
/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include "can_messages_tx.h"
#include <stdbool.h>
#include "c_utils.h"
#include "can_handler.h"
#include "bitstream.h"


static const bool handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id);

uint8_t send_max_dc_current_command
(float max_dc_current_target)
{
    bitstream_t max_dc_current_command_msg;
	uint8_t bitstream_data[2];
	bitstream_init(&max_dc_current_command_msg, bitstream_data, 2);

    
	bitstream_add(&max_dc_current_command_msg, max_dc_current_target*10, 16);
    
    can_msg_t msg;
    msg.id = 0x156;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&max_dc_current_command_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_max_dc_brake_current_command
(float max_dc_brake_current_target)
{
    bitstream_t max_dc_brake_current_command_msg;
	uint8_t bitstream_data[2];
	bitstream_init(&max_dc_brake_current_command_msg, bitstream_data, 2);

    
	bitstream_add(&max_dc_brake_current_command_msg, max_dc_brake_current_target*10, 16);
    
    can_msg_t msg;
    msg.id = 0x176;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&max_dc_brake_current_command_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_pack_status
(float voltage,float current,float amp_hours,float soc,float health)
{
    bitstream_t pack_status_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&pack_status_msg, bitstream_data, 8);

    
	bitstream_add(&pack_status_msg, voltage*10, 16);
    bitstream_add(&pack_status_msg, current*10, 16);
    bitstream_add(&pack_status_msg, amp_hours, 16);
    bitstream_add(&pack_status_msg, soc, 8);
    bitstream_add(&pack_status_msg, health, 8);
    
    can_msg_t msg;
    msg.id = 0x80;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&pack_status_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_bms_status
(uint8_t state,float temp_average,float temp_internal,uint8_t balancing)
{
    bitstream_t bms_status_msg;
	uint8_t bitstream_data[4];
	bitstream_init(&bms_status_msg, bitstream_data, 4);

    
	bitstream_add(&bms_status_msg, state, 8);
    bitstream_add(&bms_status_msg, temp_average, 8);
    bitstream_add(&bms_status_msg, temp_internal, 8);
    bitstream_add(&bms_status_msg, balancing, 8);
    
    can_msg_t msg;
    msg.id = 0x81;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&bms_status_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_cell_voltage
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val)
{
    bitstream_t cell_voltage_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&cell_voltage_msg, bitstream_data, 8);

    
	bitstream_add(&cell_voltage_msg, high_val*10000, 16);
    bitstream_add(&cell_voltage_msg, high_chip, 4);
    bitstream_add(&cell_voltage_msg, high_cell, 4);
    bitstream_add(&cell_voltage_msg, low_val*10000, 16);
    bitstream_add(&cell_voltage_msg, low_chip, 4);
    bitstream_add(&cell_voltage_msg, low_cell, 4);
    bitstream_add(&cell_voltage_msg, avg_val*10000, 16);
    
    can_msg_t msg;
    msg.id = 0x83;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&cell_voltage_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_cell_temperatures
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val)
{
    bitstream_t cell_temperatures_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&cell_temperatures_msg, bitstream_data, 8);

    
	bitstream_add(&cell_temperatures_msg, high_val*100, 16);
    bitstream_add(&cell_temperatures_msg, high_chip, 4);
    bitstream_add(&cell_temperatures_msg, high_cell, 4);
    bitstream_add(&cell_temperatures_msg, low_val*100, 16);
    bitstream_add(&cell_temperatures_msg, low_chip, 4);
    bitstream_add(&cell_temperatures_msg, low_cell, 4);
    bitstream_add(&cell_temperatures_msg, avg_val*100, 16);
    
    can_msg_t msg;
    msg.id = 0x84;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&cell_temperatures_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_segment_temperatures
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    bitstream_t segment_temperatures_msg;
	uint8_t bitstream_data[5];
	bitstream_init(&segment_temperatures_msg, bitstream_data, 5);

    
	bitstream_add(&segment_temperatures_msg, seg1, 8);
    bitstream_add(&segment_temperatures_msg, seg2, 8);
    bitstream_add(&segment_temperatures_msg, seg3, 8);
    bitstream_add(&segment_temperatures_msg, seg4, 8);
    bitstream_add(&segment_temperatures_msg, seg5, 8);
    
    can_msg_t msg;
    msg.id = 0x85;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&segment_temperatures_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_fault_status
(bool ccl_enforce,bool charger_can,bool battery_therm,bool charger_safety,bool dcl_enforce,bool external_can,bool weak_pack,bool low_cell_volts,bool charge_reading,bool current_sense,bool ic_comm,bool thermal_err,bool sw_err,bool open_wire,bool pack_overheat,bool cell_uv,bool cell_ov,bool cell_not_balancing)
{
    bitstream_t fault_status_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&fault_status_msg, bitstream_data, 8);

    
	bitstream_add(&fault_status_msg, ccl_enforce, 1);
    bitstream_add(&fault_status_msg, charger_can, 1);
    bitstream_add(&fault_status_msg, battery_therm, 1);
    bitstream_add(&fault_status_msg, charger_safety, 1);
    bitstream_add(&fault_status_msg, dcl_enforce, 1);
    bitstream_add(&fault_status_msg, external_can, 1);
    bitstream_add(&fault_status_msg, weak_pack, 1);
    bitstream_add(&fault_status_msg, low_cell_volts, 1);
    bitstream_add(&fault_status_msg, charge_reading, 1);
    bitstream_add(&fault_status_msg, current_sense, 1);
    bitstream_add(&fault_status_msg, ic_comm, 1);
    bitstream_add(&fault_status_msg, thermal_err, 1);
    bitstream_add(&fault_status_msg, sw_err, 1);
    bitstream_add(&fault_status_msg, open_wire, 1);
    bitstream_add(&fault_status_msg, pack_overheat, 1);
    bitstream_add(&fault_status_msg, cell_uv, 1);
    bitstream_add(&fault_status_msg, cell_ov, 1);
    bitstream_add(&fault_status_msg, cell_not_balancing, 1);
    
    can_msg_t msg;
    msg.id = 0x89;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&fault_status_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_segment_average_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    bitstream_t segment_average_voltages_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&segment_average_voltages_msg, bitstream_data, 8);

    
	bitstream_add(&segment_average_voltages_msg, seg1*1000, 12);
    bitstream_add(&segment_average_voltages_msg, seg2*1000, 12);
    bitstream_add(&segment_average_voltages_msg, seg3*1000, 12);
    bitstream_add(&segment_average_voltages_msg, seg4*1000, 12);
    bitstream_add(&segment_average_voltages_msg, seg5*1000, 12);
    
    can_msg_t msg;
    msg.id = 0x90;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&segment_average_voltages_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_segment_total_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    bitstream_t segment_total_voltages_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&segment_total_voltages_msg, bitstream_data, 8);

    
	bitstream_add(&segment_total_voltages_msg, seg1*39, 12);
    bitstream_add(&segment_total_voltages_msg, seg2*39, 12);
    bitstream_add(&segment_total_voltages_msg, seg3*39, 12);
    bitstream_add(&segment_total_voltages_msg, seg4*39, 12);
    bitstream_add(&segment_total_voltages_msg, seg5*39, 12);
    
    can_msg_t msg;
    msg.id = 0x91;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&segment_total_voltages_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_bms_debug
(uint8_t spare0,uint8_t spare1,uint16_t spare2,uint32_t spare3)
{
    bitstream_t bms_debug_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&bms_debug_msg, bitstream_data, 8);

    
	bitstream_add(&bms_debug_msg, spare0, 8);
    bitstream_add(&bms_debug_msg, spare1, 8);
    bitstream_add(&bms_debug_msg, spare2, 16);
    bitstream_add(&bms_debug_msg, spare3, 32);
    
    can_msg_t msg;
    msg.id = 0x702;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&bms_debug_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_bms_fault_timers
(uint8_t start_stop,uint8_t code,float value)
{
    bitstream_t bms_fault_timers_msg;
	uint8_t bitstream_data[6];
	bitstream_init(&bms_fault_timers_msg, bitstream_data, 6);

    
	bitstream_add(&bms_fault_timers_msg, start_stop, 8);
    bitstream_add(&bms_fault_timers_msg, code, 8);
    bitstream_add(&bms_fault_timers_msg, value, 32);
    
    can_msg_t msg;
    msg.id = 0x6F9;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&bms_fault_timers_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_shepherd_version_tag
(uint8_t major,uint8_t minor,uint8_t patch,bool dirty,bool local_commit)
{
    bitstream_t shepherd_version_tag_msg;
	uint8_t bitstream_data[5];
	bitstream_init(&shepherd_version_tag_msg, bitstream_data, 5);

    
	bitstream_add(&shepherd_version_tag_msg, major, 8);
    bitstream_add(&shepherd_version_tag_msg, minor, 8);
    bitstream_add(&shepherd_version_tag_msg, patch, 8);
    bitstream_add(&shepherd_version_tag_msg, dirty, 8);
    bitstream_add(&shepherd_version_tag_msg, local_commit, 8);
    
    can_msg_t msg;
    msg.id = 0x69A;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&shepherd_version_tag_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_shepherd_version_hash
(uint32_t short_hash,uint32_t author_hash)
{
    bitstream_t shepherd_version_hash_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&shepherd_version_hash_msg, bitstream_data, 8);

    
	bitstream_add(&shepherd_version_hash_msg, short_hash, 32);
    bitstream_add(&shepherd_version_hash_msg, author_hash, 32);
    
    can_msg_t msg;
    msg.id = 0x69B;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&shepherd_version_hash_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_overflow_notification_for_percell
(uint32_t overflow_can_id,uint16_t overflow_cnt)
{
    bitstream_t overflow_notification_for_percell_msg;
	uint8_t bitstream_data[6];
	bitstream_init(&overflow_notification_for_percell_msg, bitstream_data, 6);

    
	bitstream_add(&overflow_notification_for_percell_msg, overflow_can_id, 32);
    bitstream_add(&overflow_notification_for_percell_msg, overflow_cnt, 16);
    
    can_msg_t msg;
    msg.id = 0x6F1;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    return queue_can_msg(msg);
}

uint8_t send_pec_error_count_notification_per_chip
(uint8_t pec_error_chip,uint16_t pec_error_cnt)
{
    bitstream_t pec_error_count_notification_per_chip_msg;
	uint8_t bitstream_data[3];
	bitstream_init(&pec_error_count_notification_per_chip_msg, bitstream_data, 3);

    
	bitstream_add(&pec_error_count_notification_per_chip_msg, pec_error_chip, 8);
    bitstream_add(&pec_error_count_notification_per_chip_msg, pec_error_cnt, 16);
    
    can_msg_t msg;
    msg.id = 0x6F2;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&pec_error_count_notification_per_chip_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_alpha_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b)
{
    bitstream_t alpha_cell_data_debug_msg;
	uint8_t bitstream_data[7];
	bitstream_init(&alpha_cell_data_debug_msg, bitstream_data, 7);

    
	bitstream_add(&alpha_cell_data_debug_msg, therm*10, 10);
    bitstream_add(&alpha_cell_data_debug_msg, voltage_a*1000, 13);
    bitstream_add(&alpha_cell_data_debug_msg, voltage_b*1000, 13);
    bitstream_add(&alpha_cell_data_debug_msg, chip_id, 4);
    bitstream_add(&alpha_cell_data_debug_msg, cell_a, 4);
    bitstream_add(&alpha_cell_data_debug_msg, cell_b, 4);
    bitstream_add(&alpha_cell_data_debug_msg, discharging_a, 1);
    bitstream_add(&alpha_cell_data_debug_msg, discharging_b, 1);
    bitstream_add(&alpha_cell_data_debug_msg, cvs_a, 1);
    bitstream_add(&alpha_cell_data_debug_msg, cvs_b, 1);
    
    can_msg_t msg;
    msg.id = 0x6FA;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&alpha_cell_data_debug_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_beta_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b)
{
    bitstream_t beta_cell_data_debug_msg;
	uint8_t bitstream_data[7];
	bitstream_init(&beta_cell_data_debug_msg, bitstream_data, 7);

    
	bitstream_add(&beta_cell_data_debug_msg, therm*10, 10);
    bitstream_add(&beta_cell_data_debug_msg, voltage_a*1000, 13);
    bitstream_add(&beta_cell_data_debug_msg, voltage_b*1000, 13);
    bitstream_add(&beta_cell_data_debug_msg, chip_id, 4);
    bitstream_add(&beta_cell_data_debug_msg, cell_a, 4);
    bitstream_add(&beta_cell_data_debug_msg, cell_b, 4);
    bitstream_add(&beta_cell_data_debug_msg, discharging_a, 1);
    bitstream_add(&beta_cell_data_debug_msg, discharging_b, 1);
    bitstream_add(&beta_cell_data_debug_msg, cvs_a, 1);
    bitstream_add(&beta_cell_data_debug_msg, cvs_b, 1);
    
    can_msg_t msg;
    msg.id = 0x6FB;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&beta_cell_data_debug_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_beta_chip_a_debug
(float therm_last,float voltage_last,bool discharging_last,uint8_t chip_id,float seg_temp,float die_temp,float vpv)
{
    bitstream_t beta_chip_a_debug_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&beta_chip_a_debug_msg, bitstream_data, 8);

    
	bitstream_add(&beta_chip_a_debug_msg, therm_last*10, 10);
    bitstream_add(&beta_chip_a_debug_msg, voltage_last*1000, 13);
    bitstream_add(&beta_chip_a_debug_msg, discharging_last, 1);
    bitstream_add(&beta_chip_a_debug_msg, chip_id, 4);
    bitstream_add(&beta_chip_a_debug_msg, seg_temp*10, 10);
    bitstream_add(&beta_chip_a_debug_msg, die_temp*100, 13);
    bitstream_add(&beta_chip_a_debug_msg, vpv*100, 13);
    
    can_msg_t msg;
    msg.id = 0x6FD;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&beta_chip_a_debug_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_beta_chip_b_debug
(float vref2,float v_analog,float v_digital,uint8_t chip_id,float v_res,float vmv,bool cvs_last)
{
    bitstream_t beta_chip_b_debug_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&beta_chip_b_debug_msg, bitstream_data, 8);

    
	bitstream_add(&beta_chip_b_debug_msg, vref2*1000, 13);
    bitstream_add(&beta_chip_b_debug_msg, v_analog*100, 10);
    bitstream_add(&beta_chip_b_debug_msg, v_digital*100, 10);
    bitstream_add(&beta_chip_b_debug_msg, chip_id, 4);
    bitstream_add(&beta_chip_b_debug_msg, v_res*1000, 13);
    bitstream_add(&beta_chip_b_debug_msg, vmv*1000, 13);
    bitstream_add(&beta_chip_b_debug_msg, cvs_last, 1);
    
    can_msg_t msg;
    msg.id = 0x6FE;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&beta_chip_b_debug_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_beta_chip_c_debug
(bool chip_id,bool va_ov,bool va_uv,bool vd_ov,bool vd_uv,bool vde,bool vdel,bool spiflt,bool sleep,bool thsd,bool tmodchk,bool oscchk,bool otp1_med,bool otp2_med)
{
    bitstream_t beta_chip_c_debug_msg;
	uint8_t bitstream_data[3];
	bitstream_init(&beta_chip_c_debug_msg, bitstream_data, 3);

    
	bitstream_add(&beta_chip_c_debug_msg, chip_id, 4);
    bitstream_add(&beta_chip_c_debug_msg, va_ov, 1);
    bitstream_add(&beta_chip_c_debug_msg, va_uv, 1);
    bitstream_add(&beta_chip_c_debug_msg, vd_ov, 1);
    bitstream_add(&beta_chip_c_debug_msg, vd_uv, 1);
    bitstream_add(&beta_chip_c_debug_msg, vde, 1);
    bitstream_add(&beta_chip_c_debug_msg, vdel, 1);
    bitstream_add(&beta_chip_c_debug_msg, spiflt, 1);
    bitstream_add(&beta_chip_c_debug_msg, sleep, 1);
    bitstream_add(&beta_chip_c_debug_msg, thsd, 1);
    bitstream_add(&beta_chip_c_debug_msg, tmodchk, 1);
    bitstream_add(&beta_chip_c_debug_msg, oscchk, 1);
    bitstream_add(&beta_chip_c_debug_msg, otp1_med, 1);
    bitstream_add(&beta_chip_c_debug_msg, otp2_med, 1);
    
    can_msg_t msg;
    msg.id = 0x6F0;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&beta_chip_c_debug_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_alpha_chip_a_debug
(float seg_temp,uint8_t chip_id,float die_temp,float vpv,float vmv,bool va_ov,bool va_uv,bool vd_ov,bool vd_uv,bool vde,bool vdel,bool spiflt,bool sleep,bool thsd,bool tmodchk,bool oscchk)
{
    bitstream_t alpha_chip_a_debug_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&alpha_chip_a_debug_msg, bitstream_data, 8);

    
	bitstream_add(&alpha_chip_a_debug_msg, seg_temp*10, 10);
    bitstream_add(&alpha_chip_a_debug_msg, chip_id, 4);
    bitstream_add(&alpha_chip_a_debug_msg, die_temp*100, 13);
    bitstream_add(&alpha_chip_a_debug_msg, vpv*100, 13);
    bitstream_add(&alpha_chip_a_debug_msg, vmv*1000, 13);
    bitstream_add(&alpha_chip_a_debug_msg, va_ov, 1);
    bitstream_add(&alpha_chip_a_debug_msg, va_uv, 1);
    bitstream_add(&alpha_chip_a_debug_msg, vd_ov, 1);
    bitstream_add(&alpha_chip_a_debug_msg, vd_uv, 1);
    bitstream_add(&alpha_chip_a_debug_msg, vde, 1);
    bitstream_add(&alpha_chip_a_debug_msg, vdel, 1);
    bitstream_add(&alpha_chip_a_debug_msg, spiflt, 1);
    bitstream_add(&alpha_chip_a_debug_msg, sleep, 1);
    bitstream_add(&alpha_chip_a_debug_msg, thsd, 1);
    bitstream_add(&alpha_chip_a_debug_msg, tmodchk, 1);
    bitstream_add(&alpha_chip_a_debug_msg, oscchk, 1);
    
    can_msg_t msg;
    msg.id = 0x6FC;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&alpha_chip_a_debug_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_alpha_chip_b_debug
(float vres,uint8_t chip_id,float vref2,float v_analog,float v_digital,bool otp1_med,bool opt2_med)
{
    bitstream_t alpha_chip_b_debug_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&alpha_chip_b_debug_msg, bitstream_data, 8);

    
	bitstream_add(&alpha_chip_b_debug_msg, vres*1000, 13);
    bitstream_add(&alpha_chip_b_debug_msg, chip_id, 4);
    bitstream_add(&alpha_chip_b_debug_msg, vref2*1000, 13);
    bitstream_add(&alpha_chip_b_debug_msg, v_analog*1000, 13);
    bitstream_add(&alpha_chip_b_debug_msg, v_digital*1000, 13);
    bitstream_add(&alpha_chip_b_debug_msg, otp1_med, 1);
    bitstream_add(&alpha_chip_b_debug_msg, opt2_med, 1);
    
    can_msg_t msg;
    msg.id = 0x6FF;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&alpha_chip_b_debug_msg, msg.id);
    
    return queue_can_msg(msg);
}

uint8_t send_bms_charge_message_send
(float charge_volts,float charge_current,uint8_t enable_charging)
{
    bitstream_t bms_charge_message_send_msg;
	uint8_t bitstream_data[8];
	bitstream_init(&bms_charge_message_send_msg, bitstream_data, 8);

    
	bitstream_add(&bms_charge_message_send_msg, charge_volts*10, 16);
    bitstream_add(&bms_charge_message_send_msg, charge_current*10, 16);
    bitstream_add(&bms_charge_message_send_msg, enable_charging, 8);
    
    can_msg_t msg;
    msg.id = 0x1806E5F4;
    msg.len = sizeof(bitstream_data);
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    
    handle_bitstream_overflow(&bms_charge_message_send_msg, msg.id);
    
    return queue_can_msg(msg);
}



/// @brief A helper which sends appropriate error to stdout and CAN if a bistream overflows
/// @param bitstream_res The bitstream to check for overflow
/// @param can_id The CAN ID this bistream data is intended for
/// @return 0 if success
static const bool handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id)
{
	if (!bitstream_res->overflow) {
		return 0;
	}

    static uint16_t overflow_cnt = 0;
	overflow_cnt++;

    return send_overflow_notification_for_percell(can_id, overflow_cnt);
}