
/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include "can_messages_tx.h"
#include <stdbool.h>

#include "u_queues.h"
#include "u_tx_debug.h"
#include "c_utils.h"
#include "fdcan.h"
#include "bitstream.h"


static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id);

uint8_t send_max_ac_current_command
(float max_current_ac_target)
{
    can_msg_t msg;
    msg.id = 0x116;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        int32_t max_current_ac_target_i = (int32_t)(max_current_ac_target*10);
                        if(max_current_ac_target_i > 32767) {max_current_ac_target_i = 32767;
                        } else if(max_current_ac_target_i < -32768) {max_current_ac_target_i = -32768;
                        }
                        data |= ((uint32_t)(max_current_ac_target_i) & 0xFFFFULL) << 48;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_max_ac_brake_current_command
(float max_ac_brake_current_target)
{
    can_msg_t msg;
    msg.id = 0x136;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        int32_t max_ac_brake_current_target_i = (int32_t)(max_ac_brake_current_target*10);
                        if(max_ac_brake_current_target_i > 32767) {max_ac_brake_current_target_i = 32767;
                        } else if(max_ac_brake_current_target_i < -32768) {max_ac_brake_current_target_i = -32768;
                        }
                        data |= ((uint32_t)(max_ac_brake_current_target_i) & 0xFFFFULL) << 48;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_max_dc_current_command
(float max_dc_current_target)
{
    can_msg_t msg;
    msg.id = 0x156;
    msg.id_is_extended = false;
    msg.len = 2;

    
            uint16_t data = 0;
                        int32_t max_dc_current_target_i = (int32_t)(max_dc_current_target*10);
                        if(max_dc_current_target_i > 32767) {max_dc_current_target_i = 32767;
                        } else if(max_dc_current_target_i < -32768) {max_dc_current_target_i = -32768;
                        }
                        data |= ((uint32_t)(max_dc_current_target_i) & 0xFFFFULL) << 0;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_max_dc_brake_current_command
(float max_dc_brake_current_target)
{
    can_msg_t msg;
    msg.id = 0x176;
    msg.id_is_extended = false;
    msg.len = 2;

    
            uint16_t data = 0;
                        int32_t max_dc_brake_current_target_i = (int32_t)(max_dc_brake_current_target*10);
                        if(max_dc_brake_current_target_i > 32767) {max_dc_brake_current_target_i = 32767;
                        } else if(max_dc_brake_current_target_i < -32768) {max_dc_brake_current_target_i = -32768;
                        }
                        data |= ((uint32_t)(max_dc_brake_current_target_i) & 0xFFFFULL) << 0;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_pack_status
(float voltage,float current,float amp_hours,float soc,float health)
{
    can_msg_t msg;
    msg.id = 0x80;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t voltage_i = (uint32_t)(voltage*10);
                        if(voltage_i > 65535ULL) {voltage_i = 65535;
                        }
                        data |= ((voltage_i) & 0xFFFFULL) << 48;
            
                        int32_t current_i = (int32_t)(current*10);
                        if(current_i > 32767) {current_i = 32767;
                        } else if(current_i < -32768) {current_i = -32768;
                        }
                        data |= ((uint32_t)(current_i) & 0xFFFFULL) << 32;
            
                        uint32_t amp_hours_i = (uint32_t)(amp_hours);
                        if(amp_hours_i > 65535ULL) {amp_hours_i = 65535;
                        }
                        data |= ((amp_hours_i) & 0xFFFFULL) << 16;
            
                        uint32_t soc_i = (uint32_t)(soc);
                        if(soc_i > 255ULL) {soc_i = 255;
                        }
                        data |= ((soc_i) & 0xFFULL) << 8;
            
                        uint32_t health_i = (uint32_t)(health);
                        if(health_i > 255ULL) {health_i = 255;
                        }
                        data |= ((health_i) & 0xFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_bms_status
(uint8_t state,float temp_average,float temp_internal,uint8_t balancing)
{
    can_msg_t msg;
    msg.id = 0x81;
    msg.id_is_extended = false;
    msg.len = 4;

    
            uint32_t data = 0;
                        uint32_t state_i = (uint32_t)(state);
                        if(state_i > 255ULL) {state_i = 255;
                        }
                        data |= ((state_i) & 0xFFULL) << 24;
            
                        uint32_t temp_average_i = (uint32_t)(temp_average);
                        if(temp_average_i > 255ULL) {temp_average_i = 255;
                        }
                        data |= ((temp_average_i) & 0xFFULL) << 16;
            
                        uint32_t temp_internal_i = (uint32_t)(temp_internal);
                        if(temp_internal_i > 255ULL) {temp_internal_i = 255;
                        }
                        data |= ((temp_internal_i) & 0xFFULL) << 8;
            
                        uint32_t balancing_i = (uint32_t)(balancing);
                        if(balancing_i > 255ULL) {balancing_i = 255;
                        }
                        data |= ((balancing_i) & 0xFFULL) << 0;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_cell_voltage
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val)
{
    can_msg_t msg;
    msg.id = 0x83;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t high_val_i = (uint32_t)(high_val*10000);
                        if(high_val_i > 65535ULL) {high_val_i = 65535;
                        }
                        data |= ((high_val_i) & 0xFFFFULL) << 48;
            
                        uint32_t high_chip_i = (uint32_t)(high_chip);
                        if(high_chip_i > 15ULL) {high_chip_i = 15;
                        }
                        data |= ((high_chip_i) & 0xFULL) << 44;
            
                        uint32_t high_cell_i = (uint32_t)(high_cell);
                        if(high_cell_i > 15ULL) {high_cell_i = 15;
                        }
                        data |= ((high_cell_i) & 0xFULL) << 40;
            
                        uint32_t low_val_i = (uint32_t)(low_val*10000);
                        if(low_val_i > 65535ULL) {low_val_i = 65535;
                        }
                        data |= ((low_val_i) & 0xFFFFULL) << 24;
            
                        uint32_t low_chip_i = (uint32_t)(low_chip);
                        if(low_chip_i > 15ULL) {low_chip_i = 15;
                        }
                        data |= ((low_chip_i) & 0xFULL) << 20;
            
                        uint32_t low_cell_i = (uint32_t)(low_cell);
                        if(low_cell_i > 15ULL) {low_cell_i = 15;
                        }
                        data |= ((low_cell_i) & 0xFULL) << 16;
            
                        uint32_t avg_val_i = (uint32_t)(avg_val*10000);
                        if(avg_val_i > 65535ULL) {avg_val_i = 65535;
                        }
                        data |= ((avg_val_i) & 0xFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_cell_temperatures
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val)
{
    can_msg_t msg;
    msg.id = 0x84;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t high_val_i = (uint32_t)(high_val*100);
                        if(high_val_i > 65535ULL) {high_val_i = 65535;
                        }
                        data |= ((high_val_i) & 0xFFFFULL) << 48;
            
                        uint32_t high_chip_i = (uint32_t)(high_chip);
                        if(high_chip_i > 15ULL) {high_chip_i = 15;
                        }
                        data |= ((high_chip_i) & 0xFULL) << 44;
            
                        uint32_t high_cell_i = (uint32_t)(high_cell);
                        if(high_cell_i > 15ULL) {high_cell_i = 15;
                        }
                        data |= ((high_cell_i) & 0xFULL) << 40;
            
                        uint32_t low_val_i = (uint32_t)(low_val*100);
                        if(low_val_i > 65535ULL) {low_val_i = 65535;
                        }
                        data |= ((low_val_i) & 0xFFFFULL) << 24;
            
                        uint32_t low_chip_i = (uint32_t)(low_chip);
                        if(low_chip_i > 15ULL) {low_chip_i = 15;
                        }
                        data |= ((low_chip_i) & 0xFULL) << 20;
            
                        uint32_t low_cell_i = (uint32_t)(low_cell);
                        if(low_cell_i > 15ULL) {low_cell_i = 15;
                        }
                        data |= ((low_cell_i) & 0xFULL) << 16;
            
                        uint32_t avg_val_i = (uint32_t)(avg_val*100);
                        if(avg_val_i > 65535ULL) {avg_val_i = 65535;
                        }
                        data |= ((avg_val_i) & 0xFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_temperatures
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    can_msg_t msg;
    msg.id = 0x85;
    msg.id_is_extended = false;
    msg.len = 5;

    
            uint64_t data = 0;
                        int32_t seg1_i = (int32_t)(seg1);
                        if(seg1_i > 127) {seg1_i = 127;
                        } else if(seg1_i < -128) {seg1_i = -128;
                        }
                        data |= ((uint32_t)(seg1_i) & 0xFFULL) << 56;
            
                        int32_t seg2_i = (int32_t)(seg2);
                        if(seg2_i > 127) {seg2_i = 127;
                        } else if(seg2_i < -128) {seg2_i = -128;
                        }
                        data |= ((uint32_t)(seg2_i) & 0xFFULL) << 48;
            
                        int32_t seg3_i = (int32_t)(seg3);
                        if(seg3_i > 127) {seg3_i = 127;
                        } else if(seg3_i < -128) {seg3_i = -128;
                        }
                        data |= ((uint32_t)(seg3_i) & 0xFFULL) << 40;
            
                        int32_t seg4_i = (int32_t)(seg4);
                        if(seg4_i > 127) {seg4_i = 127;
                        } else if(seg4_i < -128) {seg4_i = -128;
                        }
                        data |= ((uint32_t)(seg4_i) & 0xFFULL) << 32;
            
                        int32_t seg5_i = (int32_t)(seg5);
                        if(seg5_i > 127) {seg5_i = 127;
                        } else if(seg5_i < -128) {seg5_i = -128;
                        }
                        data |= ((uint32_t)(seg5_i) & 0xFFULL) << 24;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_isospi_communication_status
(uint8_t state,uint8_t break_location,uint8_t verification_attempts,uint8_t recovery_successful)
{
    can_msg_t msg;
    msg.id = 0x86;
    msg.id_is_extended = false;
    msg.len = 4;

    
            uint32_t data = 0;
                        uint32_t state_i = (uint32_t)(state);
                        if(state_i > 255ULL) {state_i = 255;
                        }
                        data |= ((state_i) & 0xFFULL) << 24;
            
                        uint32_t break_location_i = (uint32_t)(break_location);
                        if(break_location_i > 255ULL) {break_location_i = 255;
                        }
                        data |= ((break_location_i) & 0xFFULL) << 16;
            
                        uint32_t verification_attempts_i = (uint32_t)(verification_attempts);
                        if(verification_attempts_i > 255ULL) {verification_attempts_i = 255;
                        }
                        data |= ((verification_attempts_i) & 0xFFULL) << 8;
            
                        uint32_t recovery_successful_i = (uint32_t)(recovery_successful);
                        if(recovery_successful_i > 255ULL) {recovery_successful_i = 255;
                        }
                        data |= ((recovery_successful_i) & 0xFFULL) << 0;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_fault_status
(bool ccl_enforce,bool charger_can,bool battery_therm,bool charger_safety,bool dcl_enforce,bool external_can,bool weak_pack,bool low_cell_volts,bool charge_reading,bool current_sense,bool ic_comm,bool thermal_err,bool sw_err,bool open_wire,bool pack_overheat,bool cell_uv,bool cell_ov,bool cell_not_balancing)
{
    can_msg_t msg;
    msg.id = 0x89;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t ccl_enforce_i = (uint32_t)(ccl_enforce);
                        if(ccl_enforce_i > 1ULL) {ccl_enforce_i = 1;
                        }
                        data |= ((ccl_enforce_i) & 0x1ULL) << 63;
            
                        uint32_t charger_can_i = (uint32_t)(charger_can);
                        if(charger_can_i > 1ULL) {charger_can_i = 1;
                        }
                        data |= ((charger_can_i) & 0x1ULL) << 62;
            
                        uint32_t battery_therm_i = (uint32_t)(battery_therm);
                        if(battery_therm_i > 1ULL) {battery_therm_i = 1;
                        }
                        data |= ((battery_therm_i) & 0x1ULL) << 61;
            
                        uint32_t charger_safety_i = (uint32_t)(charger_safety);
                        if(charger_safety_i > 1ULL) {charger_safety_i = 1;
                        }
                        data |= ((charger_safety_i) & 0x1ULL) << 60;
            
                        uint32_t dcl_enforce_i = (uint32_t)(dcl_enforce);
                        if(dcl_enforce_i > 1ULL) {dcl_enforce_i = 1;
                        }
                        data |= ((dcl_enforce_i) & 0x1ULL) << 59;
            
                        uint32_t external_can_i = (uint32_t)(external_can);
                        if(external_can_i > 1ULL) {external_can_i = 1;
                        }
                        data |= ((external_can_i) & 0x1ULL) << 58;
            
                        uint32_t weak_pack_i = (uint32_t)(weak_pack);
                        if(weak_pack_i > 1ULL) {weak_pack_i = 1;
                        }
                        data |= ((weak_pack_i) & 0x1ULL) << 57;
            
                        uint32_t low_cell_volts_i = (uint32_t)(low_cell_volts);
                        if(low_cell_volts_i > 1ULL) {low_cell_volts_i = 1;
                        }
                        data |= ((low_cell_volts_i) & 0x1ULL) << 56;
            
                        uint32_t charge_reading_i = (uint32_t)(charge_reading);
                        if(charge_reading_i > 1ULL) {charge_reading_i = 1;
                        }
                        data |= ((charge_reading_i) & 0x1ULL) << 55;
            
                        uint32_t current_sense_i = (uint32_t)(current_sense);
                        if(current_sense_i > 1ULL) {current_sense_i = 1;
                        }
                        data |= ((current_sense_i) & 0x1ULL) << 54;
            
                        uint32_t ic_comm_i = (uint32_t)(ic_comm);
                        if(ic_comm_i > 1ULL) {ic_comm_i = 1;
                        }
                        data |= ((ic_comm_i) & 0x1ULL) << 53;
            
                        uint32_t thermal_err_i = (uint32_t)(thermal_err);
                        if(thermal_err_i > 1ULL) {thermal_err_i = 1;
                        }
                        data |= ((thermal_err_i) & 0x1ULL) << 52;
            
                        uint32_t sw_err_i = (uint32_t)(sw_err);
                        if(sw_err_i > 1ULL) {sw_err_i = 1;
                        }
                        data |= ((sw_err_i) & 0x1ULL) << 51;
            
                        uint32_t open_wire_i = (uint32_t)(open_wire);
                        if(open_wire_i > 1ULL) {open_wire_i = 1;
                        }
                        data |= ((open_wire_i) & 0x1ULL) << 50;
            
                        uint32_t pack_overheat_i = (uint32_t)(pack_overheat);
                        if(pack_overheat_i > 1ULL) {pack_overheat_i = 1;
                        }
                        data |= ((pack_overheat_i) & 0x1ULL) << 49;
            
                        uint32_t cell_uv_i = (uint32_t)(cell_uv);
                        if(cell_uv_i > 1ULL) {cell_uv_i = 1;
                        }
                        data |= ((cell_uv_i) & 0x1ULL) << 48;
            
                        uint32_t cell_ov_i = (uint32_t)(cell_ov);
                        if(cell_ov_i > 1ULL) {cell_ov_i = 1;
                        }
                        data |= ((cell_ov_i) & 0x1ULL) << 47;
            
                        uint32_t cell_not_balancing_i = (uint32_t)(cell_not_balancing);
                        if(cell_not_balancing_i > 1ULL) {cell_not_balancing_i = 1;
                        }
                        data |= ((cell_not_balancing_i) & 0x1ULL) << 46;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_average_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    can_msg_t msg;
    msg.id = 0x90;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t seg1_i = (uint32_t)(seg1*1000);
                        if(seg1_i > 4095ULL) {seg1_i = 4095;
                        }
                        data |= ((seg1_i) & 0xFFFULL) << 52;
            
                        uint32_t seg2_i = (uint32_t)(seg2*1000);
                        if(seg2_i > 4095ULL) {seg2_i = 4095;
                        }
                        data |= ((seg2_i) & 0xFFFULL) << 40;
            
                        uint32_t seg3_i = (uint32_t)(seg3*1000);
                        if(seg3_i > 4095ULL) {seg3_i = 4095;
                        }
                        data |= ((seg3_i) & 0xFFFULL) << 28;
            
                        uint32_t seg4_i = (uint32_t)(seg4*1000);
                        if(seg4_i > 4095ULL) {seg4_i = 4095;
                        }
                        data |= ((seg4_i) & 0xFFFULL) << 16;
            
                        uint32_t seg5_i = (uint32_t)(seg5*1000);
                        if(seg5_i > 4095ULL) {seg5_i = 4095;
                        }
                        data |= ((seg5_i) & 0xFFFULL) << 4;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_total_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    can_msg_t msg;
    msg.id = 0x91;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t seg1_i = (uint32_t)(seg1*39);
                        if(seg1_i > 4095ULL) {seg1_i = 4095;
                        }
                        data |= ((seg1_i) & 0xFFFULL) << 52;
            
                        uint32_t seg2_i = (uint32_t)(seg2*39);
                        if(seg2_i > 4095ULL) {seg2_i = 4095;
                        }
                        data |= ((seg2_i) & 0xFFFULL) << 40;
            
                        uint32_t seg3_i = (uint32_t)(seg3*39);
                        if(seg3_i > 4095ULL) {seg3_i = 4095;
                        }
                        data |= ((seg3_i) & 0xFFFULL) << 28;
            
                        uint32_t seg4_i = (uint32_t)(seg4*39);
                        if(seg4_i > 4095ULL) {seg4_i = 4095;
                        }
                        data |= ((seg4_i) & 0xFFFULL) << 16;
            
                        uint32_t seg5_i = (uint32_t)(seg5*39);
                        if(seg5_i > 4095ULL) {seg5_i = 4095;
                        }
                        data |= ((seg5_i) & 0xFFFULL) << 4;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_delta_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    can_msg_t msg;
    msg.id = 0x92;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t seg1_i = (uint32_t)(seg1*1000);
                        if(seg1_i > 4095ULL) {seg1_i = 4095;
                        }
                        data |= ((seg1_i) & 0xFFFULL) << 52;
            
                        uint32_t seg2_i = (uint32_t)(seg2*1000);
                        if(seg2_i > 4095ULL) {seg2_i = 4095;
                        }
                        data |= ((seg2_i) & 0xFFFULL) << 40;
            
                        uint32_t seg3_i = (uint32_t)(seg3*1000);
                        if(seg3_i > 4095ULL) {seg3_i = 4095;
                        }
                        data |= ((seg3_i) & 0xFFFULL) << 28;
            
                        uint32_t seg4_i = (uint32_t)(seg4*1000);
                        if(seg4_i > 4095ULL) {seg4_i = 4095;
                        }
                        data |= ((seg4_i) & 0xFFFULL) << 16;
            
                        uint32_t seg5_i = (uint32_t)(seg5*1000);
                        if(seg5_i > 4095ULL) {seg5_i = 4095;
                        }
                        data |= ((seg5_i) & 0xFFFULL) << 4;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_bms_debug
(uint8_t spare0,uint8_t spare1,uint16_t spare2,uint32_t spare3)
{
    can_msg_t msg;
    msg.id = 0x702;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t spare0_i = (uint32_t)(spare0);
                        if(spare0_i > 255ULL) {spare0_i = 255;
                        }
                        data |= ((spare0_i) & 0xFFULL) << 56;
            
                        uint32_t spare1_i = (uint32_t)(spare1);
                        if(spare1_i > 255ULL) {spare1_i = 255;
                        }
                        data |= ((spare1_i) & 0xFFULL) << 48;
            
                        uint32_t spare2_i = (uint32_t)(spare2);
                        if(spare2_i > 65535ULL) {spare2_i = 65535;
                        }
                        data |= ((spare2_i) & 0xFFFFULL) << 32;
            
                        uint32_t spare3_i = (uint32_t)(spare3);
                        if(spare3_i > 4294967295ULL) {spare3_i = 4294967295;
                        }
                        data |= ((spare3_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_bms_fault_timers
(uint8_t start_stop,uint8_t code,float value)
{
    can_msg_t msg;
    msg.id = 0x6F9;
    msg.id_is_extended = false;
    msg.len = 6;

    
            uint64_t data = 0;
                        uint32_t start_stop_i = (uint32_t)(start_stop);
                        if(start_stop_i > 255ULL) {start_stop_i = 255;
                        }
                        data |= ((start_stop_i) & 0xFFULL) << 56;
            
                        uint32_t code_i = (uint32_t)(code);
                        if(code_i > 255ULL) {code_i = 255;
                        }
                        data |= ((code_i) & 0xFFULL) << 48;
            
                        uint32_t value_i = (uint32_t)(value);
                        if(value_i > 4294967295ULL) {value_i = 4294967295;
                        }
                        data |= ((value_i) & 0xFFFFFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_shepherd_version_tag
(uint8_t major,uint8_t minor,uint8_t patch,bool dirty,bool local_commit)
{
    can_msg_t msg;
    msg.id = 0x69A;
    msg.id_is_extended = false;
    msg.len = 5;

    
            uint64_t data = 0;
                        uint32_t major_i = (uint32_t)(major);
                        if(major_i > 255ULL) {major_i = 255;
                        }
                        data |= ((major_i) & 0xFFULL) << 56;
            
                        uint32_t minor_i = (uint32_t)(minor);
                        if(minor_i > 255ULL) {minor_i = 255;
                        }
                        data |= ((minor_i) & 0xFFULL) << 48;
            
                        uint32_t patch_i = (uint32_t)(patch);
                        if(patch_i > 255ULL) {patch_i = 255;
                        }
                        data |= ((patch_i) & 0xFFULL) << 40;
            
                        uint32_t dirty_i = (uint32_t)(dirty);
                        if(dirty_i > 255ULL) {dirty_i = 255;
                        }
                        data |= ((dirty_i) & 0xFFULL) << 32;
            
                        uint32_t local_commit_i = (uint32_t)(local_commit);
                        if(local_commit_i > 255ULL) {local_commit_i = 255;
                        }
                        data |= ((local_commit_i) & 0xFFULL) << 24;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_shepherd_version_hash
(uint32_t short_hash,uint32_t author_hash)
{
    can_msg_t msg;
    msg.id = 0x69B;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t short_hash_i = (uint32_t)(short_hash);
                        if(short_hash_i > 4294967295ULL) {short_hash_i = 4294967295;
                        }
                        data |= ((short_hash_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t author_hash_i = (uint32_t)(author_hash);
                        if(author_hash_i > 4294967295ULL) {author_hash_i = 4294967295;
                        }
                        data |= ((author_hash_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_overflow_notification_for_percell
(uint32_t overflow_can_id,uint16_t overflow_cnt)
{
    can_msg_t msg;
    msg.id = 0x6F1;
    msg.id_is_extended = false;
    msg.len = 6;

    
            uint64_t data = 0;
                        uint32_t overflow_can_id_i = (uint32_t)(overflow_can_id);
                        if(overflow_can_id_i > 4294967295ULL) {overflow_can_id_i = 4294967295;
                        }
                        data |= ((overflow_can_id_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t overflow_cnt_i = (uint32_t)(overflow_cnt);
                        if(overflow_cnt_i > 65535ULL) {overflow_cnt_i = 65535;
                        }
                        data |= ((overflow_cnt_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_pec_error_count_notification_per_chip
(uint8_t pec_error_chip,uint16_t pec_error_cnt)
{
    can_msg_t msg;
    msg.id = 0x6F2;
    msg.id_is_extended = false;
    msg.len = 3;

    
            uint32_t data = 0;
                        uint32_t pec_error_chip_i = (uint32_t)(pec_error_chip);
                        if(pec_error_chip_i > 255ULL) {pec_error_chip_i = 255;
                        }
                        data |= ((pec_error_chip_i) & 0xFFULL) << 24;
            
                        uint32_t pec_error_cnt_i = (uint32_t)(pec_error_cnt);
                        if(pec_error_cnt_i > 65535ULL) {pec_error_cnt_i = 65535;
                        }
                        data |= ((pec_error_cnt_i) & 0xFFFFULL) << 8;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_alpha_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b)
{
    can_msg_t msg;
    msg.id = 0x6FA;
    msg.id_is_extended = false;
    msg.len = 7;

    
            uint64_t data = 0;
                        uint32_t therm_i = (uint32_t)(therm*10);
                        if(therm_i > 1023ULL) {therm_i = 1023;
                        }
                        data |= ((therm_i) & 0x3FFULL) << 54;
            
                        uint32_t voltage_a_i = (uint32_t)(voltage_a*1000);
                        if(voltage_a_i > 8191ULL) {voltage_a_i = 8191;
                        }
                        data |= ((voltage_a_i) & 0x1FFFULL) << 41;
            
                        uint32_t voltage_b_i = (uint32_t)(voltage_b*1000);
                        if(voltage_b_i > 8191ULL) {voltage_b_i = 8191;
                        }
                        data |= ((voltage_b_i) & 0x1FFFULL) << 28;
            
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 24;
            
                        uint32_t cell_a_i = (uint32_t)(cell_a);
                        if(cell_a_i > 15ULL) {cell_a_i = 15;
                        }
                        data |= ((cell_a_i) & 0xFULL) << 20;
            
                        uint32_t cell_b_i = (uint32_t)(cell_b);
                        if(cell_b_i > 15ULL) {cell_b_i = 15;
                        }
                        data |= ((cell_b_i) & 0xFULL) << 16;
            
                        uint32_t discharging_a_i = (uint32_t)(discharging_a);
                        if(discharging_a_i > 1ULL) {discharging_a_i = 1;
                        }
                        data |= ((discharging_a_i) & 0x1ULL) << 15;
            
                        uint32_t discharging_b_i = (uint32_t)(discharging_b);
                        if(discharging_b_i > 1ULL) {discharging_b_i = 1;
                        }
                        data |= ((discharging_b_i) & 0x1ULL) << 14;
            
                        uint32_t cvs_a_i = (uint32_t)(cvs_a);
                        if(cvs_a_i > 1ULL) {cvs_a_i = 1;
                        }
                        data |= ((cvs_a_i) & 0x1ULL) << 13;
            
                        uint32_t cvs_b_i = (uint32_t)(cvs_b);
                        if(cvs_b_i > 1ULL) {cvs_b_i = 1;
                        }
                        data |= ((cvs_b_i) & 0x1ULL) << 12;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_beta_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b)
{
    can_msg_t msg;
    msg.id = 0x6FB;
    msg.id_is_extended = false;
    msg.len = 7;

    
            uint64_t data = 0;
                        uint32_t therm_i = (uint32_t)(therm*10);
                        if(therm_i > 1023ULL) {therm_i = 1023;
                        }
                        data |= ((therm_i) & 0x3FFULL) << 54;
            
                        uint32_t voltage_a_i = (uint32_t)(voltage_a*1000);
                        if(voltage_a_i > 8191ULL) {voltage_a_i = 8191;
                        }
                        data |= ((voltage_a_i) & 0x1FFFULL) << 41;
            
                        uint32_t voltage_b_i = (uint32_t)(voltage_b*1000);
                        if(voltage_b_i > 8191ULL) {voltage_b_i = 8191;
                        }
                        data |= ((voltage_b_i) & 0x1FFFULL) << 28;
            
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 24;
            
                        uint32_t cell_a_i = (uint32_t)(cell_a);
                        if(cell_a_i > 15ULL) {cell_a_i = 15;
                        }
                        data |= ((cell_a_i) & 0xFULL) << 20;
            
                        uint32_t cell_b_i = (uint32_t)(cell_b);
                        if(cell_b_i > 15ULL) {cell_b_i = 15;
                        }
                        data |= ((cell_b_i) & 0xFULL) << 16;
            
                        uint32_t discharging_a_i = (uint32_t)(discharging_a);
                        if(discharging_a_i > 1ULL) {discharging_a_i = 1;
                        }
                        data |= ((discharging_a_i) & 0x1ULL) << 15;
            
                        uint32_t discharging_b_i = (uint32_t)(discharging_b);
                        if(discharging_b_i > 1ULL) {discharging_b_i = 1;
                        }
                        data |= ((discharging_b_i) & 0x1ULL) << 14;
            
                        uint32_t cvs_a_i = (uint32_t)(cvs_a);
                        if(cvs_a_i > 1ULL) {cvs_a_i = 1;
                        }
                        data |= ((cvs_a_i) & 0x1ULL) << 13;
            
                        uint32_t cvs_b_i = (uint32_t)(cvs_b);
                        if(cvs_b_i > 1ULL) {cvs_b_i = 1;
                        }
                        data |= ((cvs_b_i) & 0x1ULL) << 12;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_beta_chip_a_debug
(float therm_last,float voltage_last,bool discharging_last,uint8_t chip_id,float seg_temp,float die_temp,float vpv)
{
    can_msg_t msg;
    msg.id = 0x6FD;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t therm_last_i = (uint32_t)(therm_last*10);
                        if(therm_last_i > 1023ULL) {therm_last_i = 1023;
                        }
                        data |= ((therm_last_i) & 0x3FFULL) << 54;
            
                        uint32_t voltage_last_i = (uint32_t)(voltage_last*1000);
                        if(voltage_last_i > 8191ULL) {voltage_last_i = 8191;
                        }
                        data |= ((voltage_last_i) & 0x1FFFULL) << 41;
            
                        uint32_t discharging_last_i = (uint32_t)(discharging_last);
                        if(discharging_last_i > 1ULL) {discharging_last_i = 1;
                        }
                        data |= ((discharging_last_i) & 0x1ULL) << 40;
            
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 36;
            
                        uint32_t seg_temp_i = (uint32_t)(seg_temp*10);
                        if(seg_temp_i > 1023ULL) {seg_temp_i = 1023;
                        }
                        data |= ((seg_temp_i) & 0x3FFULL) << 26;
            
                        uint32_t die_temp_i = (uint32_t)(die_temp*100);
                        if(die_temp_i > 8191ULL) {die_temp_i = 8191;
                        }
                        data |= ((die_temp_i) & 0x1FFFULL) << 13;
            
                        uint32_t vpv_i = (uint32_t)(vpv*100);
                        if(vpv_i > 8191ULL) {vpv_i = 8191;
                        }
                        data |= ((vpv_i) & 0x1FFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_beta_chip_b_debug
(float vref2,float v_analog,float v_digital,uint8_t chip_id,float v_res,float vmv,bool cvs_last)
{
    can_msg_t msg;
    msg.id = 0x6FE;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t vref2_i = (uint32_t)(vref2*1000);
                        if(vref2_i > 8191ULL) {vref2_i = 8191;
                        }
                        data |= ((vref2_i) & 0x1FFFULL) << 51;
            
                        uint32_t v_analog_i = (uint32_t)(v_analog*100);
                        if(v_analog_i > 1023ULL) {v_analog_i = 1023;
                        }
                        data |= ((v_analog_i) & 0x3FFULL) << 41;
            
                        uint32_t v_digital_i = (uint32_t)(v_digital*100);
                        if(v_digital_i > 1023ULL) {v_digital_i = 1023;
                        }
                        data |= ((v_digital_i) & 0x3FFULL) << 31;
            
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 27;
            
                        uint32_t v_res_i = (uint32_t)(v_res*1000);
                        if(v_res_i > 8191ULL) {v_res_i = 8191;
                        }
                        data |= ((v_res_i) & 0x1FFFULL) << 14;
            
                        uint32_t vmv_i = (uint32_t)(vmv*1000);
                        if(vmv_i > 8191ULL) {vmv_i = 8191;
                        }
                        data |= ((vmv_i) & 0x1FFFULL) << 1;
            
                        uint32_t cvs_last_i = (uint32_t)(cvs_last);
                        if(cvs_last_i > 1ULL) {cvs_last_i = 1;
                        }
                        data |= ((cvs_last_i) & 0x1ULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_beta_chip_c_debug
(bool chip_id,bool va_ov,bool va_uv,bool vd_ov,bool vd_uv,bool vde,bool vdel,bool spiflt,bool sleep,bool thsd,bool tmodchk,bool oscchk,bool otp1_med,bool otp2_med)
{
    can_msg_t msg;
    msg.id = 0x6F0;
    msg.id_is_extended = false;
    msg.len = 3;

    
            uint32_t data = 0;
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 28;
            
                        uint32_t va_ov_i = (uint32_t)(va_ov);
                        if(va_ov_i > 1ULL) {va_ov_i = 1;
                        }
                        data |= ((va_ov_i) & 0x1ULL) << 27;
            
                        uint32_t va_uv_i = (uint32_t)(va_uv);
                        if(va_uv_i > 1ULL) {va_uv_i = 1;
                        }
                        data |= ((va_uv_i) & 0x1ULL) << 26;
            
                        uint32_t vd_ov_i = (uint32_t)(vd_ov);
                        if(vd_ov_i > 1ULL) {vd_ov_i = 1;
                        }
                        data |= ((vd_ov_i) & 0x1ULL) << 25;
            
                        uint32_t vd_uv_i = (uint32_t)(vd_uv);
                        if(vd_uv_i > 1ULL) {vd_uv_i = 1;
                        }
                        data |= ((vd_uv_i) & 0x1ULL) << 24;
            
                        uint32_t vde_i = (uint32_t)(vde);
                        if(vde_i > 1ULL) {vde_i = 1;
                        }
                        data |= ((vde_i) & 0x1ULL) << 23;
            
                        uint32_t vdel_i = (uint32_t)(vdel);
                        if(vdel_i > 1ULL) {vdel_i = 1;
                        }
                        data |= ((vdel_i) & 0x1ULL) << 22;
            
                        uint32_t spiflt_i = (uint32_t)(spiflt);
                        if(spiflt_i > 1ULL) {spiflt_i = 1;
                        }
                        data |= ((spiflt_i) & 0x1ULL) << 21;
            
                        uint32_t sleep_i = (uint32_t)(sleep);
                        if(sleep_i > 1ULL) {sleep_i = 1;
                        }
                        data |= ((sleep_i) & 0x1ULL) << 20;
            
                        uint32_t thsd_i = (uint32_t)(thsd);
                        if(thsd_i > 1ULL) {thsd_i = 1;
                        }
                        data |= ((thsd_i) & 0x1ULL) << 19;
            
                        uint32_t tmodchk_i = (uint32_t)(tmodchk);
                        if(tmodchk_i > 1ULL) {tmodchk_i = 1;
                        }
                        data |= ((tmodchk_i) & 0x1ULL) << 18;
            
                        uint32_t oscchk_i = (uint32_t)(oscchk);
                        if(oscchk_i > 1ULL) {oscchk_i = 1;
                        }
                        data |= ((oscchk_i) & 0x1ULL) << 17;
            
                        uint32_t otp1_med_i = (uint32_t)(otp1_med);
                        if(otp1_med_i > 1ULL) {otp1_med_i = 1;
                        }
                        data |= ((otp1_med_i) & 0x1ULL) << 16;
            
                        uint32_t otp2_med_i = (uint32_t)(otp2_med);
                        if(otp2_med_i > 1ULL) {otp2_med_i = 1;
                        }
                        data |= ((otp2_med_i) & 0x1ULL) << 15;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_alpha_chip_a_debug
(float seg_temp,uint8_t chip_id,float die_temp,float vpv,float vmv,bool va_ov,bool va_uv,bool vd_ov,bool vd_uv,bool vde,bool vdel,bool spiflt,bool sleep,bool thsd,bool tmodchk,bool oscchk)
{
    can_msg_t msg;
    msg.id = 0x6FC;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t seg_temp_i = (uint32_t)(seg_temp*10);
                        if(seg_temp_i > 1023ULL) {seg_temp_i = 1023;
                        }
                        data |= ((seg_temp_i) & 0x3FFULL) << 54;
            
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 50;
            
                        uint32_t die_temp_i = (uint32_t)(die_temp*100);
                        if(die_temp_i > 8191ULL) {die_temp_i = 8191;
                        }
                        data |= ((die_temp_i) & 0x1FFFULL) << 37;
            
                        uint32_t vpv_i = (uint32_t)(vpv*100);
                        if(vpv_i > 8191ULL) {vpv_i = 8191;
                        }
                        data |= ((vpv_i) & 0x1FFFULL) << 24;
            
                        uint32_t vmv_i = (uint32_t)(vmv*1000);
                        if(vmv_i > 8191ULL) {vmv_i = 8191;
                        }
                        data |= ((vmv_i) & 0x1FFFULL) << 11;
            
                        uint32_t va_ov_i = (uint32_t)(va_ov);
                        if(va_ov_i > 1ULL) {va_ov_i = 1;
                        }
                        data |= ((va_ov_i) & 0x1ULL) << 10;
            
                        uint32_t va_uv_i = (uint32_t)(va_uv);
                        if(va_uv_i > 1ULL) {va_uv_i = 1;
                        }
                        data |= ((va_uv_i) & 0x1ULL) << 9;
            
                        uint32_t vd_ov_i = (uint32_t)(vd_ov);
                        if(vd_ov_i > 1ULL) {vd_ov_i = 1;
                        }
                        data |= ((vd_ov_i) & 0x1ULL) << 8;
            
                        uint32_t vd_uv_i = (uint32_t)(vd_uv);
                        if(vd_uv_i > 1ULL) {vd_uv_i = 1;
                        }
                        data |= ((vd_uv_i) & 0x1ULL) << 7;
            
                        uint32_t vde_i = (uint32_t)(vde);
                        if(vde_i > 1ULL) {vde_i = 1;
                        }
                        data |= ((vde_i) & 0x1ULL) << 6;
            
                        uint32_t vdel_i = (uint32_t)(vdel);
                        if(vdel_i > 1ULL) {vdel_i = 1;
                        }
                        data |= ((vdel_i) & 0x1ULL) << 5;
            
                        uint32_t spiflt_i = (uint32_t)(spiflt);
                        if(spiflt_i > 1ULL) {spiflt_i = 1;
                        }
                        data |= ((spiflt_i) & 0x1ULL) << 4;
            
                        uint32_t sleep_i = (uint32_t)(sleep);
                        if(sleep_i > 1ULL) {sleep_i = 1;
                        }
                        data |= ((sleep_i) & 0x1ULL) << 3;
            
                        uint32_t thsd_i = (uint32_t)(thsd);
                        if(thsd_i > 1ULL) {thsd_i = 1;
                        }
                        data |= ((thsd_i) & 0x1ULL) << 2;
            
                        uint32_t tmodchk_i = (uint32_t)(tmodchk);
                        if(tmodchk_i > 1ULL) {tmodchk_i = 1;
                        }
                        data |= ((tmodchk_i) & 0x1ULL) << 1;
            
                        uint32_t oscchk_i = (uint32_t)(oscchk);
                        if(oscchk_i > 1ULL) {oscchk_i = 1;
                        }
                        data |= ((oscchk_i) & 0x1ULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_alpha_chip_b_debug
(float vres,uint8_t chip_id,float vref2,float v_analog,float v_digital,bool otp1_med,bool opt2_med)
{
    can_msg_t msg;
    msg.id = 0x6FF;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t vres_i = (uint32_t)(vres*1000);
                        if(vres_i > 8191ULL) {vres_i = 8191;
                        }
                        data |= ((vres_i) & 0x1FFFULL) << 51;
            
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 47;
            
                        uint32_t vref2_i = (uint32_t)(vref2*1000);
                        if(vref2_i > 8191ULL) {vref2_i = 8191;
                        }
                        data |= ((vref2_i) & 0x1FFFULL) << 34;
            
                        uint32_t v_analog_i = (uint32_t)(v_analog*1000);
                        if(v_analog_i > 8191ULL) {v_analog_i = 8191;
                        }
                        data |= ((v_analog_i) & 0x1FFFULL) << 21;
            
                        uint32_t v_digital_i = (uint32_t)(v_digital*1000);
                        if(v_digital_i > 8191ULL) {v_digital_i = 8191;
                        }
                        data |= ((v_digital_i) & 0x1FFFULL) << 8;
            
                        uint32_t otp1_med_i = (uint32_t)(otp1_med);
                        if(otp1_med_i > 1ULL) {otp1_med_i = 1;
                        }
                        data |= ((otp1_med_i) & 0x1ULL) << 7;
            
                        uint32_t opt2_med_i = (uint32_t)(opt2_med);
                        if(opt2_med_i > 1ULL) {opt2_med_i = 1;
                        }
                        data |= ((opt2_med_i) & 0x1ULL) << 6;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_fan_duty_cycle_percentage
(uint8_t fan_duty_cycle)
{
    can_msg_t msg;
    msg.id = 0x700;
    msg.id_is_extended = false;
    msg.len = 1;

    
            uint8_t data = 0;
                        uint32_t fan_duty_cycle_i = (uint32_t)(fan_duty_cycle);
                        if(fan_duty_cycle_i > 255ULL) {fan_duty_cycle_i = 255;
                        }
                        data |= ((fan_duty_cycle_i) & 0xFFULL) << 0;
            
            msg.data[0] = data;
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_bms_charge_message_send
(float charge_volts,float charge_current,uint8_t enable_charging)
{
    can_msg_t msg;
    msg.id = 0x1806E5F4;
    msg.id_is_extended = true;msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t charge_volts_i = (uint32_t)(charge_volts*10);
                        if(charge_volts_i > 65535ULL) {charge_volts_i = 65535;
                        }
                        data |= ((charge_volts_i) & 0xFFFFULL) << 48;
            
                        uint32_t charge_current_i = (uint32_t)(charge_current*10);
                        if(charge_current_i > 65535ULL) {charge_current_i = 65535;
                        }
                        data |= ((charge_current_i) & 0xFFFFULL) << 32;
            
                        uint32_t enable_charging_i = (uint32_t)(enable_charging);
                        if(enable_charging_i > 255ULL) {enable_charging_i = 255;
                        }
                        data |= ((enable_charging_i) & 0xFFULL) << 24;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}



/// @brief A helper which sends appropriate error to stdout and CAN if a bistream overflows
/// @param bitstream_res The bitstream to check for overflow
/// @param can_id The CAN ID this bistream data is intended for
/// @return 0 if success
static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id)
{
	if (!bitstream_res->overflow) {
		return;
	}

    static uint16_t overflow_cnt = 0;
	overflow_cnt++;
	send_overflow_notification_for_percell(can_id, overflow_cnt);
}