
/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include "can_messages_tx.h"
#include <stdbool.h>

#include "u_tx_debug.h"
#include "u_queues.h"
#include "c_utils.h"
#include "fdcan.h"
#include "bitstream.h"


static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id);

uint8_t send_max_ac_current_command
(float max_current_ac_target)
{
    can_msg_t msg;
    msg.id = 0x116;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        int32_t max_current_ac_target_i = (int32_t)(max_current_ac_target*10);
                        if(max_current_ac_target_i > 32767) {max_current_ac_target_i = 32767;
                        } else if(max_current_ac_target_i < -32768) {max_current_ac_target_i = -32768;
                        }
                        data |= ((uint32_t)(max_current_ac_target_i) & 0xFFFFULL) << 48;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_max_ac_brake_current_command
(float max_ac_brake_current_target)
{
    can_msg_t msg;
    msg.id = 0x136;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        int32_t max_ac_brake_current_target_i = (int32_t)(max_ac_brake_current_target*10);
                        if(max_ac_brake_current_target_i > 32767) {max_ac_brake_current_target_i = 32767;
                        } else if(max_ac_brake_current_target_i < -32768) {max_ac_brake_current_target_i = -32768;
                        }
                        data |= ((uint32_t)(max_ac_brake_current_target_i) & 0xFFFFULL) << 48;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_max_dc_current_command
(float max_dc_current_target)
{
    can_msg_t msg;
    msg.id = 0x156;
    msg.id_is_extended = false;
    msg.len = 2;

    
            uint16_t data = 0;
                        int32_t max_dc_current_target_i = (int32_t)(max_dc_current_target*10);
                        if(max_dc_current_target_i > 32767) {max_dc_current_target_i = 32767;
                        } else if(max_dc_current_target_i < -32768) {max_dc_current_target_i = -32768;
                        }
                        data |= ((uint32_t)(max_dc_current_target_i) & 0xFFFFULL) << 0;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_max_dc_brake_current_command
(float max_dc_brake_current_target)
{
    can_msg_t msg;
    msg.id = 0x176;
    msg.id_is_extended = false;
    msg.len = 2;

    
            uint16_t data = 0;
                        int32_t max_dc_brake_current_target_i = (int32_t)(max_dc_brake_current_target*10);
                        if(max_dc_brake_current_target_i > 32767) {max_dc_brake_current_target_i = 32767;
                        } else if(max_dc_brake_current_target_i < -32768) {max_dc_brake_current_target_i = -32768;
                        }
                        data |= ((uint32_t)(max_dc_brake_current_target_i) & 0xFFFFULL) << 0;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_pack_status
(float voltage,float current,float amp_hours,float soc,float health)
{
    can_msg_t msg;
    msg.id = 0x80;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t voltage_i = (uint32_t)(voltage*10);
                        if(voltage_i > 65535ULL) {voltage_i = 65535;
                        }
                        data |= ((voltage_i) & 0xFFFFULL) << 48;
            
                        int32_t current_i = (int32_t)(current*10);
                        if(current_i > 32767) {current_i = 32767;
                        } else if(current_i < -32768) {current_i = -32768;
                        }
                        data |= ((uint32_t)(current_i) & 0xFFFFULL) << 32;
            
                        uint32_t amp_hours_i = (uint32_t)(amp_hours);
                        if(amp_hours_i > 65535ULL) {amp_hours_i = 65535;
                        }
                        data |= ((amp_hours_i) & 0xFFFFULL) << 16;
            
                        uint32_t soc_i = (uint32_t)(soc);
                        if(soc_i > 255ULL) {soc_i = 255;
                        }
                        data |= ((soc_i) & 0xFFULL) << 8;
            
                        uint32_t health_i = (uint32_t)(health);
                        if(health_i > 255ULL) {health_i = 255;
                        }
                        data |= ((health_i) & 0xFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_bms_status
(uint8_t state,float temp_average,float temp_internal)
{
    can_msg_t msg;
    msg.id = 0x81;
    msg.id_is_extended = false;
    msg.len = 3;

    
            uint32_t data = 0;
                        uint32_t state_i = (uint32_t)(state);
                        if(state_i > 255ULL) {state_i = 255;
                        }
                        data |= ((state_i) & 0xFFULL) << 24;
            
                        uint32_t temp_average_i = (uint32_t)(temp_average);
                        if(temp_average_i > 255ULL) {temp_average_i = 255;
                        }
                        data |= ((temp_average_i) & 0xFFULL) << 16;
            
                        uint32_t temp_internal_i = (uint32_t)(temp_internal);
                        if(temp_internal_i > 255ULL) {temp_internal_i = 255;
                        }
                        data |= ((temp_internal_i) & 0xFFULL) << 8;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_cell_voltage
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val)
{
    can_msg_t msg;
    msg.id = 0x83;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t high_val_i = (uint32_t)(high_val*10000);
                        if(high_val_i > 65535ULL) {high_val_i = 65535;
                        }
                        data |= ((high_val_i) & 0xFFFFULL) << 48;
            
                        uint32_t high_chip_i = (uint32_t)(high_chip);
                        if(high_chip_i > 15ULL) {high_chip_i = 15;
                        }
                        data |= ((high_chip_i) & 0xFULL) << 44;
            
                        uint32_t high_cell_i = (uint32_t)(high_cell);
                        if(high_cell_i > 15ULL) {high_cell_i = 15;
                        }
                        data |= ((high_cell_i) & 0xFULL) << 40;
            
                        uint32_t low_val_i = (uint32_t)(low_val*10000);
                        if(low_val_i > 65535ULL) {low_val_i = 65535;
                        }
                        data |= ((low_val_i) & 0xFFFFULL) << 24;
            
                        uint32_t low_chip_i = (uint32_t)(low_chip);
                        if(low_chip_i > 15ULL) {low_chip_i = 15;
                        }
                        data |= ((low_chip_i) & 0xFULL) << 20;
            
                        uint32_t low_cell_i = (uint32_t)(low_cell);
                        if(low_cell_i > 15ULL) {low_cell_i = 15;
                        }
                        data |= ((low_cell_i) & 0xFULL) << 16;
            
                        uint32_t avg_val_i = (uint32_t)(avg_val*10000);
                        if(avg_val_i > 65535ULL) {avg_val_i = 65535;
                        }
                        data |= ((avg_val_i) & 0xFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_cell_temperatures
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val)
{
    can_msg_t msg;
    msg.id = 0x84;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t high_val_i = (uint32_t)(high_val*100);
                        if(high_val_i > 65535ULL) {high_val_i = 65535;
                        }
                        data |= ((high_val_i) & 0xFFFFULL) << 48;
            
                        uint32_t high_chip_i = (uint32_t)(high_chip);
                        if(high_chip_i > 15ULL) {high_chip_i = 15;
                        }
                        data |= ((high_chip_i) & 0xFULL) << 44;
            
                        uint32_t high_cell_i = (uint32_t)(high_cell);
                        if(high_cell_i > 15ULL) {high_cell_i = 15;
                        }
                        data |= ((high_cell_i) & 0xFULL) << 40;
            
                        uint32_t low_val_i = (uint32_t)(low_val*100);
                        if(low_val_i > 65535ULL) {low_val_i = 65535;
                        }
                        data |= ((low_val_i) & 0xFFFFULL) << 24;
            
                        uint32_t low_chip_i = (uint32_t)(low_chip);
                        if(low_chip_i > 15ULL) {low_chip_i = 15;
                        }
                        data |= ((low_chip_i) & 0xFULL) << 20;
            
                        uint32_t low_cell_i = (uint32_t)(low_cell);
                        if(low_cell_i > 15ULL) {low_cell_i = 15;
                        }
                        data |= ((low_cell_i) & 0xFULL) << 16;
            
                        uint32_t avg_val_i = (uint32_t)(avg_val*100);
                        if(avg_val_i > 65535ULL) {avg_val_i = 65535;
                        }
                        data |= ((avg_val_i) & 0xFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_temperatures
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    can_msg_t msg;
    msg.id = 0x85;
    msg.id_is_extended = false;
    msg.len = 5;

    
            uint64_t data = 0;
                        int32_t seg1_i = (int32_t)(seg1);
                        if(seg1_i > 127) {seg1_i = 127;
                        } else if(seg1_i < -128) {seg1_i = -128;
                        }
                        data |= ((uint32_t)(seg1_i) & 0xFFULL) << 56;
            
                        int32_t seg2_i = (int32_t)(seg2);
                        if(seg2_i > 127) {seg2_i = 127;
                        } else if(seg2_i < -128) {seg2_i = -128;
                        }
                        data |= ((uint32_t)(seg2_i) & 0xFFULL) << 48;
            
                        int32_t seg3_i = (int32_t)(seg3);
                        if(seg3_i > 127) {seg3_i = 127;
                        } else if(seg3_i < -128) {seg3_i = -128;
                        }
                        data |= ((uint32_t)(seg3_i) & 0xFFULL) << 40;
            
                        int32_t seg4_i = (int32_t)(seg4);
                        if(seg4_i > 127) {seg4_i = 127;
                        } else if(seg4_i < -128) {seg4_i = -128;
                        }
                        data |= ((uint32_t)(seg4_i) & 0xFFULL) << 32;
            
                        int32_t seg5_i = (int32_t)(seg5);
                        if(seg5_i > 127) {seg5_i = 127;
                        } else if(seg5_i < -128) {seg5_i = -128;
                        }
                        data |= ((uint32_t)(seg5_i) & 0xFFULL) << 24;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_isospi_communication_status
(uint8_t state,uint8_t break_location,uint8_t verification_attempts,uint8_t recovery_successful)
{
    can_msg_t msg;
    msg.id = 0x86;
    msg.id_is_extended = false;
    msg.len = 4;

    
            uint32_t data = 0;
                        uint32_t state_i = (uint32_t)(state);
                        if(state_i > 255ULL) {state_i = 255;
                        }
                        data |= ((state_i) & 0xFFULL) << 24;
            
                        uint32_t break_location_i = (uint32_t)(break_location);
                        if(break_location_i > 255ULL) {break_location_i = 255;
                        }
                        data |= ((break_location_i) & 0xFFULL) << 16;
            
                        uint32_t verification_attempts_i = (uint32_t)(verification_attempts);
                        if(verification_attempts_i > 255ULL) {verification_attempts_i = 255;
                        }
                        data |= ((verification_attempts_i) & 0xFFULL) << 8;
            
                        uint32_t recovery_successful_i = (uint32_t)(recovery_successful);
                        if(recovery_successful_i > 1ULL) {recovery_successful_i = 1;
                        }
                        data |= ((recovery_successful_i) & 0x1ULL) << 7;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_fault_status
(bool dcl_enforce,bool ccl_enforce,bool low_cell_volt,bool high_cell_volt,bool high_charge_volt,bool pack_hot,bool die_temp_max,bool segment_comms,bool hv_plate_comms)
{
    can_msg_t msg;
    msg.id = 0x89;
    msg.id_is_extended = false;
    msg.len = 2;

    
            uint16_t data = 0;
                        uint32_t dcl_enforce_i = (uint32_t)(dcl_enforce);
                        if(dcl_enforce_i > 1ULL) {dcl_enforce_i = 1;
                        }
                        data |= ((dcl_enforce_i) & 0x1ULL) << 15;
            
                        uint32_t ccl_enforce_i = (uint32_t)(ccl_enforce);
                        if(ccl_enforce_i > 1ULL) {ccl_enforce_i = 1;
                        }
                        data |= ((ccl_enforce_i) & 0x1ULL) << 14;
            
                        uint32_t low_cell_volt_i = (uint32_t)(low_cell_volt);
                        if(low_cell_volt_i > 1ULL) {low_cell_volt_i = 1;
                        }
                        data |= ((low_cell_volt_i) & 0x1ULL) << 13;
            
                        uint32_t high_cell_volt_i = (uint32_t)(high_cell_volt);
                        if(high_cell_volt_i > 1ULL) {high_cell_volt_i = 1;
                        }
                        data |= ((high_cell_volt_i) & 0x1ULL) << 12;
            
                        uint32_t high_charge_volt_i = (uint32_t)(high_charge_volt);
                        if(high_charge_volt_i > 1ULL) {high_charge_volt_i = 1;
                        }
                        data |= ((high_charge_volt_i) & 0x1ULL) << 11;
            
                        uint32_t pack_hot_i = (uint32_t)(pack_hot);
                        if(pack_hot_i > 1ULL) {pack_hot_i = 1;
                        }
                        data |= ((pack_hot_i) & 0x1ULL) << 10;
            
                        uint32_t die_temp_max_i = (uint32_t)(die_temp_max);
                        if(die_temp_max_i > 1ULL) {die_temp_max_i = 1;
                        }
                        data |= ((die_temp_max_i) & 0x1ULL) << 9;
            
                        uint32_t segment_comms_i = (uint32_t)(segment_comms);
                        if(segment_comms_i > 1ULL) {segment_comms_i = 1;
                        }
                        data |= ((segment_comms_i) & 0x1ULL) << 8;
            
                        uint32_t hv_plate_comms_i = (uint32_t)(hv_plate_comms);
                        if(hv_plate_comms_i > 1ULL) {hv_plate_comms_i = 1;
                        }
                        data |= ((hv_plate_comms_i) & 0x1ULL) << 7;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_average_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    can_msg_t msg;
    msg.id = 0x90;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t seg1_i = (uint32_t)(seg1*1000);
                        if(seg1_i > 4095ULL) {seg1_i = 4095;
                        }
                        data |= ((seg1_i) & 0xFFFULL) << 52;
            
                        uint32_t seg2_i = (uint32_t)(seg2*1000);
                        if(seg2_i > 4095ULL) {seg2_i = 4095;
                        }
                        data |= ((seg2_i) & 0xFFFULL) << 40;
            
                        uint32_t seg3_i = (uint32_t)(seg3*1000);
                        if(seg3_i > 4095ULL) {seg3_i = 4095;
                        }
                        data |= ((seg3_i) & 0xFFFULL) << 28;
            
                        uint32_t seg4_i = (uint32_t)(seg4*1000);
                        if(seg4_i > 4095ULL) {seg4_i = 4095;
                        }
                        data |= ((seg4_i) & 0xFFFULL) << 16;
            
                        uint32_t seg5_i = (uint32_t)(seg5*1000);
                        if(seg5_i > 4095ULL) {seg5_i = 4095;
                        }
                        data |= ((seg5_i) & 0xFFFULL) << 4;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_total_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    can_msg_t msg;
    msg.id = 0x91;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t seg1_i = (uint32_t)(seg1*39);
                        if(seg1_i > 4095ULL) {seg1_i = 4095;
                        }
                        data |= ((seg1_i) & 0xFFFULL) << 52;
            
                        uint32_t seg2_i = (uint32_t)(seg2*39);
                        if(seg2_i > 4095ULL) {seg2_i = 4095;
                        }
                        data |= ((seg2_i) & 0xFFFULL) << 40;
            
                        uint32_t seg3_i = (uint32_t)(seg3*39);
                        if(seg3_i > 4095ULL) {seg3_i = 4095;
                        }
                        data |= ((seg3_i) & 0xFFFULL) << 28;
            
                        uint32_t seg4_i = (uint32_t)(seg4*39);
                        if(seg4_i > 4095ULL) {seg4_i = 4095;
                        }
                        data |= ((seg4_i) & 0xFFFULL) << 16;
            
                        uint32_t seg5_i = (uint32_t)(seg5*39);
                        if(seg5_i > 4095ULL) {seg5_i = 4095;
                        }
                        data |= ((seg5_i) & 0xFFFULL) << 4;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_delta_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5)
{
    can_msg_t msg;
    msg.id = 0x92;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t seg1_i = (uint32_t)(seg1*1000);
                        if(seg1_i > 4095ULL) {seg1_i = 4095;
                        }
                        data |= ((seg1_i) & 0xFFFULL) << 52;
            
                        uint32_t seg2_i = (uint32_t)(seg2*1000);
                        if(seg2_i > 4095ULL) {seg2_i = 4095;
                        }
                        data |= ((seg2_i) & 0xFFFULL) << 40;
            
                        uint32_t seg3_i = (uint32_t)(seg3*1000);
                        if(seg3_i > 4095ULL) {seg3_i = 4095;
                        }
                        data |= ((seg3_i) & 0xFFFULL) << 28;
            
                        uint32_t seg4_i = (uint32_t)(seg4*1000);
                        if(seg4_i > 4095ULL) {seg4_i = 4095;
                        }
                        data |= ((seg4_i) & 0xFFFULL) << 16;
            
                        uint32_t seg5_i = (uint32_t)(seg5*1000);
                        if(seg5_i > 4095ULL) {seg5_i = 4095;
                        }
                        data |= ((seg5_i) & 0xFFFULL) << 4;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_bms_debug
(uint8_t spare0,uint8_t spare1,uint16_t spare2,uint32_t spare3)
{
    can_msg_t msg;
    msg.id = 0x702;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t spare0_i = (uint32_t)(spare0);
                        if(spare0_i > 255ULL) {spare0_i = 255;
                        }
                        data |= ((spare0_i) & 0xFFULL) << 56;
            
                        uint32_t spare1_i = (uint32_t)(spare1);
                        if(spare1_i > 255ULL) {spare1_i = 255;
                        }
                        data |= ((spare1_i) & 0xFFULL) << 48;
            
                        uint32_t spare2_i = (uint32_t)(spare2);
                        if(spare2_i > 65535ULL) {spare2_i = 65535;
                        }
                        data |= ((spare2_i) & 0xFFFFULL) << 32;
            
                        uint32_t spare3_i = (uint32_t)(spare3);
                        if(spare3_i > 4294967295ULL) {spare3_i = 4294967295;
                        }
                        data |= ((spare3_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_bms_fault_timers
(uint8_t start_stop,uint8_t code,float value)
{
    can_msg_t msg;
    msg.id = 0x6F9;
    msg.id_is_extended = false;
    msg.len = 6;

    
            uint64_t data = 0;
                        uint32_t start_stop_i = (uint32_t)(start_stop);
                        if(start_stop_i > 255ULL) {start_stop_i = 255;
                        }
                        data |= ((start_stop_i) & 0xFFULL) << 56;
            
                        uint32_t code_i = (uint32_t)(code);
                        if(code_i > 255ULL) {code_i = 255;
                        }
                        data |= ((code_i) & 0xFFULL) << 48;
            
                        uint32_t value_i = (uint32_t)(value);
                        if(value_i > 4294967295ULL) {value_i = 4294967295;
                        }
                        data |= ((value_i) & 0xFFFFFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_shepherd_version_tag
(uint8_t major,uint8_t minor,uint8_t patch,bool dirty,bool local_commit)
{
    can_msg_t msg;
    msg.id = 0x69A;
    msg.id_is_extended = false;
    msg.len = 5;

    
            uint64_t data = 0;
                        uint32_t major_i = (uint32_t)(major);
                        if(major_i > 255ULL) {major_i = 255;
                        }
                        data |= ((major_i) & 0xFFULL) << 56;
            
                        uint32_t minor_i = (uint32_t)(minor);
                        if(minor_i > 255ULL) {minor_i = 255;
                        }
                        data |= ((minor_i) & 0xFFULL) << 48;
            
                        uint32_t patch_i = (uint32_t)(patch);
                        if(patch_i > 255ULL) {patch_i = 255;
                        }
                        data |= ((patch_i) & 0xFFULL) << 40;
            
                        uint32_t dirty_i = (uint32_t)(dirty);
                        if(dirty_i > 255ULL) {dirty_i = 255;
                        }
                        data |= ((dirty_i) & 0xFFULL) << 32;
            
                        uint32_t local_commit_i = (uint32_t)(local_commit);
                        if(local_commit_i > 255ULL) {local_commit_i = 255;
                        }
                        data |= ((local_commit_i) & 0xFFULL) << 24;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_shepherd_version_hash
(uint32_t short_hash,uint32_t author_hash)
{
    can_msg_t msg;
    msg.id = 0x69B;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t short_hash_i = (uint32_t)(short_hash);
                        if(short_hash_i > 4294967295ULL) {short_hash_i = 4294967295;
                        }
                        data |= ((short_hash_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t author_hash_i = (uint32_t)(author_hash);
                        if(author_hash_i > 4294967295ULL) {author_hash_i = 4294967295;
                        }
                        data |= ((author_hash_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_overflow_notification_for_percell
(uint32_t overflow_can_id,uint16_t overflow_cnt)
{
    can_msg_t msg;
    msg.id = 0x6F1;
    msg.id_is_extended = false;
    msg.len = 6;

    
            uint64_t data = 0;
                        uint32_t overflow_can_id_i = (uint32_t)(overflow_can_id);
                        if(overflow_can_id_i > 4294967295ULL) {overflow_can_id_i = 4294967295;
                        }
                        data |= ((overflow_can_id_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t overflow_cnt_i = (uint32_t)(overflow_cnt);
                        if(overflow_cnt_i > 65535ULL) {overflow_cnt_i = 65535;
                        }
                        data |= ((overflow_cnt_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_alpha_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b)
{
    can_msg_t msg;
    msg.id = 0x6FA;
    msg.id_is_extended = false;
    msg.len = 7;

    
            uint64_t data = 0;
                        uint32_t therm_i = (uint32_t)(therm*10);
                        if(therm_i > 1023ULL) {therm_i = 1023;
                        }
                        data |= ((therm_i) & 0x3FFULL) << 54;
            
                        uint32_t voltage_a_i = (uint32_t)(voltage_a*1000);
                        if(voltage_a_i > 8191ULL) {voltage_a_i = 8191;
                        }
                        data |= ((voltage_a_i) & 0x1FFFULL) << 41;
            
                        uint32_t voltage_b_i = (uint32_t)(voltage_b*1000);
                        if(voltage_b_i > 8191ULL) {voltage_b_i = 8191;
                        }
                        data |= ((voltage_b_i) & 0x1FFFULL) << 28;
            
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 24;
            
                        uint32_t cell_a_i = (uint32_t)(cell_a);
                        if(cell_a_i > 15ULL) {cell_a_i = 15;
                        }
                        data |= ((cell_a_i) & 0xFULL) << 20;
            
                        uint32_t cell_b_i = (uint32_t)(cell_b);
                        if(cell_b_i > 15ULL) {cell_b_i = 15;
                        }
                        data |= ((cell_b_i) & 0xFULL) << 16;
            
                        uint32_t discharging_a_i = (uint32_t)(discharging_a);
                        if(discharging_a_i > 1ULL) {discharging_a_i = 1;
                        }
                        data |= ((discharging_a_i) & 0x1ULL) << 15;
            
                        uint32_t discharging_b_i = (uint32_t)(discharging_b);
                        if(discharging_b_i > 1ULL) {discharging_b_i = 1;
                        }
                        data |= ((discharging_b_i) & 0x1ULL) << 14;
            
                        uint32_t cvs_a_i = (uint32_t)(cvs_a);
                        if(cvs_a_i > 1ULL) {cvs_a_i = 1;
                        }
                        data |= ((cvs_a_i) & 0x1ULL) << 13;
            
                        uint32_t cvs_b_i = (uint32_t)(cvs_b);
                        if(cvs_b_i > 1ULL) {cvs_b_i = 1;
                        }
                        data |= ((cvs_b_i) & 0x1ULL) << 12;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_beta_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b)
{
    can_msg_t msg;
    msg.id = 0x6FB;
    msg.id_is_extended = false;
    msg.len = 7;

    
            uint64_t data = 0;
                        uint32_t therm_i = (uint32_t)(therm*10);
                        if(therm_i > 1023ULL) {therm_i = 1023;
                        }
                        data |= ((therm_i) & 0x3FFULL) << 54;
            
                        uint32_t voltage_a_i = (uint32_t)(voltage_a*1000);
                        if(voltage_a_i > 8191ULL) {voltage_a_i = 8191;
                        }
                        data |= ((voltage_a_i) & 0x1FFFULL) << 41;
            
                        uint32_t voltage_b_i = (uint32_t)(voltage_b*1000);
                        if(voltage_b_i > 8191ULL) {voltage_b_i = 8191;
                        }
                        data |= ((voltage_b_i) & 0x1FFFULL) << 28;
            
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 24;
            
                        uint32_t cell_a_i = (uint32_t)(cell_a);
                        if(cell_a_i > 15ULL) {cell_a_i = 15;
                        }
                        data |= ((cell_a_i) & 0xFULL) << 20;
            
                        uint32_t cell_b_i = (uint32_t)(cell_b);
                        if(cell_b_i > 15ULL) {cell_b_i = 15;
                        }
                        data |= ((cell_b_i) & 0xFULL) << 16;
            
                        uint32_t discharging_a_i = (uint32_t)(discharging_a);
                        if(discharging_a_i > 1ULL) {discharging_a_i = 1;
                        }
                        data |= ((discharging_a_i) & 0x1ULL) << 15;
            
                        uint32_t discharging_b_i = (uint32_t)(discharging_b);
                        if(discharging_b_i > 1ULL) {discharging_b_i = 1;
                        }
                        data |= ((discharging_b_i) & 0x1ULL) << 14;
            
                        uint32_t cvs_a_i = (uint32_t)(cvs_a);
                        if(cvs_a_i > 1ULL) {cvs_a_i = 1;
                        }
                        data |= ((cvs_a_i) & 0x1ULL) << 13;
            
                        uint32_t cvs_b_i = (uint32_t)(cvs_b);
                        if(cvs_b_i > 1ULL) {cvs_b_i = 1;
                        }
                        data |= ((cvs_b_i) & 0x1ULL) << 12;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_chip_a_debug
(uint8_t chip_id,float die_temp,float vpv,float vmv,bool va_ov,bool va_uv,bool vd_ov,bool vd_uv,bool vde,bool vdel,bool spiflt,bool sleep,bool thsd,bool tmodchk,bool oscchk)
{
    can_msg_t msg;
    msg.id = 0x6FC;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 60;
            
                        uint32_t die_temp_i = (uint32_t)(die_temp*100);
                        if(die_temp_i > 8191ULL) {die_temp_i = 8191;
                        }
                        data |= ((die_temp_i) & 0x1FFFULL) << 47;
            
                        uint32_t vpv_i = (uint32_t)(vpv*100);
                        if(vpv_i > 8191ULL) {vpv_i = 8191;
                        }
                        data |= ((vpv_i) & 0x1FFFULL) << 34;
            
                        uint32_t vmv_i = (uint32_t)(vmv*1000);
                        if(vmv_i > 8191ULL) {vmv_i = 8191;
                        }
                        data |= ((vmv_i) & 0x1FFFULL) << 21;
            
                        uint32_t va_ov_i = (uint32_t)(va_ov);
                        if(va_ov_i > 1ULL) {va_ov_i = 1;
                        }
                        data |= ((va_ov_i) & 0x1ULL) << 20;
            
                        uint32_t va_uv_i = (uint32_t)(va_uv);
                        if(va_uv_i > 1ULL) {va_uv_i = 1;
                        }
                        data |= ((va_uv_i) & 0x1ULL) << 19;
            
                        uint32_t vd_ov_i = (uint32_t)(vd_ov);
                        if(vd_ov_i > 1ULL) {vd_ov_i = 1;
                        }
                        data |= ((vd_ov_i) & 0x1ULL) << 18;
            
                        uint32_t vd_uv_i = (uint32_t)(vd_uv);
                        if(vd_uv_i > 1ULL) {vd_uv_i = 1;
                        }
                        data |= ((vd_uv_i) & 0x1ULL) << 17;
            
                        uint32_t vde_i = (uint32_t)(vde);
                        if(vde_i > 1ULL) {vde_i = 1;
                        }
                        data |= ((vde_i) & 0x1ULL) << 16;
            
                        uint32_t vdel_i = (uint32_t)(vdel);
                        if(vdel_i > 1ULL) {vdel_i = 1;
                        }
                        data |= ((vdel_i) & 0x1ULL) << 15;
            
                        uint32_t spiflt_i = (uint32_t)(spiflt);
                        if(spiflt_i > 1ULL) {spiflt_i = 1;
                        }
                        data |= ((spiflt_i) & 0x1ULL) << 14;
            
                        uint32_t sleep_i = (uint32_t)(sleep);
                        if(sleep_i > 1ULL) {sleep_i = 1;
                        }
                        data |= ((sleep_i) & 0x1ULL) << 13;
            
                        uint32_t thsd_i = (uint32_t)(thsd);
                        if(thsd_i > 1ULL) {thsd_i = 1;
                        }
                        data |= ((thsd_i) & 0x1ULL) << 12;
            
                        uint32_t tmodchk_i = (uint32_t)(tmodchk);
                        if(tmodchk_i > 1ULL) {tmodchk_i = 1;
                        }
                        data |= ((tmodchk_i) & 0x1ULL) << 11;
            
                        uint32_t oscchk_i = (uint32_t)(oscchk);
                        if(oscchk_i > 1ULL) {oscchk_i = 1;
                        }
                        data |= ((oscchk_i) & 0x1ULL) << 10;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_chip_b_debug
(float vres,uint8_t chip_id,float vref2,float v_analog,float v_digital,bool otp1_med,bool opt2_med)
{
    can_msg_t msg;
    msg.id = 0x6FF;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t vres_i = (uint32_t)(vres*1000);
                        if(vres_i > 8191ULL) {vres_i = 8191;
                        }
                        data |= ((vres_i) & 0x1FFFULL) << 51;
            
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 15ULL) {chip_id_i = 15;
                        }
                        data |= ((chip_id_i) & 0xFULL) << 47;
            
                        uint32_t vref2_i = (uint32_t)(vref2*1000);
                        if(vref2_i > 8191ULL) {vref2_i = 8191;
                        }
                        data |= ((vref2_i) & 0x1FFFULL) << 34;
            
                        uint32_t v_analog_i = (uint32_t)(v_analog*1000);
                        if(v_analog_i > 8191ULL) {v_analog_i = 8191;
                        }
                        data |= ((v_analog_i) & 0x1FFFULL) << 21;
            
                        uint32_t v_digital_i = (uint32_t)(v_digital*1000);
                        if(v_digital_i > 8191ULL) {v_digital_i = 8191;
                        }
                        data |= ((v_digital_i) & 0x1FFFULL) << 8;
            
                        uint32_t otp1_med_i = (uint32_t)(otp1_med);
                        if(otp1_med_i > 1ULL) {otp1_med_i = 1;
                        }
                        data |= ((otp1_med_i) & 0x1ULL) << 7;
            
                        uint32_t opt2_med_i = (uint32_t)(opt2_med);
                        if(opt2_med_i > 1ULL) {opt2_med_i = 1;
                        }
                        data |= ((opt2_med_i) & 0x1ULL) << 6;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_fan_duty_cycle_percentage
(uint8_t fan_duty_cycle)
{
    can_msg_t msg;
    msg.id = 0x700;
    msg.id_is_extended = false;
    msg.len = 1;

    
            uint8_t data = 0;
                        uint32_t fan_duty_cycle_i = (uint32_t)(fan_duty_cycle);
                        if(fan_duty_cycle_i > 255ULL) {fan_duty_cycle_i = 255;
                        }
                        data |= ((fan_duty_cycle_i) & 0xFFULL) << 0;
            
            msg.data[0] = data;
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_onboard_therm_temperatures
(uint8_t chip_id,float therm_temp_1,float therm_temp_2,float therm_temp_3)
{
    can_msg_t msg;
    msg.id = 0x93;
    msg.id_is_extended = false;
    msg.len = 1;

    
            uint8_t data = 0;
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 1ULL) {chip_id_i = 1;
                        }
                        data |= ((chip_id_i) & 0x1ULL) << 7;
            
                        uint32_t therm_temp_1_i = (uint32_t)(therm_temp_1);
                        if(therm_temp_1_i > 3ULL) {therm_temp_1_i = 3;
                        }
                        data |= ((therm_temp_1_i) & 0x3ULL) << 5;
            
                        uint32_t therm_temp_2_i = (uint32_t)(therm_temp_2);
                        if(therm_temp_2_i > 3ULL) {therm_temp_2_i = 3;
                        }
                        data |= ((therm_temp_2_i) & 0x3ULL) << 3;
            
                        uint32_t therm_temp_3_i = (uint32_t)(therm_temp_3);
                        if(therm_temp_3_i > 3ULL) {therm_temp_3_i = 3;
                        }
                        data |= ((therm_temp_3_i) & 0x3ULL) << 1;
            
            msg.data[0] = data;
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_precharge_status
(bool precharge_status)
{
    can_msg_t msg;
    msg.id = 0x601;
    msg.id_is_extended = false;
    msg.len = 1;

    
            uint8_t data = 0;
                        uint32_t precharge_status_i = (uint32_t)(precharge_status);
                        if(precharge_status_i > 1ULL) {precharge_status_i = 1;
                        }
                        data |= ((precharge_status_i) & 0x1ULL) << 7;
            
            msg.data[0] = data;
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_hv_plate_data
(float batt_voltage,float ts_voltage,float shunt_temp,float pack_current)
{
    can_msg_t msg;
    msg.id = 0x701;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        int32_t batt_voltage_i = (int32_t)(batt_voltage*100);
                        if(batt_voltage_i > 32767) {batt_voltage_i = 32767;
                        } else if(batt_voltage_i < -32768) {batt_voltage_i = -32768;
                        }
                        data |= ((uint32_t)(batt_voltage_i) & 0xFFFFULL) << 48;
            
                        int32_t ts_voltage_i = (int32_t)(ts_voltage*100);
                        if(ts_voltage_i > 32767) {ts_voltage_i = 32767;
                        } else if(ts_voltage_i < -32768) {ts_voltage_i = -32768;
                        }
                        data |= ((uint32_t)(ts_voltage_i) & 0xFFFFULL) << 32;
            
                        int32_t shunt_temp_i = (int32_t)(shunt_temp*100);
                        if(shunt_temp_i > 32767) {shunt_temp_i = 32767;
                        } else if(shunt_temp_i < -32768) {shunt_temp_i = -32768;
                        }
                        data |= ((uint32_t)(shunt_temp_i) & 0xFFFFULL) << 16;
            
                        int32_t pack_current_i = (int32_t)(pack_current*100);
                        if(pack_current_i > 32767) {pack_current_i = 32767;
                        } else if(pack_current_i < -32768) {pack_current_i = -32768;
                        }
                        data |= ((uint32_t)(pack_current_i) & 0xFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_segment_pec_errors
(uint8_t chip_id,uint16_t pec_errors)
{
    can_msg_t msg;
    msg.id = 0x6F2;
    msg.id_is_extended = false;
    msg.len = 3;

    
            uint32_t data = 0;
                        uint32_t chip_id_i = (uint32_t)(chip_id);
                        if(chip_id_i > 255ULL) {chip_id_i = 255;
                        }
                        data |= ((chip_id_i) & 0xFFULL) << 24;
            
                        uint32_t pec_errors_i = (uint32_t)(pec_errors);
                        if(pec_errors_i > 65535ULL) {pec_errors_i = 65535;
                        }
                        data |= ((pec_errors_i) & 0xFFFFULL) << 8;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_hv_plate_pec_errors
(uint16_t pec_errors)
{
    can_msg_t msg;
    msg.id = 0x6F3;
    msg.id_is_extended = false;
    msg.len = 2;

    
            uint16_t data = 0;
                        uint32_t pec_errors_i = (uint32_t)(pec_errors);
                        if(pec_errors_i > 65535ULL) {pec_errors_i = 65535;
                        }
                        data |= ((pec_errors_i) & 0xFFFFULL) << 0;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_hv_plate_diagnostics
(uint16_t flags,float vreg,float tmp1,float vref1p25,uint16_t osccnt)
{
    can_msg_t msg;
    msg.id = 0x100;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t flags_i = (uint32_t)(flags);
                        if(flags_i > 4095ULL) {flags_i = 4095;
                        }
                        data |= ((flags_i) & 0xFFFULL) << 52;
            
                        uint32_t vreg_i = (uint32_t)(vreg*100);
                        if(vreg_i > 4095ULL) {vreg_i = 4095;
                        }
                        data |= ((vreg_i) & 0xFFFULL) << 40;
            
                        uint32_t tmp1_i = (uint32_t)(tmp1*100);
                        if(tmp1_i > 4095ULL) {tmp1_i = 4095;
                        }
                        data |= ((tmp1_i) & 0xFFFULL) << 28;
            
                        uint32_t vref1p25_i = (uint32_t)(vref1p25*100);
                        if(vref1p25_i > 4095ULL) {vref1p25_i = 4095;
                        }
                        data |= ((vref1p25_i) & 0xFFFULL) << 16;
            
                        uint32_t osccnt_i = (uint32_t)(osccnt);
                        if(osccnt_i > 65535ULL) {osccnt_i = 65535;
                        }
                        data |= ((osccnt_i) & 0xFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_hv_plate_diagnostics_second
(float epad,float vdig,float vdd,float tmp2,float vdiv)
{
    can_msg_t msg;
    msg.id = 0x101;
    msg.id_is_extended = false;
    msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t epad_i = (uint32_t)(epad*100);
                        if(epad_i > 4095ULL) {epad_i = 4095;
                        }
                        data |= ((epad_i) & 0xFFFULL) << 52;
            
                        uint32_t vdig_i = (uint32_t)(vdig*100);
                        if(vdig_i > 4095ULL) {vdig_i = 4095;
                        }
                        data |= ((vdig_i) & 0xFFFULL) << 40;
            
                        uint32_t vdd_i = (uint32_t)(vdd*100);
                        if(vdd_i > 4095ULL) {vdd_i = 4095;
                        }
                        data |= ((vdd_i) & 0xFFFULL) << 28;
            
                        uint32_t tmp2_i = (uint32_t)(tmp2*100);
                        if(tmp2_i > 4095ULL) {tmp2_i = 4095;
                        }
                        data |= ((tmp2_i) & 0xFFFULL) << 16;
            
                        uint32_t vdiv_i = (uint32_t)(vdiv*100);
                        if(vdiv_i > 4095ULL) {vdiv_i = 4095;
                        }
                        data |= ((vdiv_i) & 0xFFFULL) << 4;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_bms_charge_message_send
(float charge_volts,float charge_current,uint8_t enable_charging)
{
    can_msg_t msg;
    msg.id = 0x1806E5F4;
    msg.id_is_extended = true;msg.len = 8;

    
            uint64_t data = 0;
                        uint32_t charge_volts_i = (uint32_t)(charge_volts*10);
                        if(charge_volts_i > 65535ULL) {charge_volts_i = 65535;
                        }
                        data |= ((charge_volts_i) & 0xFFFFULL) << 48;
            
                        uint32_t charge_current_i = (uint32_t)(charge_current*10);
                        if(charge_current_i > 65535ULL) {charge_current_i = 65535;
                        }
                        data |= ((charge_current_i) & 0xFFFFULL) << 32;
            
                        uint32_t enable_charging_i = (uint32_t)(enable_charging);
                        if(enable_charging_i > 255ULL) {enable_charging_i = 255;
                        }
                        data |= ((enable_charging_i) & 0xFFULL) << 24;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);
        

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}



/// @brief A helper which sends appropriate error to stdout and CAN if a bistream overflows
/// @param bitstream_res The bitstream to check for overflow
/// @param can_id The CAN ID this bistream data is intended for
/// @return 0 if success
static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id)
{
	if (!bitstream_res->overflow) {
		return;
	}

    static uint16_t overflow_cnt = 0;
	overflow_cnt++;
	send_overflow_notification_for_percell(can_id, overflow_cnt);
}