#ifndef _CAN_MSGS_RX_H
#define _CAN_MSGS_RX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/

#include <stdbool.h>

#include "u_tx_debug.h"
#include "u_queues.h"
#include "c_utils.h"
#include "fdcan.h"
#include "bitstream.h"

typedef struct {
 float current_target_ac;
} ac_current_command_t;

void receive_ac_current_command(const can_msg_t *message, ac_current_command_t *ac_current_command);

typedef struct {
 float brake_ac_current;
} brake_current_command_t;

void receive_brake_current_command(const can_msg_t *message, brake_current_command_t *brake_current_command);

typedef struct {
 uint8_t drive_enable;
} drive_enable_command_t;

void receive_drive_enable_command(const can_msg_t *message, drive_enable_command_t *drive_enable_command);

typedef struct {
 uint8_t state;
} dashboard_efuse_state_t;

void receive_dashboard_efuse_state(const can_msg_t *message, dashboard_efuse_state_t *dashboard_efuse_state);

typedef struct {
 uint8_t state;
} brake_efuse_state_t;

void receive_brake_efuse_state(const can_msg_t *message, brake_efuse_state_t *brake_efuse_state);

typedef struct {
 uint8_t state;
} shutdown_efuse_state_t;

void receive_shutdown_efuse_state(const can_msg_t *message, shutdown_efuse_state_t *shutdown_efuse_state);

typedef struct {
 uint8_t state;
} lv_efuse_state_t;

void receive_lv_efuse_state(const can_msg_t *message, lv_efuse_state_t *lv_efuse_state);

typedef struct {
 uint8_t state;
} radfan_efuse_state_t;

void receive_radfan_efuse_state(const can_msg_t *message, radfan_efuse_state_t *radfan_efuse_state);

typedef struct {
 uint8_t state;
} fanbatt_efuse_state_t;

void receive_fanbatt_efuse_state(const can_msg_t *message, fanbatt_efuse_state_t *fanbatt_efuse_state);

typedef struct {
 uint8_t state;
} pumpone_efuse_state_t;

void receive_pumpone_efuse_state(const can_msg_t *message, pumpone_efuse_state_t *pumpone_efuse_state);

typedef struct {
 uint8_t state;
} pumptwo_efuse_state_t;

void receive_pumptwo_efuse_state(const can_msg_t *message, pumptwo_efuse_state_t *pumptwo_efuse_state);

typedef struct {
 uint8_t state;
} battbox_efuse_state_t;

void receive_battbox_efuse_state(const can_msg_t *message, battbox_efuse_state_t *battbox_efuse_state);

typedef struct {
 uint8_t state;
} mc_efuse_state_t;

void receive_mc_efuse_state(const can_msg_t *message, mc_efuse_state_t *mc_efuse_state);

typedef struct {
 uint8_t state;
} spare_efuse_state_t;

void receive_spare_efuse_state(const can_msg_t *message, spare_efuse_state_t *spare_efuse_state);

typedef struct {
 uint8_t command;
} rtds_command_message_t;

void receive_rtds_command_message(const can_msg_t *message, rtds_command_message_t *rtds_command_message);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} dashboard_efuse_t;

void receive_dashboard_efuse(const can_msg_t *message, dashboard_efuse_t *dashboard_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} brake_efuse_t;

void receive_brake_efuse(const can_msg_t *message, brake_efuse_t *brake_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} shutdown_efuse_t;

void receive_shutdown_efuse(const can_msg_t *message, shutdown_efuse_t *shutdown_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} lv_efuse_t;

void receive_lv_efuse(const can_msg_t *message, lv_efuse_t *lv_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} radfan_efuse_t;

void receive_radfan_efuse(const can_msg_t *message, radfan_efuse_t *radfan_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} fanbatt_efuse_t;

void receive_fanbatt_efuse(const can_msg_t *message, fanbatt_efuse_t *fanbatt_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} pumpone_efuse_t;

void receive_pumpone_efuse(const can_msg_t *message, pumpone_efuse_t *pumpone_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} pumptwo_efuse_t;

void receive_pumptwo_efuse(const can_msg_t *message, pumptwo_efuse_t *pumptwo_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} battbox_efuse_t;

void receive_battbox_efuse(const can_msg_t *message, battbox_efuse_t *battbox_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} mc_efuse_t;

void receive_mc_efuse(const can_msg_t *message, mc_efuse_t *mc_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} spare_efuse_t;

void receive_spare_efuse(const can_msg_t *message, spare_efuse_t *spare_efuse);

typedef struct {
 bool bms_gpio;
 bool bots_gpio;
 bool spare_gpio;
 bool bspd_gpio;
 bool hv_c;
 bool hvd_gpio;
 bool imd_gpio;
 bool ckpt_gpio;
 bool inertia_sw_gpio;
 bool tsms_gpio;
 uint8_t UNUSED;
} shutdown_pins_t;

void receive_shutdown_pins(const can_msg_t *message, shutdown_pins_t *shutdown_pins);

typedef struct {
 bool home_mode;
 uint8_t nero_index;
 int32_t car_speed;
 bool tsms;
 uint32_t torque_limit_percentage;
 bool reverse;
 uint16_t regen_limit;
 bool launch_control;
 uint8_t functional_state;
 bool traction_control;
} car_state_t;

void receive_car_state(const can_msg_t *message, car_state_t *car_state);

typedef struct {
 float accel_norm;
 float brake_norm;
} pedal_percent_pressed_values_t;

void receive_pedal_percent_pressed_values(const can_msg_t *message, pedal_percent_pressed_values_t *pedal_percent_pressed_values);

typedef struct {
 float accel1_volts;
 float accel2_volts;
 float brake1_volts;
 float brake2_volts;
} pedal_sensor_voltages_t;

void receive_pedal_sensor_voltages(const can_msg_t *message, pedal_sensor_voltages_t *pedal_sensor_voltages);

typedef struct {
 uint8_t status;
} lightning_board_light_status_t;

void receive_lightning_board_light_status(const can_msg_t *message, lightning_board_light_status_t *lightning_board_light_status);

typedef struct {
 float vcu_temperature;
 float vcu_humidity;
} temperature_sensor_t;

void receive_temperature_sensor(const can_msg_t *message, temperature_sensor_t *temperature_sensor);

typedef struct {
 float imu_accelerometer_x;
 float imu_accelerometer_y;
 float imu_accelerometer_z;
} imu_accelerometer_t;

void receive_imu_accelerometer(const can_msg_t *message, imu_accelerometer_t *imu_accelerometer);

typedef struct {
 float imu_gyro_x;
 float imu_gyro_y;
 float imu_gyro_z;
} imu_gyro_t;

void receive_imu_gyro(const can_msg_t *message, imu_gyro_t *imu_gyro);

typedef struct {
 bool CAN_OUTGOING_FAULT;
 bool CAN_INCOMING_FAULT;
 bool BMS_CAN_MONITOR_FAULT;
 bool LIGHTNING_CAN_MONITOR_FAULT;
 bool SHUTDOWN_FAULT;
 bool ONBOARD_TEMP_FAULT;
 bool IMU_ACCEL_FAULT;
 bool IMU_GYRO_FAULT;
 bool BSPD_PREFAULT;
 bool ONBOARD_BRAKE_OPEN_CIRCUIT_FAULT;
 bool ONBOARD_ACCEL_OPEN_CIRCUIT_FAULT;
 bool ONBOARD_BRAKE_SHORT_CIRCUIT_FAULT;
 bool ONBOARD_ACCEL_SHORT_CIRCUIT_FAULT;
 bool ONBOARD_PEDAL_DIFFERENCE_FAULT;
 bool RTDS_FAULT;
 bool LV_LOW_VOLTAGE_FAULT;
} faults_t;

void receive_faults(const can_msg_t *message, faults_t *faults);

typedef struct {
 uint16_t ADC;
 float Voltage;
} lv_voltage_t;

void receive_lv_voltage(const can_msg_t *message, lv_voltage_t *lv_voltage);

typedef struct {
 uint8_t three_bits;
 float float_value;
 uint8_t five_bits;
 uint16_t sixteen_bits;
 int8_t signed_8_bits;
} vcu_test_message_t;

void receive_vcu_test_message(const can_msg_t *message, vcu_test_message_t *vcu_test_message);

typedef struct {
 uint16_t temp;
} dti_motor_temp_as_reported_by_vcu_t;

void receive_dti_motor_temp_as_reported_by_vcu(const can_msg_t *message, dti_motor_temp_as_reported_by_vcu_t *dti_motor_temp_as_reported_by_vcu);

typedef struct {
 uint16_t temp;
} dti_controller_temp_as_reported_by_vcu_t;

void receive_dti_controller_temp_as_reported_by_vcu(const can_msg_t *message, dti_controller_temp_as_reported_by_vcu_t *dti_controller_temp_as_reported_by_vcu);

typedef struct {
 float temp;
} bms_battbox_temp_as_reported_by_vcu_t;

void receive_bms_battbox_temp_as_reported_by_vcu(const can_msg_t *message, bms_battbox_temp_as_reported_by_vcu_t *bms_battbox_temp_as_reported_by_vcu);

typedef struct {
 bool brake_state;
} brake_state_as_reported_by_vcu_t;

void receive_brake_state_as_reported_by_vcu(const can_msg_t *message, brake_state_as_reported_by_vcu_t *brake_state_as_reported_by_vcu);

typedef struct {
 bool pin_state;
 bool sounding_state;
 bool reverse_state;
 bool error;
} rtds_state_message_t;

void receive_rtds_state_message(const can_msg_t *message, rtds_state_message_t *rtds_state_message);

typedef struct {
 uint16_t raw;
 float voltage;
 float current;
} lfiu_low_current_adc_readings_t;

void receive_lfiu_low_current_adc_readings(const can_msg_t *message, lfiu_low_current_adc_readings_t *lfiu_low_current_adc_readings);

typedef struct {
 uint16_t raw;
 float voltage;
 float current;
} lfiu_high_current_adc_readings_t;

void receive_lfiu_high_current_adc_readings(const can_msg_t *message, lfiu_high_current_adc_readings_t *lfiu_high_current_adc_readings);

typedef struct {
 uint16_t one;
 uint8_t two;
 uint8_t three;
 bool four;
 uint8_t five;
 uint32_t six;
} second_vcu_test_message_t;

void receive_second_vcu_test_message(const can_msg_t *message, second_vcu_test_message_t *second_vcu_test_message);

typedef struct {
 uint8_t fan_pwm_percentage;
} lv_box_fan_pwm_t;

void receive_lv_box_fan_pwm(const can_msg_t *message, lv_box_fan_pwm_t *lv_box_fan_pwm);

typedef struct {
 uint8_t button_id;
} wheel_buttons_t;

void receive_wheel_buttons(const can_msg_t *message, wheel_buttons_t *wheel_buttons);

typedef struct {
 float accel_x;
 float accel_y;
 float accel_z;
} lightning_board_imu_acceleration_data_t;

void receive_lightning_board_imu_acceleration_data(const can_msg_t *message, lightning_board_imu_acceleration_data_t *lightning_board_imu_acceleration_data);

typedef struct {
 float gyro_x;
 float gyro_y;
 float gyro_z;
} lightning_board_imu_gyro_data_t;

void receive_lightning_board_imu_gyro_data(const can_msg_t *message, lightning_board_imu_gyro_data_t *lightning_board_imu_gyro_data);

typedef struct {
 uint8_t interrupt;
 uint8_t distance;
 uint32_t energy;
} lightning_board_lightning_sensor_information_t;

void receive_lightning_board_lightning_sensor_information(const can_msg_t *message, lightning_board_lightning_sensor_information_t *lightning_board_lightning_sensor_information);

typedef struct {
 float mag_x;
 float mag_y;
 float mag_z;
} lightning_board_magnometer_sensor_information_t;

void receive_lightning_board_magnometer_sensor_information(const can_msg_t *message, lightning_board_magnometer_sensor_information_t *lightning_board_magnometer_sensor_information);

typedef struct {
 float temp;
 float humidity;
} front_msb_env_t;

void receive_front_msb_env(const can_msg_t *message, front_msb_env_t *front_msb_env);

typedef struct {
 float x_force;
 float y_force;
 float z_force;
} front_msb_accel_t;

void receive_front_msb_accel(const can_msg_t *message, front_msb_accel_t *front_msb_accel);

typedef struct {
 float x_deg;
 float y_deg;
 float z_deg;
} front_msb_gyro_t;

void receive_front_msb_gyro(const can_msg_t *message, front_msb_gyro_t *front_msb_gyro);

typedef struct {
 uint32_t strain1;
 uint32_t strain2;
} front_msb_strain_t;

void receive_front_msb_strain(const can_msg_t *message, front_msb_strain_t *front_msb_strain);

typedef struct {
 float shock1;
 uint16_t shock1_raw;
} front_shockpot_t;

void receive_front_shockpot(const can_msg_t *message, front_shockpot_t *front_shockpot);

typedef struct {
 float rh;
} front_ride_height_t;

void receive_front_ride_height(const can_msg_t *message, front_ride_height_t *front_ride_height);

typedef struct {
 float wheel_temp;
} front_wheel_temp_t;

void receive_front_wheel_temp(const can_msg_t *message, front_wheel_temp_t *front_wheel_temp);

typedef struct {
 float x_fdeg;
 float y_fdeg;
 float z_fdeg;
} front_msb_orientation_t;

void receive_front_msb_orientation(const can_msg_t *message, front_msb_orientation_t *front_msb_orientation);

typedef struct {
 float temp;
 float humidity;
} back_msb_env_t;

void receive_back_msb_env(const can_msg_t *message, back_msb_env_t *back_msb_env);

typedef struct {
 float x_force;
 float y_force;
 float z_force;
} back_msb_accel_t;

void receive_back_msb_accel(const can_msg_t *message, back_msb_accel_t *back_msb_accel);

typedef struct {
 float x_deg;
 float y_deg;
 float z_deg;
} back_msb_gyro_t;

void receive_back_msb_gyro(const can_msg_t *message, back_msb_gyro_t *back_msb_gyro);

typedef struct {
 uint32_t strain1;
 uint32_t strain2;
} back_msb_strain_t;

void receive_back_msb_strain(const can_msg_t *message, back_msb_strain_t *back_msb_strain);

typedef struct {
 float shock1;
 uint16_t shock1_raw;
} back_shockpot_t;

void receive_back_shockpot(const can_msg_t *message, back_shockpot_t *back_shockpot);

typedef struct {
 float rh;
} back_ride_height_t;

void receive_back_ride_height(const can_msg_t *message, back_ride_height_t *back_ride_height);

typedef struct {
 float wheel_temp;
} back_wheel_temp_t;

void receive_back_wheel_temp(const can_msg_t *message, back_wheel_temp_t *back_wheel_temp);

typedef struct {
 float x_fdeg;
 float y_fdeg;
 float z_fdeg;
} back_msb_orientation_t;

void receive_back_msb_orientation(const can_msg_t *message, back_msb_orientation_t *back_msb_orientation);


void receive_can(const can_msg_t *msg);

#endif