#ifndef _CAN_MSGS_TX_H
#define _CAN_MSGS_TX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include <stdbool.h>
#include <stdint.h>

/**
* Contents of this message:
* BMS/Commands/Max_AC_Current_Target - This value determines the maximum allowable drive current on the AC side
*/
uint8_t send_max_ac_current_command
(float max_current_ac_target);

/**
* Contents of this message:
* BMS/Commands/Max_AC_Brake_Current_Target - This value sets the maximum allowable brake current on the AC side
*/
uint8_t send_max_ac_brake_current_command
(float max_ac_brake_current_target);

/**
* Contents of this message:
* BMS/Commands/Max_DC_Current_Target - This value determines the maximum allowable drive current on the DC side
*/
uint8_t send_max_dc_current_command
(float max_dc_current_target);

/**
* Contents of this message:
* BMS/Commands/Max_DC_Brake_Current_Target - This value determines the maximum allowable brake current on the DC side
*/
uint8_t send_max_dc_brake_current_command
(float max_dc_brake_current_target);

/**
* Contents of this message:
* BMS/Status/State - The system state
* BMS/Status/Temp_Average - Average of all thermistor readings
*/
uint8_t send_bms_status
(uint8_t state,float temp_average);

/**
* Contents of this message:
* BMS/Cells/Volts_High_Value - The highest voltage cell value
* BMS/Cells/Volts_High_Chip - The highest voltage cell chip #
* BMS/Cells/Volts_High_Cell - The highest voltage cell #
* BMS/Cells/Volts_Low_Value - The lowest voltage cell value
* BMS/Cells/Volts_Low_Chip - The lowest voltage cell chip #
* BMS/Cells/Volts_Low_Cell - The lowest voltage cell #
* BMS/Cells/Volts_Avg_Value - The average voltage of all cells
*/
uint8_t send_cell_voltage
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val);

/**
* Contents of this message:
* BMS/Cells/Temp_High_Value - The highest temperature cell value
* BMS/Cells/Temp_High_Cell - The highest temperature cell #
* BMS/Cells/Temp_High_Chip - The highest temperature cell chip #
* BMS/Cells/Temp_Low_Value - The lowest temperature cell value
* BMS/Cells/Temp_Low_Cell - The lowest temperature cell #
* BMS/Cells/Temp_Low_Chip - The lowest temperature cell chip #
* BMS/Cells/Temp_Avg_Value - The average temperature of all cells
*/
uint8_t send_cell_temperatures
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val);

/**
* Contents of this message:
* BMS/Segment_Temp/0 - Average temperature of first segment
* BMS/Segment_Temp/1 - Average temperature of second segment
* BMS/Segment_Temp/2 - Average temperature of third segment
* BMS/Segment_Temp/3 - Average temperature of fourth segment
* BMS/Segment_Temp/4 - Average temperature of fifth segment
*/
uint8_t send_segment_temperatures
(float seg1,float seg2,float seg3,float seg4,float seg5);

/**
* Contents of this message:
* BMS/Segment_Comms/State - Current IsoSPI state
* BMS/Segment_Comms/Break_Location - Detected break location
* BMS/Segment_Comms/Verification_Attempts - Number of required recovery verification attempts
* BMS/Segment_Comms/Recovery_Successful - IsoSPI recovery completed successfully
* BMS/Segment_Comms/Extra - Reserved
*/
uint8_t send_segment_isospi_communication_status
(uint8_t state,uint8_t break_location,uint8_t verification_attempts,uint8_t recovery_successful);

/**
* Contents of this message:
* BMS/Faults/Critical/DCL_Enforce - DCL not being obeyed
* BMS/Faults/Critical/CCL_Enforce - CCL is not being obeyed
* BMS/Faults/Critical/Cell_Voltage_Low - Cell voltage is low
* BMS/Faults/Critical/Cell_Voltage_High - Cell voltage is high
* BMS/Faults/Critical/Charging_Voltage_High - Voltage when charging is high
* BMS/Faults/Critical/Pack_too_hot - Pack is too hot
* BMS/Faults/Critical/High_die_temp - Die temp ts too high
* BMS/Faults/Non-Critical/Segment_Comms_fault - Lost communications with segments
* BMS/Faults/Non-Critical/HV_Plate_Comms_Fault - Lost communications with HV Plate
* BMS/Faults/Non-Critical/Extra - Reserved
*/
uint8_t send_fault_status
(bool dcl_enforce,bool ccl_enforce,bool low_cell_volt,bool high_cell_volt,bool high_charge_volt,bool pack_hot,bool die_temp_max,bool segment_comms,bool hv_plate_comms);

/**
* Contents of this message:
* BMS/Segment_Volt/0 - Average voltage of first segment
* BMS/Segment_Volt/1 - Average voltage of second segment
* BMS/Segment_Volt/2 - Average voltage of third segment
* BMS/Segment_Volt/3 - Average voltage of fourth segment
* BMS/Segment_Volt/4 - Average voltage of fifth segment
* BMS/Segment_Volt/Extra - Reserved
*/
uint8_t send_segment_average_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5);

/**
* Contents of this message:
* BMS/Segment_Total_Volt/0 - Total voltage of first segment
* BMS/Segment_Total_Volt/1 - Total voltage of second segment
* BMS/Segment_Total_Volt/2 - Total voltage of third segment
* BMS/Segment_Total_Volt/3 - Total voltage of fourth segment
* BMS/Segment_Total_Volt/4 - Total voltage of fifth segment
* BMS/Segment_Total_Volt/Extra - Reserved
*/
uint8_t send_segment_total_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5);

/**
* Contents of this message:
* BMS/Segment_Delta_Volt/0 - Delta voltage of first segment
* BMS/Segment_Delta_Volt/1 - Delta voltage of second segment
* BMS/Segment_Delta_Volt/2 - Delta voltage of third segment
* BMS/Segment_Delta_Volt/3 - Delta voltage of fourth segment
* BMS/Segment_Delta_Volt/4 - Delta voltage of fifth segment
* BMS/Segment_Delta_Volt/Extra - Reserved
*/
uint8_t send_segment_delta_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5);

/**
* Contents of this message:
* BMS/Debug/Spare0 - Internal
* BMS/Debug/Spare1 - Internal
* BMS/Debug/Spare2 - Internal
* BMS/Debug/Spare3 - Internal
*/
uint8_t send_bms_debug
(uint8_t spare0,uint8_t spare1,uint16_t spare2,uint32_t spare3);

/**
* Contents of this message:
* BMS/Fault_Timer/Start_Stop - Whether the timer is starting or stopping
* BMS/Fault_Timer/Code - The fault code timer began for
* BMS/Fault_Timer/Value - The value evaluated to trigger fault
*/
uint8_t send_bms_fault_timers
(uint8_t start_stop,uint8_t code,float value);

/**
* Contents of this message:
* BMS/Version/Tag - The version tag deployed
* BMS/Version/Dirty - Whether the working tree was dirty
* BMS/Version/LocalCommit - Whether local-only commits were deployed
*/
uint8_t send_shepherd_version_tag
(uint8_t major,uint8_t minor,uint8_t patch,bool dirty,bool local_commit);

/**
* Contents of this message:
* BMS/Version/ShortHash - Hash of the deployed code
* BMS/Version/AuthorHash - Hash of the authors most recent commit
*/
uint8_t send_shepherd_version_hash
(uint32_t short_hash,uint32_t author_hash);


/**
* Contents of this message:
* BMS/PerCell/Alpha/{4}/Therms/{5} - Therm temperature
* BMS/PerCell/Alpha/{4}/Volts/{5} - Cell voltage
* BMS/PerCell/Alpha/{4}/Volts/{6} - Cell voltage
* BMS/PerCell/Alpha/{4}/Burning/{5} - Whether cell is burning
* BMS/PerCell/Alpha/{4}/Burning/{6} - Whether cell is burning
* BMS/PerCell/Alpha/{4}/CvS/{5} - Whether C and S ADCs read too different
* BMS/PerCell/Alpha/{4}/CvS/{6} - Whether C and S ADCs read too different
*/
uint8_t send_alpha_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b);

/**
* Contents of this message:
* BMS/PerCell/Beta/{4}/Therms/{5} - Therm temperature
* BMS/PerCell/Beta/{4}/Volts/{5} - Cell voltage
* BMS/PerCell/Beta/{4}/Volts/{6} - Cell voltage
* BMS/PerCell/Beta/{4}/Burning/{5} - Whether cell is burning
* BMS/PerCell/Beta/{4}/Burning/{6} - Whether cell is burning
* BMS/PerCell/Beta/{4}/CvS/{5} - Whether C and S ADCs read too different
* BMS/PerCell/Beta/{4}/CvS/{6} - Whether C and S ADCs read too different
*/
uint8_t send_beta_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b);

/**
* Contents of this message:
* BMS/PerCell/Alpha/{1}/DieTemp - Temperatue of ADBMS die
* BMS/PerCell/Alpha/{1}/VPV - Positive ADBMS voltage
* BMS/PerCell/Alpha/{1}/VMV - Voltage of S1N to V- of ADBMS
* BMS/PerCell/Alpha/{1}/Faults/VA_OV - Whether 5V Analog rail went over
* BMS/PerCell/Alpha/{1}/Faults/VA_UV - Whether 5V Analog rail went under
* BMS/PerCell/Alpha/{1}/Faults/VD_OV - Whether 3V digital rail went over
* BMS/PerCell/Alpha/{1}/Faults/VD_UV - Whether 3V digital rail went under
* BMS/PerCell/Alpha/{1}/Faults/VDE - 5V supply differed from Vreg by 0.5V+
* BMS/PerCell/Alpha/{1}/Faults/VDEL - All 5V supply differed from Vreg by 0.5V+
* BMS/PerCell/Alpha/{1}/Faults/SPI - Redundant SPI slave mismatch
* BMS/PerCell/Alpha/{1}/Faults/SLEEP - Sleep mode previously occured
* BMS/PerCell/Alpha/{1}/Faults/THSD - Thermal shutdown occured/occuring
* BMS/PerCell/Alpha/{1}/Faults/TMOD_CHCK - Test mode occured/occuring
* BMS/PerCell/Alpha/{1}/Faults/OSC_CHCK - Oscillator drift during ADC conversion detected
*/
uint8_t send_alpha_chip_a_debug
(uint8_t chip_id,float die_temp,float vpv,float vmv,bool va_ov,bool va_uv,bool vd_ov,bool vd_uv,bool vde,bool vdel,bool spiflt,bool sleep,bool thsd,bool tmodchk,bool oscchk);

/**
* Contents of this message:
* BMS/PerCell/Alpha/{2}/Vres - Vref2 of ADBMS across resistor
* BMS/PerCell/Alpha/{2}/Vref2 - 3V reference voltage of ADBMS
* BMS/PerCell/Alpha/{2}/Vanalog - Vreg voltage of ADBMS
* BMS/PerCell/Alpha/{2}/Vdigital - Digital in voltage of ADBMS
* BMS/PerCell/Alpha/{2}/Faults/OTP1 - Single trim error in S-NVM
* BMS/PerCell/Alpha/{2}/Faults/OTP2 - Multiple trim errors in S-NVM
*/
uint8_t send_alpha_chip_b_debug
(float vres,uint8_t chip_id,float vref2,float v_analog,float v_digital,bool otp1_med,bool opt2_med);

/**
* Contents of this message:
* BMS/PerCell/Beta/{1}/DieTemp - Temperatue of ADBMS die
* BMS/PerCell/Beta/{1}/VPV - Positive ADBMS voltage
* BMS/PerCell/Beta/{1}/VMV - Voltage of S1N to V- of ADBMS
* BMS/PerCell/Beta/{1}/Faults/VA_OV - Whether 5V Analog rail went over
* BMS/PerCell/Beta/{1}/Faults/VA_UV - Whether 5V Analog rail went under
* BMS/PerCell/Beta/{1}/Faults/VD_OV - Whether 3V digital rail went over
* BMS/PerCell/Beta/{1}/Faults/VD_UV - Whether 3V digital rail went under
* BMS/PerCell/Beta/{1}/Faults/VDE - 5V supply differed from Vreg by 0.5V+
* BMS/PerCell/Beta/{1}/Faults/VDEL - All 5V supply differed from Vreg by 0.5V+
* BMS/PerCell/Beta/{1}/Faults/SPI - Redundant SPI slave mismatch
* BMS/PerCell/Beta/{1}/Faults/SLEEP - Sleep mode previously occured
* BMS/PerCell/Beta/{1}/Faults/THSD - Thermal shutdown occured/occuring
* BMS/PerCell/Beta/{1}/Faults/TMOD_CHCK - Test mode occured/occuring
* BMS/PerCell/Beta/{1}/Faults/OSC_CHCK - Oscillator drift during ADC conversion detected
*/
uint8_t send_beta_chip_a_debug
(uint8_t chip_id,float die_temp,float vpv,float vmv,bool va_ov,bool va_uv,bool vd_ov,bool vd_uv,bool vde,bool vdel,bool spiflt,bool sleep,bool thsd,bool tmodchk,bool oscchk);

/**
* Contents of this message:
* BMS/PerCell/Beta/{2}/Vres - Vref2 of ADBMS across resistor
* BMS/PerCell/Beta/{2}/Vref2 - 3V reference voltage of ADBMS
* BMS/PerCell/Beta/{2}/Vanalog - Vreg voltage of ADBMS
* BMS/PerCell/Beta/{2}/Vdigital - Digital in voltage of ADBMS
* BMS/PerCell/Beta/{2}/Faults/OTP1 - Single trim error in S-NVM
* BMS/PerCell/Beta/{2}/Faults/OTP2 - Multiple trim errors in S-NVM
*/
uint8_t send_beta_chip_b_debug
(float vres,uint8_t chip_id,float vref2,float v_analog,float v_digital,bool otp1_med,bool opt2_med);

/**
* Contents of this message:
* BMS/Control/Fan/DutyCycle - Duty Cycle of Fan
*/
uint8_t send_fan_duty_cycle_percentage
(uint8_t fan_duty_cycle);

/**
* Contents of this message:
* BMS/Segment_Onboard_Temps/{1}/OnboardTemp1 - Temp of onboard therm 1
* BMS/Segment_Onboard_Temps/{1}/OnboardTemp2 - Temp of onboard therm 2
* BMS/Segment_Onboard_Temps/{1}/OnboardTemp3 - Temp of onboard therm 3
*/
uint8_t send_onboard_therm_temperatures
(uint8_t chip_id,float therm_temp_1,float therm_temp_2,float therm_temp_3);

/**
* Contents of this message:
* BMS/HV_Plate/Precharge - Indicates whether Precharge is active or not
*/
uint8_t send_precharge_status
(uint8_t precharge_status);

/**
* Contents of this message:
* BMS/HV_Plate/Batt_Voltage - Batt Voltage
* BMS/Precharge/TS_Voltage - TS Voltage
*/
uint8_t send_hv_plate_voltages
(float batt_voltage,float ts_voltage);

/**
* Contents of this message:
* BMS/Segment/{1}/PEC - PEC error count for segment communication for chip
*/
uint8_t send_segment_pec_errors
(uint8_t chip_id,uint16_t pec_errors);

/**
* Contents of this message:
* BMS/HV_Plate/PEC - PEC error count for communications with HV Plate
*/
uint8_t send_hv_plate_pec_errors
(uint16_t pec_errors);

/**
* Contents of this message:
* BMS/HV_Plate/Diagnostics/Flags - ADBMS2950 Flags
* BMS/HV_Plate/Diagnostics/VREG - VREG power supply pin
* BMS/HV_Plate/Diagnostics/TMP1 - Primary internal temperature
* BMS/HV_Plate/Diagnostics/VREF1P25 - VREF1P25 reference pin
* BMS/HV_Plate/Diagnostics/OSCCNT - Oscillator count
*/
uint8_t send_hv_plate_diagnostics
(uint16_t flags,float vreg,float tmp1,float vref1p25,uint16_t osccnt);

/**
* Contents of this message:
* BMS/Plate/Diagnostics/EPAD - Exposed pad
* BMS/Plate/Diagnostics/VDIG - Internal digital 3V supply
* BMS/Plate/Diagnostics/VDD - VDD power supply pin
* BMS/Plate/Diagnostics/TMP2 - Secondary internal temperature sensor
* BMS/Plate/Diagnostics/VDIV - 
* BMS/Plate/Diagnostics/Extra - Reserved
*/
uint8_t send_hv_plate_diagnostics_second
(float epad,float vdig,float vdd,float tmp2,float vdiv);

/**
* Contents of this message:
* BMS/Peripherals/Temperature - 
*/
uint8_t send_bms_onboard_temperature
(float internal_temp);

/**
* Contents of this message:
* BMS/Peripherals/IMU/Accelerometer - IMU acceleration values (x,y,z).
*/
uint8_t send_bms_imu_accelerometer
(float imu_accelerometer_x,float imu_accelerometer_y,float imu_accelerometer_z);

/**
* Contents of this message:
* BMS/Peripherals/IMU/Gyro - IMU Gyroscope Reading
*/
uint8_t send_bms_imu_gyro
(float imu_gyro_x,float imu_gyro_y,float imu_gyro_z);

/**
* Contents of this message:
* BMS/Pack/SoC - Pack state of charge
* BMS/Pack/SoC_Drift - Pack SoC drift from OCV curve
*/
uint8_t send_pack_soc_status
(float Pack_SoC,float Pack_SoC_Drift);

/**
* Contents of this message:
* BMS/Shutdown/State - Current shutdown state
* BMS/Shutdown/TS_Minus_Sense - 
* BMS/Shutdown/TS_Plus_Sense - 
* BMS/Shutdown/Acc_Sense - 
* BMS/Shutdown/TSIP_Sense - 
*/
uint8_t send_shutdown_as_read_by_bms
(bool shutdown_state,bool shutdown_ts_minus_sense,bool shutdown_ts_plus_sense,bool shutdown_acc_sense,bool shutdown_tsip_sense);

/**
* Contents of this message:
* BMS/HV_Plate_Comms/State - Current IsoSPI state
* BMS/HV_Plate_Comms/Verification_Attempts - Number of required recovery verification attempts
* BMS/HV_Plate_Comms/Recovery_Successful - IsoSPI recovery completed successfully
* BMS/HV_Plate_Comms/Extra - Reserved
*/
uint8_t send_hv_plate_isospi_communication_status
(uint8_t state,uint8_t verification_attempts,uint8_t recovery_successful);

/**
* Contents of this message:
* BMS/Faults/Critically_Faulted - If the BMS has a Critical Fault
*/
uint8_t send_bms_critically_faulted
(bool critically_faulted);

/**
* Contents of this message:
* BMS/HV_Plate/Pack_Current - 
* BMS/HV_Plate/Shunt_Temp - 
*/
uint8_t send_pack_current_and_shunt_temp
(float pack_current,float shunt_temp);

/**
* Contents of this message:
* BMS/Charging/Voltage - Voltage to charge to
* BMS/Charging/Current - Current to charge at
* BMS/Charging/Control - Whether to charge
* BMS/Charging/UnimplementedData - Reserved
*/
uint8_t send_bms_charge_message_send
(float charge_volts,float charge_current,uint8_t enable_charging);
#endif