#ifndef _CAN_MSGS_TX_H
#define _CAN_MSGS_TX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include <stdbool.h>
#include <stdint.h>

/**
* Contents of this message:
* BMS/Commands/Max_AC_Current_Target - This value determines the maximum allowable drive current on the AC side
*/
uint8_t send_max_ac_current_command
(float max_current_ac_target);

/**
* Contents of this message:
* BMS/Commands/Max_AC_Brake_Current_Target - This value sets the maximum allowable brake current on the AC side
*/
uint8_t send_max_ac_brake_current_command
(float max_ac_brake_current_target);

/**
* Contents of this message:
* BMS/Commands/Max_DC_Current_Target - This value determines the maximum allowable drive current on the DC side
*/
uint8_t send_max_dc_current_command
(float max_dc_current_target);

/**
* Contents of this message:
* BMS/Commands/Max_DC_Brake_Current_Target - This value determines the maximum allowable brake current on the DC side
*/
uint8_t send_max_dc_brake_current_command
(float max_dc_brake_current_target);

/**
* Contents of this message:
* BMS/Pack/Voltage - The total pack voltage.
* BMS/Pack/Current - The total pack current
* BMS/Pack/Amp-hours - Reserved
* BMS/Pack/SOC - The state of charge of the lowest cell
* BMS/Pack/Health - Reserved
*/
uint8_t send_pack_status
(float voltage,float current,float amp_hours,float soc,float health);

/**
* Contents of this message:
* BMS/Status/State - The system state
* BMS/Status/Temp_Average - Average of all thermistor readings
* BMS/Status/Temp_Internal - Board temperature
* BMS/Status/Balancing - Whether any cell in the pack is balancing
*/
uint8_t send_bms_status
(uint8_t state,float temp_average,float temp_internal,uint8_t balancing);

/**
* Contents of this message:
* BMS/Cells/Volts_High_Value - The highest voltage cell value
* BMS/Cells/Volts_High_Chip - The highest voltage cell chip #
* BMS/Cells/Volts_High_Cell - The highest voltage cell #
* BMS/Cells/Volts_Low_Value - The lowest voltage cell value
* BMS/Cells/Volts_Low_Chip - The lowest voltage cell chip #
* BMS/Cells/Volts_Low_Cell - The lowest voltage cell #
* BMS/Cells/Volts_Avg_Value - The average voltage of all cells
*/
uint8_t send_cell_voltage
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val);

/**
* Contents of this message:
* BMS/Cells/Temp_High_Value - The highest temperature cell value
* BMS/Cells/Temp_High_Cell - The highest temperature cell #
* BMS/Cells/Temp_High_Chip - The highest temperature cell chip #
* BMS/Cells/Temp_Low_Value - The lowest temperature cell value
* BMS/Cells/Temp_Low_Cell - The lowest temperature cell #
* BMS/Cells/Temp_Low_Chip - The lowest temperature cell chip #
* BMS/Cells/Temp_Avg_Value - The average temperature of all cells
*/
uint8_t send_cell_temperatures
(float high_val,uint8_t high_chip,uint8_t high_cell,float low_val,uint8_t low_chip,uint8_t low_cell,float avg_val);

/**
* Contents of this message:
* BMS/Segment_Temp/0 - Average temperature of first segment
* BMS/Segment_Temp/1 - Average temperature of second segment
* BMS/Segment_Temp/2 - Average temperature of third segment
* BMS/Segment_Temp/3 - Average temperature of fourth segment
* BMS/Segment_Temp/4 - Average temperature of fifth segment
*/
uint8_t send_segment_temperatures
(float seg1,float seg2,float seg3,float seg4,float seg5);

/**
* Contents of this message:
* BMS/Faults/Critical/Extra - Reserved
* BMS/Faults/Critical/CCL_Enforce - CCL is not being obeyed
* BMS/Faults/Critical/Charger_Can - Reserved
* BMS/Faults/Critical/Battery_Therm - Reserved
* BMS/Faults/Critical/Charger_Safety - Reserved
* BMS/Faults/Critical/DCL_Enforce - DCL is not being obeyed
* BMS/Faults/Critical/External_Can - Critical failure in CAN system
* BMS/Faults/Critical/Weak_Pack - Reserved
* BMS/Faults/Critical/Low_Cell_Volts - Cell voltage is below datasheet minimum
* BMS/Faults/Critical/Charge_Reading - Reserved
* BMS/Faults/Critical/Current_Sense - Failure to read current sensor from sensor or CAN
* BMS/Faults/Critical/IC_Comm - Reserved
* BMS/Faults/Critical/Thermal_Err - Reserved
* BMS/Faults/Critical/Software - Reserved
* BMS/Faults/Critical/Open_Wire - Reserved
* BMS/Faults/Critical/Pack_Overheat - Reserved
* BMS/Faults/Critical/Cell_Undervoltage - A cell has gone below datasheet minimum
* BMS/Faults/Critical/Cell_Overvoltage - A cell has gone above datasheet maximum
* BMS/Faults/Critical/Cells_Not_Balancing - Reserved
* BMS/Faults/Non-Critical/Extra - Reserved
*/
uint8_t send_fault_status
(bool ccl_enforce,bool charger_can,bool battery_therm,bool charger_safety,bool dcl_enforce,bool external_can,bool weak_pack,bool low_cell_volts,bool charge_reading,bool current_sense,bool ic_comm,bool thermal_err,bool sw_err,bool open_wire,bool pack_overheat,bool cell_uv,bool cell_ov,bool cell_not_balancing);

/**
* Contents of this message:
* BMS/Segment_Volt/0 - Average voltage of first segment
* BMS/Segment_Volt/1 - Average voltage of second segment
* BMS/Segment_Volt/2 - Average voltage of third segment
* BMS/Segment_Volt/3 - Average voltage of fourth segment
* BMS/Segment_Volt/4 - Average voltage of fifth segment
* BMS/Segment_Volt/Extra - Reserved
*/
uint8_t send_segment_average_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5);

/**
* Contents of this message:
* BMS/Segment_Total_Volt/0 - Total voltage of first segment
* BMS/Segment_Total_Volt/1 - Total voltage of second segment
* BMS/Segment_Total_Volt/2 - Total voltage of third segment
* BMS/Segment_Total_Volt/3 - Total voltage of fourth segment
* BMS/Segment_Total_Volt/4 - Total voltage of fifth segment
* BMS/Segment_Total_Volt/Extra - Reserved
*/
uint8_t send_segment_total_voltages
(float seg1,float seg2,float seg3,float seg4,float seg5);

/**
* Contents of this message:
* BMS/Debug/Spare0 - Internal
* BMS/Debug/Spare1 - Internal
* BMS/Debug/Spare2 - Internal
* BMS/Debug/Spare3 - Internal
*/
uint8_t send_bms_debug
(uint8_t spare0,uint8_t spare1,uint16_t spare2,uint32_t spare3);

/**
* Contents of this message:
* BMS/Fault_Timer/Start_Stop - Whether the timer is starting or stopping
* BMS/Fault_Timer/Code - The fault code timer began for
* BMS/Fault_Timer/Value - The value evaluated to trigger fault
*/
uint8_t send_bms_fault_timers
(uint8_t start_stop,uint8_t code,float value);

/**
* Contents of this message:
* BMS/Version/Tag - The version tag deployed
* BMS/Version/Dirty - Whether the working tree was dirty
* BMS/Version/LocalCommit - Whether local-only commits were deployed
*/
uint8_t send_shepherd_version_tag
(uint8_t major,uint8_t minor,uint8_t patch,bool dirty,bool local_commit);

/**
* Contents of this message:
* BMS/Version/ShortHash - Hash of the deployed code
* BMS/Version/AuthorHash - Hash of the authors most recent commit
*/
uint8_t send_shepherd_version_hash
(uint32_t short_hash,uint32_t author_hash);


/**
* Contents of this message:
* BMS/PerChip/PECErrorChip - The chip that has experienced PEC errors
* BMS/PerChip/PECErrorCount - The number of times errors have occured
*/
uint8_t send_pec_error_count_notification_per_chip
(uint8_t pec_error_chip,uint16_t pec_error_cnt);

/**
* Contents of this message:
* BMS/PerCell/Alpha/{4}/Therms/{5} - Therm temperature
* BMS/PerCell/Alpha/{4}/Volts/{5} - Cell voltage
* BMS/PerCell/Alpha/{4}/Volts/{6} - Cell voltage
* BMS/PerCell/Alpha/{4}/Burning/{5} - Whether cell is burning
* BMS/PerCell/Alpha/{4}/Burning/{6} - Whether cell is burning
* BMS/PerCell/Alpha/{4}/CvS/{5} - Whether C and S ADCs read too different
* BMS/PerCell/Alpha/{4}/CvS/{6} - Whether C and S ADCs read too different
*/
uint8_t send_alpha_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b);

/**
* Contents of this message:
* BMS/PerCell/Beta/{4}/Therms/{5} - Therm temperature
* BMS/PerCell/Beta/{4}/Volts/{5} - Cell voltage
* BMS/PerCell/Beta/{4}/Volts/{6} - Cell voltage
* BMS/PerCell/Beta/{4}/Burning/{5} - Whether cell is burning
* BMS/PerCell/Beta/{4}/Burning/{6} - Whether cell is burning
* BMS/PerCell/Beta/{4}/CvS/{5} - Whether C and S ADCs read too different
* BMS/PerCell/Beta/{4}/CvS/{6} - Whether C and S ADCs read too different
*/
uint8_t send_beta_cell_data_debug
(float therm,float voltage_a,float voltage_b,uint8_t chip_id,uint8_t cell_a,uint8_t cell_b,bool discharging_a,bool discharging_b,bool cvs_a,bool cvs_b);

/**
* Contents of this message:
* BMS/PerCell/Beta/{4}/Therms/10 - Therm temperature
* BMS/PerCell/Beta/{4}/Volts/10 - Cell voltage
* BMS/PerCell/Beta/{4}/Burning/10 - Whether cell is burning
* BMS/PerCell/Beta/{4}/SegTemp - Therm temperature of PCB therm
* BMS/PerCell/Beta/{4}/DieTemp - Temperatue of ADBMS die
* BMS/PerCell/Beta/{4}/VPV - Positive ADBMS voltage (across resistor)
*/
uint8_t send_beta_chip_a_debug
(float therm_last,float voltage_last,bool discharging_last,uint8_t chip_id,float seg_temp,float die_temp,float vpv);

/**
* Contents of this message:
* BMS/PerCell/Beta/{4}/Vref2 - 3V reference voltage of ADBMS
* BMS/PerCell/Beta/{4}/Vanalog - Vreg voltage of ADBMS
* BMS/PerCell/Beta/{4}/Vdigital - Digital in voltage of ADBMS
* BMS/PerCell/Beta/{4}/Vres - Vref2 of ADBMS across resistor
* BMS/PerCell/Beta/{4}/VMV - Voltage of S1N to V- of ADBMS
* BMS/PerCell/Beta/{4}/CvS/10 - Whether C and S ADCs read too different
*/
uint8_t send_beta_chip_b_debug
(float vref2,float v_analog,float v_digital,uint8_t chip_id,float v_res,float vmv,bool cvs_last);

/**
* Contents of this message:
* BMS/PerCell/Beta/{1}/Faults/VA_OV - Whether 5V Analog rail went over
* BMS/PerCell/Beta/{1}/Faults/VA_UV - Whether 5V Analog rail went under
* BMS/PerCell/Beta/{1}/Faults/VD_OV - Whether 3V digital rail went over
* BMS/PerCell/Beta/{1}/Faults/VD_UV - Whether 3V digital rail went under
* BMS/PerCell/Beta/{1}/Faults/VDE - 5V supply differed from Vreg by 0.5V+
* BMS/PerCell/Beta/{1}/Faults/VDEL - All 5V supply differed from Vreg by 0.5V+
* BMS/PerCell/Beta/{1}/Faults/SPI - Redundant SPI slave mismatch
* BMS/PerCell/Beta/{1}/Faults/SLEEP - Sleep mode previously occured
* BMS/PerCell/Beta/{1}/Faults/THSD - Thermal shutdown occured/occuring
* BMS/PerCell/Beta/{1}/Faults/TMOD_CHCK - Test mode occured/occuring
* BMS/PerCell/Beta/{1}/Faults/OSC_CHCK - Oscillator drift during ADC conversion detected
* BMS/PerCell/Beta/{1}/Faults/OTP1 - Single trim error in S-NVM
* BMS/PerCell/Beta/{1}/Faults/OTP2 - Multiple trim errors in S-NVM
*/
uint8_t send_beta_chip_c_debug
(bool chip_id,bool va_ov,bool va_uv,bool vd_ov,bool vd_uv,bool vde,bool vdel,bool spiflt,bool sleep,bool thsd,bool tmodchk,bool oscchk,bool otp1_med,bool otp2_med);

/**
* Contents of this message:
* BMS/PerCell/Alpha/{2}/SegTemp - Therm temperature of PCB therm
* BMS/PerCell/Alpha/{2}/DieTemp - Temperatue of ADBMS die
* BMS/PerCell/Alpha/{2}/VPV - Positive ADBMS voltage
* BMS/PerCell/Alpha/{2}/VMV - Voltage of S1N to V- of ADBMS
* BMS/PerCell/Alpha/{2}/Faults/VA_OV - Whether 5V Analog rail went over
* BMS/PerCell/Alpha/{2}/Faults/VA_UV - Whether 5V Analog rail went under
* BMS/PerCell/Alpha/{2}/Faults/VD_OV - Whether 3V digital rail went over
* BMS/PerCell/Alpha/{2}/Faults/VD_UV - Whether 3V digital rail went under
* BMS/PerCell/Alpha/{2}/Faults/VDE - 5V supply differed from Vreg by 0.5V+
* BMS/PerCell/Alpha/{2}/Faults/VDEL - All 5V supply differed from Vreg by 0.5V+
* BMS/PerCell/Alpha/{2}/Faults/SPI - Redundant SPI slave mismatch
* BMS/PerCell/Alpha/{2}/Faults/SLEEP - Sleep mode previously occured
* BMS/PerCell/Alpha/{2}/Faults/THSD - Thermal shutdown occured/occuring
* BMS/PerCell/Alpha/{2}/Faults/TMOD_CHCK - Test mode occured/occuring
* BMS/PerCell/Alpha/{2}/Faults/OSC_CHCK - Oscillator drift during ADC conversion detected
*/
uint8_t send_alpha_chip_a_debug
(float seg_temp,uint8_t chip_id,float die_temp,float vpv,float vmv,bool va_ov,bool va_uv,bool vd_ov,bool vd_uv,bool vde,bool vdel,bool spiflt,bool sleep,bool thsd,bool tmodchk,bool oscchk);

/**
* Contents of this message:
* BMS/PerCell/Alpha/{2}/Vres - Vref2 of ADBMS across resistor
* BMS/PerCell/Alpha/{2}/Vref2 - 3V reference voltage of ADBMS
* BMS/PerCell/Alpha/{2}/Vanalog - Vreg voltage of ADBMS
* BMS/PerCell/Alpha/{2}/Vdigital - Digital in voltage of ADBMS
* BMS/PerCell/Alpha/{2}/Faults/OTP1 - Single trim error in S-NVM
* BMS/PerCell/Alpha/{2}/Faults/OTP2 - Multiple trim errors in S-NVM
*/
uint8_t send_alpha_chip_b_debug
(float vres,uint8_t chip_id,float vref2,float v_analog,float v_digital,bool otp1_med,bool opt2_med);

/**
* Contents of this message:
* BMS/Charging/Voltage - Voltage to charge to
* BMS/Charging/Current - Current to charge at
* BMS/Charging/Control - Whether to charge
* BMS/Charging/UnimplementedData - Reserved
*/
uint8_t send_bms_charge_message_send
(float charge_volts,float charge_current,uint8_t enable_charging);
#endif