/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_ANALYZER_H
#define _MOCK_ANALYZER_H

#include "unity.h"
#include "analyzer.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_analyzer_Init(void);
void mock_analyzer_Destroy(void);
void mock_analyzer_Verify(void);




#define get_num_cells_Ignore() TEST_FAIL_MESSAGE("get_num_cells requires _IgnoreAndReturn");
#define get_num_cells_IgnoreAndReturn(cmock_retval) get_num_cells_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_num_cells_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define get_num_cells_StopIgnore() get_num_cells_CMockStopIgnore()
void get_num_cells_CMockStopIgnore(void);
#define get_num_cells_ExpectAnyArgs() TEST_FAIL_MESSAGE("get_num_cells requires _ExpectAnyArgsAndReturn");
#define get_num_cells_ExpectAnyArgsAndReturn(cmock_retval) get_num_cells_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void get_num_cells_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define get_num_cells_Expect(chip_data) TEST_FAIL_MESSAGE("get_num_cells requires _ExpectAndReturn");
#define get_num_cells_ExpectAndReturn(chip_data, cmock_retval) get_num_cells_CMockExpectAndReturn(__LINE__, chip_data, cmock_retval)
void get_num_cells_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, chipdata_t* chip_data, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_get_num_cells_CALLBACK)(chipdata_t* chip_data, int cmock_num_calls);
void get_num_cells_AddCallback(CMOCK_get_num_cells_CALLBACK Callback);
void get_num_cells_Stub(CMOCK_get_num_cells_CALLBACK Callback);
#define get_num_cells_StubWithCallback get_num_cells_Stub
#define get_num_cells_IgnoreArg_chip_data() get_num_cells_CMockIgnoreArg_chip_data(__LINE__)
void get_num_cells_CMockIgnoreArg_chip_data(UNITY_LINE_TYPE cmock_line);
#define calc_cell_temps_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cell_temps requires _Ignore (not AndReturn)");
#define calc_cell_temps_Ignore() calc_cell_temps_CMockIgnore()
void calc_cell_temps_CMockIgnore(void);
#define calc_cell_temps_StopIgnore() calc_cell_temps_CMockStopIgnore()
void calc_cell_temps_CMockStopIgnore(void);
#define calc_cell_temps_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cell_temps requires _ExpectAnyArgs (not AndReturn)");
#define calc_cell_temps_ExpectAnyArgs() calc_cell_temps_CMockExpectAnyArgs(__LINE__)
void calc_cell_temps_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define calc_cell_temps_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("calc_cell_temps requires _Expect (not AndReturn)");
#define calc_cell_temps_Expect(bmsdata) calc_cell_temps_CMockExpect(__LINE__, bmsdata)
void calc_cell_temps_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata);
typedef void (* CMOCK_calc_cell_temps_CALLBACK)(acc_data_t* bmsdata, int cmock_num_calls);
void calc_cell_temps_AddCallback(CMOCK_calc_cell_temps_CALLBACK Callback);
void calc_cell_temps_Stub(CMOCK_calc_cell_temps_CALLBACK Callback);
#define calc_cell_temps_StubWithCallback calc_cell_temps_Stub
#define calc_cell_temps_IgnoreArg_bmsdata() calc_cell_temps_CMockIgnoreArg_bmsdata(__LINE__)
void calc_cell_temps_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);
#define calc_pack_temps_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_pack_temps requires _Ignore (not AndReturn)");
#define calc_pack_temps_Ignore() calc_pack_temps_CMockIgnore()
void calc_pack_temps_CMockIgnore(void);
#define calc_pack_temps_StopIgnore() calc_pack_temps_CMockStopIgnore()
void calc_pack_temps_CMockStopIgnore(void);
#define calc_pack_temps_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_pack_temps requires _ExpectAnyArgs (not AndReturn)");
#define calc_pack_temps_ExpectAnyArgs() calc_pack_temps_CMockExpectAnyArgs(__LINE__)
void calc_pack_temps_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define calc_pack_temps_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("calc_pack_temps requires _Expect (not AndReturn)");
#define calc_pack_temps_Expect(bmsdata) calc_pack_temps_CMockExpect(__LINE__, bmsdata)
void calc_pack_temps_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata);
typedef void (* CMOCK_calc_pack_temps_CALLBACK)(acc_data_t* bmsdata, int cmock_num_calls);
void calc_pack_temps_AddCallback(CMOCK_calc_pack_temps_CALLBACK Callback);
void calc_pack_temps_Stub(CMOCK_calc_pack_temps_CALLBACK Callback);
#define calc_pack_temps_StubWithCallback calc_pack_temps_Stub
#define calc_pack_temps_IgnoreArg_bmsdata() calc_pack_temps_CMockIgnoreArg_bmsdata(__LINE__)
void calc_pack_temps_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);
#define calc_cell_voltages_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cell_voltages requires _Ignore (not AndReturn)");
#define calc_cell_voltages_Ignore() calc_cell_voltages_CMockIgnore()
void calc_cell_voltages_CMockIgnore(void);
#define calc_cell_voltages_StopIgnore() calc_cell_voltages_CMockStopIgnore()
void calc_cell_voltages_CMockStopIgnore(void);
#define calc_cell_voltages_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cell_voltages requires _ExpectAnyArgs (not AndReturn)");
#define calc_cell_voltages_ExpectAnyArgs() calc_cell_voltages_CMockExpectAnyArgs(__LINE__)
void calc_cell_voltages_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define calc_cell_voltages_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("calc_cell_voltages requires _Expect (not AndReturn)");
#define calc_cell_voltages_Expect(bmsdata) calc_cell_voltages_CMockExpect(__LINE__, bmsdata)
void calc_cell_voltages_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata);
typedef void (* CMOCK_calc_cell_voltages_CALLBACK)(acc_data_t* bmsdata, int cmock_num_calls);
void calc_cell_voltages_AddCallback(CMOCK_calc_cell_voltages_CALLBACK Callback);
void calc_cell_voltages_Stub(CMOCK_calc_cell_voltages_CALLBACK Callback);
#define calc_cell_voltages_StubWithCallback calc_cell_voltages_Stub
#define calc_cell_voltages_IgnoreArg_bmsdata() calc_cell_voltages_CMockIgnoreArg_bmsdata(__LINE__)
void calc_cell_voltages_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);
#define calc_pack_voltage_stats_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_pack_voltage_stats requires _Ignore (not AndReturn)");
#define calc_pack_voltage_stats_Ignore() calc_pack_voltage_stats_CMockIgnore()
void calc_pack_voltage_stats_CMockIgnore(void);
#define calc_pack_voltage_stats_StopIgnore() calc_pack_voltage_stats_CMockStopIgnore()
void calc_pack_voltage_stats_CMockStopIgnore(void);
#define calc_pack_voltage_stats_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_pack_voltage_stats requires _ExpectAnyArgs (not AndReturn)");
#define calc_pack_voltage_stats_ExpectAnyArgs() calc_pack_voltage_stats_CMockExpectAnyArgs(__LINE__)
void calc_pack_voltage_stats_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define calc_pack_voltage_stats_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("calc_pack_voltage_stats requires _Expect (not AndReturn)");
#define calc_pack_voltage_stats_Expect(bmsdata) calc_pack_voltage_stats_CMockExpect(__LINE__, bmsdata)
void calc_pack_voltage_stats_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata);
typedef void (* CMOCK_calc_pack_voltage_stats_CALLBACK)(acc_data_t* bmsdata, int cmock_num_calls);
void calc_pack_voltage_stats_AddCallback(CMOCK_calc_pack_voltage_stats_CALLBACK Callback);
void calc_pack_voltage_stats_Stub(CMOCK_calc_pack_voltage_stats_CALLBACK Callback);
#define calc_pack_voltage_stats_StubWithCallback calc_pack_voltage_stats_Stub
#define calc_pack_voltage_stats_IgnoreArg_bmsdata() calc_pack_voltage_stats_CMockIgnoreArg_bmsdata(__LINE__)
void calc_pack_voltage_stats_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);
#define calc_open_cell_voltage_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_open_cell_voltage requires _Ignore (not AndReturn)");
#define calc_open_cell_voltage_Ignore() calc_open_cell_voltage_CMockIgnore()
void calc_open_cell_voltage_CMockIgnore(void);
#define calc_open_cell_voltage_StopIgnore() calc_open_cell_voltage_CMockStopIgnore()
void calc_open_cell_voltage_CMockStopIgnore(void);
#define calc_open_cell_voltage_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_open_cell_voltage requires _ExpectAnyArgs (not AndReturn)");
#define calc_open_cell_voltage_ExpectAnyArgs() calc_open_cell_voltage_CMockExpectAnyArgs(__LINE__)
void calc_open_cell_voltage_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define calc_open_cell_voltage_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("calc_open_cell_voltage requires _Expect (not AndReturn)");
#define calc_open_cell_voltage_Expect(bmsdata) calc_open_cell_voltage_CMockExpect(__LINE__, bmsdata)
void calc_open_cell_voltage_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata);
typedef void (* CMOCK_calc_open_cell_voltage_CALLBACK)(acc_data_t* bmsdata, int cmock_num_calls);
void calc_open_cell_voltage_AddCallback(CMOCK_calc_open_cell_voltage_CALLBACK Callback);
void calc_open_cell_voltage_Stub(CMOCK_calc_open_cell_voltage_CALLBACK Callback);
#define calc_open_cell_voltage_StubWithCallback calc_open_cell_voltage_Stub
#define calc_open_cell_voltage_IgnoreArg_bmsdata() calc_open_cell_voltage_CMockIgnoreArg_bmsdata(__LINE__)
void calc_open_cell_voltage_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);
#define calc_cell_resistances_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cell_resistances requires _Ignore (not AndReturn)");
#define calc_cell_resistances_Ignore() calc_cell_resistances_CMockIgnore()
void calc_cell_resistances_CMockIgnore(void);
#define calc_cell_resistances_StopIgnore() calc_cell_resistances_CMockStopIgnore()
void calc_cell_resistances_CMockStopIgnore(void);
#define calc_cell_resistances_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cell_resistances requires _ExpectAnyArgs (not AndReturn)");
#define calc_cell_resistances_ExpectAnyArgs() calc_cell_resistances_CMockExpectAnyArgs(__LINE__)
void calc_cell_resistances_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define calc_cell_resistances_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("calc_cell_resistances requires _Expect (not AndReturn)");
#define calc_cell_resistances_Expect(bmsdata) calc_cell_resistances_CMockExpect(__LINE__, bmsdata)
void calc_cell_resistances_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata);
typedef void (* CMOCK_calc_cell_resistances_CALLBACK)(acc_data_t* bmsdata, int cmock_num_calls);
void calc_cell_resistances_AddCallback(CMOCK_calc_cell_resistances_CALLBACK Callback);
void calc_cell_resistances_Stub(CMOCK_calc_cell_resistances_CALLBACK Callback);
#define calc_cell_resistances_StubWithCallback calc_cell_resistances_Stub
#define calc_cell_resistances_IgnoreArg_bmsdata() calc_cell_resistances_CMockIgnoreArg_bmsdata(__LINE__)
void calc_cell_resistances_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);
#define calc_cont_dcl_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cont_dcl requires _Ignore (not AndReturn)");
#define calc_cont_dcl_Ignore() calc_cont_dcl_CMockIgnore()
void calc_cont_dcl_CMockIgnore(void);
#define calc_cont_dcl_StopIgnore() calc_cont_dcl_CMockStopIgnore()
void calc_cont_dcl_CMockStopIgnore(void);
#define calc_cont_dcl_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cont_dcl requires _ExpectAnyArgs (not AndReturn)");
#define calc_cont_dcl_ExpectAnyArgs() calc_cont_dcl_CMockExpectAnyArgs(__LINE__)
void calc_cont_dcl_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define calc_cont_dcl_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("calc_cont_dcl requires _Expect (not AndReturn)");
#define calc_cont_dcl_Expect(bmsdata) calc_cont_dcl_CMockExpect(__LINE__, bmsdata)
void calc_cont_dcl_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata);
typedef void (* CMOCK_calc_cont_dcl_CALLBACK)(acc_data_t* bmsdata, int cmock_num_calls);
void calc_cont_dcl_AddCallback(CMOCK_calc_cont_dcl_CALLBACK Callback);
void calc_cont_dcl_Stub(CMOCK_calc_cont_dcl_CALLBACK Callback);
#define calc_cont_dcl_StubWithCallback calc_cont_dcl_Stub
#define calc_cont_dcl_IgnoreArg_bmsdata() calc_cont_dcl_CMockIgnoreArg_bmsdata(__LINE__)
void calc_cont_dcl_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);
#define calc_cont_ccl_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cont_ccl requires _Ignore (not AndReturn)");
#define calc_cont_ccl_Ignore() calc_cont_ccl_CMockIgnore()
void calc_cont_ccl_CMockIgnore(void);
#define calc_cont_ccl_StopIgnore() calc_cont_ccl_CMockStopIgnore()
void calc_cont_ccl_CMockStopIgnore(void);
#define calc_cont_ccl_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_cont_ccl requires _ExpectAnyArgs (not AndReturn)");
#define calc_cont_ccl_ExpectAnyArgs() calc_cont_ccl_CMockExpectAnyArgs(__LINE__)
void calc_cont_ccl_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define calc_cont_ccl_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("calc_cont_ccl requires _Expect (not AndReturn)");
#define calc_cont_ccl_Expect(bmsdata) calc_cont_ccl_CMockExpect(__LINE__, bmsdata)
void calc_cont_ccl_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata);
typedef void (* CMOCK_calc_cont_ccl_CALLBACK)(acc_data_t* bmsdata, int cmock_num_calls);
void calc_cont_ccl_AddCallback(CMOCK_calc_cont_ccl_CALLBACK Callback);
void calc_cont_ccl_Stub(CMOCK_calc_cont_ccl_CALLBACK Callback);
#define calc_cont_ccl_StubWithCallback calc_cont_ccl_Stub
#define calc_cont_ccl_IgnoreArg_bmsdata() calc_cont_ccl_CMockIgnoreArg_bmsdata(__LINE__)
void calc_cont_ccl_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);
#define calc_state_of_charge_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_state_of_charge requires _Ignore (not AndReturn)");
#define calc_state_of_charge_Ignore() calc_state_of_charge_CMockIgnore()
void calc_state_of_charge_CMockIgnore(void);
#define calc_state_of_charge_StopIgnore() calc_state_of_charge_CMockStopIgnore()
void calc_state_of_charge_CMockStopIgnore(void);
#define calc_state_of_charge_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("calc_state_of_charge requires _ExpectAnyArgs (not AndReturn)");
#define calc_state_of_charge_ExpectAnyArgs() calc_state_of_charge_CMockExpectAnyArgs(__LINE__)
void calc_state_of_charge_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define calc_state_of_charge_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("calc_state_of_charge requires _Expect (not AndReturn)");
#define calc_state_of_charge_Expect(bmsdata) calc_state_of_charge_CMockExpect(__LINE__, bmsdata)
void calc_state_of_charge_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata);
typedef void (* CMOCK_calc_state_of_charge_CALLBACK)(acc_data_t* bmsdata, int cmock_num_calls);
void calc_state_of_charge_AddCallback(CMOCK_calc_state_of_charge_CALLBACK Callback);
void calc_state_of_charge_Stub(CMOCK_calc_state_of_charge_CALLBACK Callback);
#define calc_state_of_charge_StubWithCallback calc_state_of_charge_Stub
#define calc_state_of_charge_IgnoreArg_bmsdata() calc_state_of_charge_CMockIgnoreArg_bmsdata(__LINE__)
void calc_state_of_charge_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
