/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_analyzer.h"

static const char* CMockString_bmsdata = "bmsdata";
static const char* CMockString_calc_cell_resistances = "calc_cell_resistances";
static const char* CMockString_calc_cell_temps = "calc_cell_temps";
static const char* CMockString_calc_cell_voltages = "calc_cell_voltages";
static const char* CMockString_calc_cont_ccl = "calc_cont_ccl";
static const char* CMockString_calc_cont_dcl = "calc_cont_dcl";
static const char* CMockString_calc_open_cell_voltage = "calc_open_cell_voltage";
static const char* CMockString_calc_pack_temps = "calc_pack_temps";
static const char* CMockString_calc_pack_voltage_stats = "calc_pack_voltage_stats";
static const char* CMockString_calc_state_of_charge = "calc_state_of_charge";
static const char* CMockString_chip_data = "chip_data";
static const char* CMockString_get_num_cells = "get_num_cells";

typedef struct _CMOCK_get_num_cells_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  chipdata_t* Expected_chip_data;
  char IgnoreArg_chip_data;

} CMOCK_get_num_cells_CALL_INSTANCE;

typedef struct _CMOCK_calc_cell_temps_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  acc_data_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_calc_cell_temps_CALL_INSTANCE;

typedef struct _CMOCK_calc_pack_temps_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  acc_data_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_calc_pack_temps_CALL_INSTANCE;

typedef struct _CMOCK_calc_cell_voltages_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  acc_data_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_calc_cell_voltages_CALL_INSTANCE;

typedef struct _CMOCK_calc_pack_voltage_stats_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  acc_data_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_calc_pack_voltage_stats_CALL_INSTANCE;

typedef struct _CMOCK_calc_open_cell_voltage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  acc_data_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_calc_open_cell_voltage_CALL_INSTANCE;

typedef struct _CMOCK_calc_cell_resistances_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  acc_data_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_calc_cell_resistances_CALL_INSTANCE;

typedef struct _CMOCK_calc_cont_dcl_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  acc_data_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_calc_cont_dcl_CALL_INSTANCE;

typedef struct _CMOCK_calc_cont_ccl_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  acc_data_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_calc_cont_ccl_CALL_INSTANCE;

typedef struct _CMOCK_calc_state_of_charge_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  acc_data_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_calc_state_of_charge_CALL_INSTANCE;

static struct mock_analyzerInstance
{
  char get_num_cells_IgnoreBool;
  uint8_t get_num_cells_FinalReturn;
  char get_num_cells_CallbackBool;
  CMOCK_get_num_cells_CALLBACK get_num_cells_CallbackFunctionPointer;
  int get_num_cells_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_num_cells_CallInstance;
  char calc_cell_temps_IgnoreBool;
  char calc_cell_temps_CallbackBool;
  CMOCK_calc_cell_temps_CALLBACK calc_cell_temps_CallbackFunctionPointer;
  int calc_cell_temps_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_cell_temps_CallInstance;
  char calc_pack_temps_IgnoreBool;
  char calc_pack_temps_CallbackBool;
  CMOCK_calc_pack_temps_CALLBACK calc_pack_temps_CallbackFunctionPointer;
  int calc_pack_temps_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_pack_temps_CallInstance;
  char calc_cell_voltages_IgnoreBool;
  char calc_cell_voltages_CallbackBool;
  CMOCK_calc_cell_voltages_CALLBACK calc_cell_voltages_CallbackFunctionPointer;
  int calc_cell_voltages_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_cell_voltages_CallInstance;
  char calc_pack_voltage_stats_IgnoreBool;
  char calc_pack_voltage_stats_CallbackBool;
  CMOCK_calc_pack_voltage_stats_CALLBACK calc_pack_voltage_stats_CallbackFunctionPointer;
  int calc_pack_voltage_stats_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_pack_voltage_stats_CallInstance;
  char calc_open_cell_voltage_IgnoreBool;
  char calc_open_cell_voltage_CallbackBool;
  CMOCK_calc_open_cell_voltage_CALLBACK calc_open_cell_voltage_CallbackFunctionPointer;
  int calc_open_cell_voltage_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_open_cell_voltage_CallInstance;
  char calc_cell_resistances_IgnoreBool;
  char calc_cell_resistances_CallbackBool;
  CMOCK_calc_cell_resistances_CALLBACK calc_cell_resistances_CallbackFunctionPointer;
  int calc_cell_resistances_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_cell_resistances_CallInstance;
  char calc_cont_dcl_IgnoreBool;
  char calc_cont_dcl_CallbackBool;
  CMOCK_calc_cont_dcl_CALLBACK calc_cont_dcl_CallbackFunctionPointer;
  int calc_cont_dcl_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_cont_dcl_CallInstance;
  char calc_cont_ccl_IgnoreBool;
  char calc_cont_ccl_CallbackBool;
  CMOCK_calc_cont_ccl_CALLBACK calc_cont_ccl_CallbackFunctionPointer;
  int calc_cont_ccl_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_cont_ccl_CallInstance;
  char calc_state_of_charge_IgnoreBool;
  char calc_state_of_charge_CallbackBool;
  CMOCK_calc_state_of_charge_CALLBACK calc_state_of_charge_CallbackFunctionPointer;
  int calc_state_of_charge_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE calc_state_of_charge_CallInstance;
} Mock;


void mock_analyzer_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.get_num_cells_CallInstance;
  if (Mock.get_num_cells_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_num_cells);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_num_cells_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.calc_cell_temps_CallInstance;
  if (Mock.calc_cell_temps_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_cell_temps);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_cell_temps_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.calc_pack_temps_CallInstance;
  if (Mock.calc_pack_temps_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_pack_temps);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_pack_temps_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.calc_cell_voltages_CallInstance;
  if (Mock.calc_cell_voltages_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_cell_voltages);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_cell_voltages_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.calc_pack_voltage_stats_CallInstance;
  if (Mock.calc_pack_voltage_stats_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_pack_voltage_stats);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_pack_voltage_stats_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.calc_open_cell_voltage_CallInstance;
  if (Mock.calc_open_cell_voltage_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_open_cell_voltage);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_open_cell_voltage_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.calc_cell_resistances_CallInstance;
  if (Mock.calc_cell_resistances_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_cell_resistances);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_cell_resistances_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.calc_cont_dcl_CallInstance;
  if (Mock.calc_cont_dcl_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_cont_dcl);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_cont_dcl_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.calc_cont_ccl_CallInstance;
  if (Mock.calc_cont_ccl_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_cont_ccl);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_cont_ccl_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.calc_state_of_charge_CallInstance;
  if (Mock.calc_state_of_charge_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_calc_state_of_charge);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.calc_state_of_charge_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_analyzer_Init(void)
{
  mock_analyzer_Destroy();
}

void mock_analyzer_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint8_t get_num_cells(chipdata_t* chip_data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_num_cells_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_num_cells);
  cmock_call_instance = (CMOCK_get_num_cells_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_num_cells_CallInstance);
  Mock.get_num_cells_CallInstance = CMock_Guts_MemNext(Mock.get_num_cells_CallInstance);
  if (Mock.get_num_cells_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_num_cells_FinalReturn;
    Mock.get_num_cells_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_num_cells_CallbackBool &&
      Mock.get_num_cells_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.get_num_cells_CallbackFunctionPointer(chip_data, Mock.get_num_cells_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_chip_data)
  {
    UNITY_SET_DETAILS(CMockString_get_num_cells,CMockString_chip_data);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_chip_data), (void*)(chip_data), sizeof(chipdata_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.get_num_cells_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_num_cells_CallbackFunctionPointer(chip_data, Mock.get_num_cells_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_num_cells(CMOCK_get_num_cells_CALL_INSTANCE* cmock_call_instance, chipdata_t* chip_data);
void CMockExpectParameters_get_num_cells(CMOCK_get_num_cells_CALL_INSTANCE* cmock_call_instance, chipdata_t* chip_data)
{
  cmock_call_instance->Expected_chip_data = chip_data;
  cmock_call_instance->IgnoreArg_chip_data = 0;
}

void get_num_cells_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_num_cells_CALL_INSTANCE));
  CMOCK_get_num_cells_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_num_cells_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_num_cells_CallInstance = CMock_Guts_MemChain(Mock.get_num_cells_CallInstance, cmock_guts_index);
  Mock.get_num_cells_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_num_cells_IgnoreBool = (char)1;
}

void get_num_cells_CMockStopIgnore(void)
{
  if(Mock.get_num_cells_IgnoreBool)
    Mock.get_num_cells_CallInstance = CMock_Guts_MemNext(Mock.get_num_cells_CallInstance);
  Mock.get_num_cells_IgnoreBool = (char)0;
}

void get_num_cells_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_num_cells_CALL_INSTANCE));
  CMOCK_get_num_cells_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_num_cells_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_num_cells_CallInstance = CMock_Guts_MemChain(Mock.get_num_cells_CallInstance, cmock_guts_index);
  Mock.get_num_cells_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_num_cells_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, chipdata_t* chip_data, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_num_cells_CALL_INSTANCE));
  CMOCK_get_num_cells_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_num_cells_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_num_cells_CallInstance = CMock_Guts_MemChain(Mock.get_num_cells_CallInstance, cmock_guts_index);
  Mock.get_num_cells_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_num_cells(cmock_call_instance, chip_data);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_num_cells_AddCallback(CMOCK_get_num_cells_CALLBACK Callback)
{
  Mock.get_num_cells_IgnoreBool = (char)0;
  Mock.get_num_cells_CallbackBool = (char)1;
  Mock.get_num_cells_CallbackFunctionPointer = Callback;
}

void get_num_cells_Stub(CMOCK_get_num_cells_CALLBACK Callback)
{
  Mock.get_num_cells_IgnoreBool = (char)0;
  Mock.get_num_cells_CallbackBool = (char)0;
  Mock.get_num_cells_CallbackFunctionPointer = Callback;
}

void get_num_cells_CMockIgnoreArg_chip_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_num_cells_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_num_cells_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_num_cells_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_chip_data = 1;
}

void calc_cell_temps(acc_data_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_cell_temps_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_cell_temps);
  cmock_call_instance = (CMOCK_calc_cell_temps_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_cell_temps_CallInstance);
  Mock.calc_cell_temps_CallInstance = CMock_Guts_MemNext(Mock.calc_cell_temps_CallInstance);
  if (Mock.calc_cell_temps_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.calc_cell_temps_CallbackBool &&
      Mock.calc_cell_temps_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cell_temps_CallbackFunctionPointer(bmsdata, Mock.calc_cell_temps_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_calc_cell_temps,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(acc_data_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_cell_temps_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cell_temps_CallbackFunctionPointer(bmsdata, Mock.calc_cell_temps_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_calc_cell_temps(CMOCK_calc_cell_temps_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata);
void CMockExpectParameters_calc_cell_temps(CMOCK_calc_cell_temps_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void calc_cell_temps_CMockIgnore(void)
{
  Mock.calc_cell_temps_IgnoreBool = (char)1;
}

void calc_cell_temps_CMockStopIgnore(void)
{
  Mock.calc_cell_temps_IgnoreBool = (char)0;
}

void calc_cell_temps_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cell_temps_CALL_INSTANCE));
  CMOCK_calc_cell_temps_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cell_temps_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cell_temps_CallInstance = CMock_Guts_MemChain(Mock.calc_cell_temps_CallInstance, cmock_guts_index);
  Mock.calc_cell_temps_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_cell_temps_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cell_temps_CALL_INSTANCE));
  CMOCK_calc_cell_temps_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cell_temps_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cell_temps_CallInstance = CMock_Guts_MemChain(Mock.calc_cell_temps_CallInstance, cmock_guts_index);
  Mock.calc_cell_temps_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_cell_temps(cmock_call_instance, bmsdata);
}

void calc_cell_temps_AddCallback(CMOCK_calc_cell_temps_CALLBACK Callback)
{
  Mock.calc_cell_temps_IgnoreBool = (char)0;
  Mock.calc_cell_temps_CallbackBool = (char)1;
  Mock.calc_cell_temps_CallbackFunctionPointer = Callback;
}

void calc_cell_temps_Stub(CMOCK_calc_cell_temps_CALLBACK Callback)
{
  Mock.calc_cell_temps_IgnoreBool = (char)0;
  Mock.calc_cell_temps_CallbackBool = (char)0;
  Mock.calc_cell_temps_CallbackFunctionPointer = Callback;
}

void calc_cell_temps_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_cell_temps_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cell_temps_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_cell_temps_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

void calc_pack_temps(acc_data_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_pack_temps_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_pack_temps);
  cmock_call_instance = (CMOCK_calc_pack_temps_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_pack_temps_CallInstance);
  Mock.calc_pack_temps_CallInstance = CMock_Guts_MemNext(Mock.calc_pack_temps_CallInstance);
  if (Mock.calc_pack_temps_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.calc_pack_temps_CallbackBool &&
      Mock.calc_pack_temps_CallbackFunctionPointer != NULL)
  {
    Mock.calc_pack_temps_CallbackFunctionPointer(bmsdata, Mock.calc_pack_temps_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_calc_pack_temps,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(acc_data_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_pack_temps_CallbackFunctionPointer != NULL)
  {
    Mock.calc_pack_temps_CallbackFunctionPointer(bmsdata, Mock.calc_pack_temps_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_calc_pack_temps(CMOCK_calc_pack_temps_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata);
void CMockExpectParameters_calc_pack_temps(CMOCK_calc_pack_temps_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void calc_pack_temps_CMockIgnore(void)
{
  Mock.calc_pack_temps_IgnoreBool = (char)1;
}

void calc_pack_temps_CMockStopIgnore(void)
{
  Mock.calc_pack_temps_IgnoreBool = (char)0;
}

void calc_pack_temps_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_pack_temps_CALL_INSTANCE));
  CMOCK_calc_pack_temps_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_pack_temps_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_pack_temps_CallInstance = CMock_Guts_MemChain(Mock.calc_pack_temps_CallInstance, cmock_guts_index);
  Mock.calc_pack_temps_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_pack_temps_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_pack_temps_CALL_INSTANCE));
  CMOCK_calc_pack_temps_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_pack_temps_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_pack_temps_CallInstance = CMock_Guts_MemChain(Mock.calc_pack_temps_CallInstance, cmock_guts_index);
  Mock.calc_pack_temps_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_pack_temps(cmock_call_instance, bmsdata);
}

void calc_pack_temps_AddCallback(CMOCK_calc_pack_temps_CALLBACK Callback)
{
  Mock.calc_pack_temps_IgnoreBool = (char)0;
  Mock.calc_pack_temps_CallbackBool = (char)1;
  Mock.calc_pack_temps_CallbackFunctionPointer = Callback;
}

void calc_pack_temps_Stub(CMOCK_calc_pack_temps_CALLBACK Callback)
{
  Mock.calc_pack_temps_IgnoreBool = (char)0;
  Mock.calc_pack_temps_CallbackBool = (char)0;
  Mock.calc_pack_temps_CallbackFunctionPointer = Callback;
}

void calc_pack_temps_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_pack_temps_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_pack_temps_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_pack_temps_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

void calc_cell_voltages(acc_data_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_cell_voltages_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_cell_voltages);
  cmock_call_instance = (CMOCK_calc_cell_voltages_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_cell_voltages_CallInstance);
  Mock.calc_cell_voltages_CallInstance = CMock_Guts_MemNext(Mock.calc_cell_voltages_CallInstance);
  if (Mock.calc_cell_voltages_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.calc_cell_voltages_CallbackBool &&
      Mock.calc_cell_voltages_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cell_voltages_CallbackFunctionPointer(bmsdata, Mock.calc_cell_voltages_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_calc_cell_voltages,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(acc_data_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_cell_voltages_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cell_voltages_CallbackFunctionPointer(bmsdata, Mock.calc_cell_voltages_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_calc_cell_voltages(CMOCK_calc_cell_voltages_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata);
void CMockExpectParameters_calc_cell_voltages(CMOCK_calc_cell_voltages_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void calc_cell_voltages_CMockIgnore(void)
{
  Mock.calc_cell_voltages_IgnoreBool = (char)1;
}

void calc_cell_voltages_CMockStopIgnore(void)
{
  Mock.calc_cell_voltages_IgnoreBool = (char)0;
}

void calc_cell_voltages_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cell_voltages_CALL_INSTANCE));
  CMOCK_calc_cell_voltages_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cell_voltages_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cell_voltages_CallInstance = CMock_Guts_MemChain(Mock.calc_cell_voltages_CallInstance, cmock_guts_index);
  Mock.calc_cell_voltages_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_cell_voltages_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cell_voltages_CALL_INSTANCE));
  CMOCK_calc_cell_voltages_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cell_voltages_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cell_voltages_CallInstance = CMock_Guts_MemChain(Mock.calc_cell_voltages_CallInstance, cmock_guts_index);
  Mock.calc_cell_voltages_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_cell_voltages(cmock_call_instance, bmsdata);
}

void calc_cell_voltages_AddCallback(CMOCK_calc_cell_voltages_CALLBACK Callback)
{
  Mock.calc_cell_voltages_IgnoreBool = (char)0;
  Mock.calc_cell_voltages_CallbackBool = (char)1;
  Mock.calc_cell_voltages_CallbackFunctionPointer = Callback;
}

void calc_cell_voltages_Stub(CMOCK_calc_cell_voltages_CALLBACK Callback)
{
  Mock.calc_cell_voltages_IgnoreBool = (char)0;
  Mock.calc_cell_voltages_CallbackBool = (char)0;
  Mock.calc_cell_voltages_CallbackFunctionPointer = Callback;
}

void calc_cell_voltages_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_cell_voltages_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cell_voltages_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_cell_voltages_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

void calc_pack_voltage_stats(acc_data_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_pack_voltage_stats_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_pack_voltage_stats);
  cmock_call_instance = (CMOCK_calc_pack_voltage_stats_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_pack_voltage_stats_CallInstance);
  Mock.calc_pack_voltage_stats_CallInstance = CMock_Guts_MemNext(Mock.calc_pack_voltage_stats_CallInstance);
  if (Mock.calc_pack_voltage_stats_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.calc_pack_voltage_stats_CallbackBool &&
      Mock.calc_pack_voltage_stats_CallbackFunctionPointer != NULL)
  {
    Mock.calc_pack_voltage_stats_CallbackFunctionPointer(bmsdata, Mock.calc_pack_voltage_stats_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_calc_pack_voltage_stats,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(acc_data_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_pack_voltage_stats_CallbackFunctionPointer != NULL)
  {
    Mock.calc_pack_voltage_stats_CallbackFunctionPointer(bmsdata, Mock.calc_pack_voltage_stats_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_calc_pack_voltage_stats(CMOCK_calc_pack_voltage_stats_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata);
void CMockExpectParameters_calc_pack_voltage_stats(CMOCK_calc_pack_voltage_stats_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void calc_pack_voltage_stats_CMockIgnore(void)
{
  Mock.calc_pack_voltage_stats_IgnoreBool = (char)1;
}

void calc_pack_voltage_stats_CMockStopIgnore(void)
{
  Mock.calc_pack_voltage_stats_IgnoreBool = (char)0;
}

void calc_pack_voltage_stats_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_pack_voltage_stats_CALL_INSTANCE));
  CMOCK_calc_pack_voltage_stats_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_pack_voltage_stats_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_pack_voltage_stats_CallInstance = CMock_Guts_MemChain(Mock.calc_pack_voltage_stats_CallInstance, cmock_guts_index);
  Mock.calc_pack_voltage_stats_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_pack_voltage_stats_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_pack_voltage_stats_CALL_INSTANCE));
  CMOCK_calc_pack_voltage_stats_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_pack_voltage_stats_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_pack_voltage_stats_CallInstance = CMock_Guts_MemChain(Mock.calc_pack_voltage_stats_CallInstance, cmock_guts_index);
  Mock.calc_pack_voltage_stats_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_pack_voltage_stats(cmock_call_instance, bmsdata);
}

void calc_pack_voltage_stats_AddCallback(CMOCK_calc_pack_voltage_stats_CALLBACK Callback)
{
  Mock.calc_pack_voltage_stats_IgnoreBool = (char)0;
  Mock.calc_pack_voltage_stats_CallbackBool = (char)1;
  Mock.calc_pack_voltage_stats_CallbackFunctionPointer = Callback;
}

void calc_pack_voltage_stats_Stub(CMOCK_calc_pack_voltage_stats_CALLBACK Callback)
{
  Mock.calc_pack_voltage_stats_IgnoreBool = (char)0;
  Mock.calc_pack_voltage_stats_CallbackBool = (char)0;
  Mock.calc_pack_voltage_stats_CallbackFunctionPointer = Callback;
}

void calc_pack_voltage_stats_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_pack_voltage_stats_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_pack_voltage_stats_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_pack_voltage_stats_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

void calc_open_cell_voltage(acc_data_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_open_cell_voltage_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_open_cell_voltage);
  cmock_call_instance = (CMOCK_calc_open_cell_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_open_cell_voltage_CallInstance);
  Mock.calc_open_cell_voltage_CallInstance = CMock_Guts_MemNext(Mock.calc_open_cell_voltage_CallInstance);
  if (Mock.calc_open_cell_voltage_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.calc_open_cell_voltage_CallbackBool &&
      Mock.calc_open_cell_voltage_CallbackFunctionPointer != NULL)
  {
    Mock.calc_open_cell_voltage_CallbackFunctionPointer(bmsdata, Mock.calc_open_cell_voltage_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_calc_open_cell_voltage,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(acc_data_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_open_cell_voltage_CallbackFunctionPointer != NULL)
  {
    Mock.calc_open_cell_voltage_CallbackFunctionPointer(bmsdata, Mock.calc_open_cell_voltage_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_calc_open_cell_voltage(CMOCK_calc_open_cell_voltage_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata);
void CMockExpectParameters_calc_open_cell_voltage(CMOCK_calc_open_cell_voltage_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void calc_open_cell_voltage_CMockIgnore(void)
{
  Mock.calc_open_cell_voltage_IgnoreBool = (char)1;
}

void calc_open_cell_voltage_CMockStopIgnore(void)
{
  Mock.calc_open_cell_voltage_IgnoreBool = (char)0;
}

void calc_open_cell_voltage_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_open_cell_voltage_CALL_INSTANCE));
  CMOCK_calc_open_cell_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_open_cell_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_open_cell_voltage_CallInstance = CMock_Guts_MemChain(Mock.calc_open_cell_voltage_CallInstance, cmock_guts_index);
  Mock.calc_open_cell_voltage_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_open_cell_voltage_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_open_cell_voltage_CALL_INSTANCE));
  CMOCK_calc_open_cell_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_open_cell_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_open_cell_voltage_CallInstance = CMock_Guts_MemChain(Mock.calc_open_cell_voltage_CallInstance, cmock_guts_index);
  Mock.calc_open_cell_voltage_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_open_cell_voltage(cmock_call_instance, bmsdata);
}

void calc_open_cell_voltage_AddCallback(CMOCK_calc_open_cell_voltage_CALLBACK Callback)
{
  Mock.calc_open_cell_voltage_IgnoreBool = (char)0;
  Mock.calc_open_cell_voltage_CallbackBool = (char)1;
  Mock.calc_open_cell_voltage_CallbackFunctionPointer = Callback;
}

void calc_open_cell_voltage_Stub(CMOCK_calc_open_cell_voltage_CALLBACK Callback)
{
  Mock.calc_open_cell_voltage_IgnoreBool = (char)0;
  Mock.calc_open_cell_voltage_CallbackBool = (char)0;
  Mock.calc_open_cell_voltage_CallbackFunctionPointer = Callback;
}

void calc_open_cell_voltage_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_open_cell_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_open_cell_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_open_cell_voltage_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

void calc_cell_resistances(acc_data_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_cell_resistances_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_cell_resistances);
  cmock_call_instance = (CMOCK_calc_cell_resistances_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_cell_resistances_CallInstance);
  Mock.calc_cell_resistances_CallInstance = CMock_Guts_MemNext(Mock.calc_cell_resistances_CallInstance);
  if (Mock.calc_cell_resistances_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.calc_cell_resistances_CallbackBool &&
      Mock.calc_cell_resistances_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cell_resistances_CallbackFunctionPointer(bmsdata, Mock.calc_cell_resistances_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_calc_cell_resistances,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(acc_data_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_cell_resistances_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cell_resistances_CallbackFunctionPointer(bmsdata, Mock.calc_cell_resistances_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_calc_cell_resistances(CMOCK_calc_cell_resistances_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata);
void CMockExpectParameters_calc_cell_resistances(CMOCK_calc_cell_resistances_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void calc_cell_resistances_CMockIgnore(void)
{
  Mock.calc_cell_resistances_IgnoreBool = (char)1;
}

void calc_cell_resistances_CMockStopIgnore(void)
{
  Mock.calc_cell_resistances_IgnoreBool = (char)0;
}

void calc_cell_resistances_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cell_resistances_CALL_INSTANCE));
  CMOCK_calc_cell_resistances_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cell_resistances_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cell_resistances_CallInstance = CMock_Guts_MemChain(Mock.calc_cell_resistances_CallInstance, cmock_guts_index);
  Mock.calc_cell_resistances_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_cell_resistances_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cell_resistances_CALL_INSTANCE));
  CMOCK_calc_cell_resistances_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cell_resistances_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cell_resistances_CallInstance = CMock_Guts_MemChain(Mock.calc_cell_resistances_CallInstance, cmock_guts_index);
  Mock.calc_cell_resistances_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_cell_resistances(cmock_call_instance, bmsdata);
}

void calc_cell_resistances_AddCallback(CMOCK_calc_cell_resistances_CALLBACK Callback)
{
  Mock.calc_cell_resistances_IgnoreBool = (char)0;
  Mock.calc_cell_resistances_CallbackBool = (char)1;
  Mock.calc_cell_resistances_CallbackFunctionPointer = Callback;
}

void calc_cell_resistances_Stub(CMOCK_calc_cell_resistances_CALLBACK Callback)
{
  Mock.calc_cell_resistances_IgnoreBool = (char)0;
  Mock.calc_cell_resistances_CallbackBool = (char)0;
  Mock.calc_cell_resistances_CallbackFunctionPointer = Callback;
}

void calc_cell_resistances_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_cell_resistances_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cell_resistances_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_cell_resistances_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

void calc_cont_dcl(acc_data_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_cont_dcl_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_cont_dcl);
  cmock_call_instance = (CMOCK_calc_cont_dcl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_cont_dcl_CallInstance);
  Mock.calc_cont_dcl_CallInstance = CMock_Guts_MemNext(Mock.calc_cont_dcl_CallInstance);
  if (Mock.calc_cont_dcl_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.calc_cont_dcl_CallbackBool &&
      Mock.calc_cont_dcl_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cont_dcl_CallbackFunctionPointer(bmsdata, Mock.calc_cont_dcl_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_calc_cont_dcl,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(acc_data_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_cont_dcl_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cont_dcl_CallbackFunctionPointer(bmsdata, Mock.calc_cont_dcl_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_calc_cont_dcl(CMOCK_calc_cont_dcl_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata);
void CMockExpectParameters_calc_cont_dcl(CMOCK_calc_cont_dcl_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void calc_cont_dcl_CMockIgnore(void)
{
  Mock.calc_cont_dcl_IgnoreBool = (char)1;
}

void calc_cont_dcl_CMockStopIgnore(void)
{
  Mock.calc_cont_dcl_IgnoreBool = (char)0;
}

void calc_cont_dcl_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cont_dcl_CALL_INSTANCE));
  CMOCK_calc_cont_dcl_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cont_dcl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cont_dcl_CallInstance = CMock_Guts_MemChain(Mock.calc_cont_dcl_CallInstance, cmock_guts_index);
  Mock.calc_cont_dcl_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_cont_dcl_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cont_dcl_CALL_INSTANCE));
  CMOCK_calc_cont_dcl_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cont_dcl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cont_dcl_CallInstance = CMock_Guts_MemChain(Mock.calc_cont_dcl_CallInstance, cmock_guts_index);
  Mock.calc_cont_dcl_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_cont_dcl(cmock_call_instance, bmsdata);
}

void calc_cont_dcl_AddCallback(CMOCK_calc_cont_dcl_CALLBACK Callback)
{
  Mock.calc_cont_dcl_IgnoreBool = (char)0;
  Mock.calc_cont_dcl_CallbackBool = (char)1;
  Mock.calc_cont_dcl_CallbackFunctionPointer = Callback;
}

void calc_cont_dcl_Stub(CMOCK_calc_cont_dcl_CALLBACK Callback)
{
  Mock.calc_cont_dcl_IgnoreBool = (char)0;
  Mock.calc_cont_dcl_CallbackBool = (char)0;
  Mock.calc_cont_dcl_CallbackFunctionPointer = Callback;
}

void calc_cont_dcl_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_cont_dcl_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cont_dcl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_cont_dcl_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

void calc_cont_ccl(acc_data_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_cont_ccl_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_cont_ccl);
  cmock_call_instance = (CMOCK_calc_cont_ccl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_cont_ccl_CallInstance);
  Mock.calc_cont_ccl_CallInstance = CMock_Guts_MemNext(Mock.calc_cont_ccl_CallInstance);
  if (Mock.calc_cont_ccl_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.calc_cont_ccl_CallbackBool &&
      Mock.calc_cont_ccl_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cont_ccl_CallbackFunctionPointer(bmsdata, Mock.calc_cont_ccl_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_calc_cont_ccl,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(acc_data_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_cont_ccl_CallbackFunctionPointer != NULL)
  {
    Mock.calc_cont_ccl_CallbackFunctionPointer(bmsdata, Mock.calc_cont_ccl_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_calc_cont_ccl(CMOCK_calc_cont_ccl_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata);
void CMockExpectParameters_calc_cont_ccl(CMOCK_calc_cont_ccl_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void calc_cont_ccl_CMockIgnore(void)
{
  Mock.calc_cont_ccl_IgnoreBool = (char)1;
}

void calc_cont_ccl_CMockStopIgnore(void)
{
  Mock.calc_cont_ccl_IgnoreBool = (char)0;
}

void calc_cont_ccl_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cont_ccl_CALL_INSTANCE));
  CMOCK_calc_cont_ccl_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cont_ccl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cont_ccl_CallInstance = CMock_Guts_MemChain(Mock.calc_cont_ccl_CallInstance, cmock_guts_index);
  Mock.calc_cont_ccl_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_cont_ccl_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_cont_ccl_CALL_INSTANCE));
  CMOCK_calc_cont_ccl_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cont_ccl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_cont_ccl_CallInstance = CMock_Guts_MemChain(Mock.calc_cont_ccl_CallInstance, cmock_guts_index);
  Mock.calc_cont_ccl_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_cont_ccl(cmock_call_instance, bmsdata);
}

void calc_cont_ccl_AddCallback(CMOCK_calc_cont_ccl_CALLBACK Callback)
{
  Mock.calc_cont_ccl_IgnoreBool = (char)0;
  Mock.calc_cont_ccl_CallbackBool = (char)1;
  Mock.calc_cont_ccl_CallbackFunctionPointer = Callback;
}

void calc_cont_ccl_Stub(CMOCK_calc_cont_ccl_CALLBACK Callback)
{
  Mock.calc_cont_ccl_IgnoreBool = (char)0;
  Mock.calc_cont_ccl_CallbackBool = (char)0;
  Mock.calc_cont_ccl_CallbackFunctionPointer = Callback;
}

void calc_cont_ccl_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_cont_ccl_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_cont_ccl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_cont_ccl_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

void calc_state_of_charge(acc_data_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_calc_state_of_charge_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_calc_state_of_charge);
  cmock_call_instance = (CMOCK_calc_state_of_charge_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.calc_state_of_charge_CallInstance);
  Mock.calc_state_of_charge_CallInstance = CMock_Guts_MemNext(Mock.calc_state_of_charge_CallInstance);
  if (Mock.calc_state_of_charge_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.calc_state_of_charge_CallbackBool &&
      Mock.calc_state_of_charge_CallbackFunctionPointer != NULL)
  {
    Mock.calc_state_of_charge_CallbackFunctionPointer(bmsdata, Mock.calc_state_of_charge_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_calc_state_of_charge,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(acc_data_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.calc_state_of_charge_CallbackFunctionPointer != NULL)
  {
    Mock.calc_state_of_charge_CallbackFunctionPointer(bmsdata, Mock.calc_state_of_charge_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_calc_state_of_charge(CMOCK_calc_state_of_charge_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata);
void CMockExpectParameters_calc_state_of_charge(CMOCK_calc_state_of_charge_CALL_INSTANCE* cmock_call_instance, acc_data_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void calc_state_of_charge_CMockIgnore(void)
{
  Mock.calc_state_of_charge_IgnoreBool = (char)1;
}

void calc_state_of_charge_CMockStopIgnore(void)
{
  Mock.calc_state_of_charge_IgnoreBool = (char)0;
}

void calc_state_of_charge_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_state_of_charge_CALL_INSTANCE));
  CMOCK_calc_state_of_charge_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_state_of_charge_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_state_of_charge_CallInstance = CMock_Guts_MemChain(Mock.calc_state_of_charge_CallInstance, cmock_guts_index);
  Mock.calc_state_of_charge_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void calc_state_of_charge_CMockExpect(UNITY_LINE_TYPE cmock_line, acc_data_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_calc_state_of_charge_CALL_INSTANCE));
  CMOCK_calc_state_of_charge_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_state_of_charge_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.calc_state_of_charge_CallInstance = CMock_Guts_MemChain(Mock.calc_state_of_charge_CallInstance, cmock_guts_index);
  Mock.calc_state_of_charge_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_calc_state_of_charge(cmock_call_instance, bmsdata);
}

void calc_state_of_charge_AddCallback(CMOCK_calc_state_of_charge_CALLBACK Callback)
{
  Mock.calc_state_of_charge_IgnoreBool = (char)0;
  Mock.calc_state_of_charge_CallbackBool = (char)1;
  Mock.calc_state_of_charge_CallbackFunctionPointer = Callback;
}

void calc_state_of_charge_Stub(CMOCK_calc_state_of_charge_CALLBACK Callback)
{
  Mock.calc_state_of_charge_IgnoreBool = (char)0;
  Mock.calc_state_of_charge_CallbackBool = (char)0;
  Mock.calc_state_of_charge_CallbackFunctionPointer = Callback;
}

void calc_state_of_charge_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_calc_state_of_charge_CALL_INSTANCE* cmock_call_instance = (CMOCK_calc_state_of_charge_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.calc_state_of_charge_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

