name: Build
on: [push]
jobs:
  run-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: recursive
            token: ${{ secrets.PAT_TOKEN }}
            fetch-depth: 0
      - name: Execute Make
        run: |
            if ! docker compose run --rm ner-gcc-arm make -j `nproc`; then
            echo "The application has failed to build."
            exit 1  # This will cause the workflow to fail
            fi
