name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Clean and Build Project
      run: |
        docker compose run --rm ner-gcc-arm sh -c '
          cmake --build build --target clean ;
          find . -type d -name "build" -exec rm -rf {} + ;
          mkdir -p build &&
          cd build &&
          cmake -DCMAKE_BUILD_TYPE=Release .. &&
          cmake --build .
        '
