name: Unit Test Check

on: [push]

jobs:
  test-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: Run UNITY Testing files
        run: |
          docker compose run --rm --entrypoint python3 ner-gcc-arm \
            Drivers/Embedded-Base/ner_environment/build_system/test_runner.py
            