/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CAN_HANDLER_H
#define _MOCK_CAN_HANDLER_H

#include "unity.h"
#include "stubs.h"
#include "can_handler.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_can_handler_Init(void);
void mock_can_handler_Destroy(void);
void mock_can_handler_Verify(void);




#define can_receive_callback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("can_receive_callback requires _Ignore (not AndReturn)");
#define can_receive_callback_Ignore() can_receive_callback_CMockIgnore()
void can_receive_callback_CMockIgnore(void);
#define can_receive_callback_StopIgnore() can_receive_callback_CMockStopIgnore()
void can_receive_callback_CMockStopIgnore(void);
#define can_receive_callback_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("can_receive_callback requires _ExpectAnyArgs (not AndReturn)");
#define can_receive_callback_ExpectAnyArgs() can_receive_callback_CMockExpectAnyArgs(__LINE__)
void can_receive_callback_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define can_receive_callback_ExpectAndReturn(hcan, RxFifo0ITs, cmock_retval) TEST_FAIL_MESSAGE("can_receive_callback requires _Expect (not AndReturn)");
#define can_receive_callback_Expect(hcan, RxFifo0ITs) can_receive_callback_CMockExpect(__LINE__, hcan, RxFifo0ITs)
void can_receive_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, FDCAN_HandleTypeDef* hcan, uint32_t RxFifo0ITs);
typedef void (* CMOCK_can_receive_callback_CALLBACK)(FDCAN_HandleTypeDef* hcan, uint32_t RxFifo0ITs, int cmock_num_calls);
void can_receive_callback_AddCallback(CMOCK_can_receive_callback_CALLBACK Callback);
void can_receive_callback_Stub(CMOCK_can_receive_callback_CALLBACK Callback);
#define can_receive_callback_StubWithCallback can_receive_callback_Stub
#define can_receive_callback_IgnoreArg_hcan() can_receive_callback_CMockIgnoreArg_hcan(__LINE__)
void can_receive_callback_CMockIgnoreArg_hcan(UNITY_LINE_TYPE cmock_line);
#define can_receive_callback_IgnoreArg_RxFifo0ITs() can_receive_callback_CMockIgnoreArg_RxFifo0ITs(__LINE__)
void can_receive_callback_CMockIgnoreArg_RxFifo0ITs(UNITY_LINE_TYPE cmock_line);
#define queue_can_msg_Ignore() TEST_FAIL_MESSAGE("queue_can_msg requires _IgnoreAndReturn");
#define queue_can_msg_IgnoreAndReturn(cmock_retval) queue_can_msg_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void queue_can_msg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define queue_can_msg_StopIgnore() queue_can_msg_CMockStopIgnore()
void queue_can_msg_CMockStopIgnore(void);
#define queue_can_msg_ExpectAnyArgs() TEST_FAIL_MESSAGE("queue_can_msg requires _ExpectAnyArgsAndReturn");
#define queue_can_msg_ExpectAnyArgsAndReturn(cmock_retval) queue_can_msg_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void queue_can_msg_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define queue_can_msg_Expect(can_msg) TEST_FAIL_MESSAGE("queue_can_msg requires _ExpectAndReturn");
#define queue_can_msg_ExpectAndReturn(can_msg, cmock_retval) queue_can_msg_CMockExpectAndReturn(__LINE__, can_msg, cmock_retval)
void queue_can_msg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, can_msg_t can_msg, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_queue_can_msg_CALLBACK)(can_msg_t can_msg, int cmock_num_calls);
void queue_can_msg_AddCallback(CMOCK_queue_can_msg_CALLBACK Callback);
void queue_can_msg_Stub(CMOCK_queue_can_msg_CALLBACK Callback);
#define queue_can_msg_StubWithCallback queue_can_msg_Stub
#define queue_can_msg_IgnoreArg_can_msg() queue_can_msg_CMockIgnoreArg_can_msg(__LINE__)
void queue_can_msg_CMockIgnoreArg_can_msg(UNITY_LINE_TYPE cmock_line);
#define init_can_Ignore() TEST_FAIL_MESSAGE("init_can requires _IgnoreAndReturn");
#define init_can_IgnoreAndReturn(cmock_retval) init_can_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void init_can_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define init_can_StopIgnore() init_can_CMockStopIgnore()
void init_can_CMockStopIgnore(void);
#define init_can_ExpectAnyArgs() TEST_FAIL_MESSAGE("init_can requires _ExpectAnyArgsAndReturn");
#define init_can_ExpectAnyArgsAndReturn(cmock_retval) init_can_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void init_can_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define init_can_Expect(hcan) TEST_FAIL_MESSAGE("init_can requires _ExpectAndReturn");
#define init_can_ExpectAndReturn(hcan, cmock_retval) init_can_CMockExpectAndReturn(__LINE__, hcan, cmock_retval)
void init_can_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FDCAN_HandleTypeDef* hcan, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_init_can_CALLBACK)(FDCAN_HandleTypeDef* hcan, int cmock_num_calls);
void init_can_AddCallback(CMOCK_init_can_CALLBACK Callback);
void init_can_Stub(CMOCK_init_can_CALLBACK Callback);
#define init_can_StubWithCallback init_can_Stub
#define init_can_IgnoreArg_hcan() init_can_CMockIgnoreArg_hcan(__LINE__)
void init_can_CMockIgnoreArg_hcan(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
