/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_timer.h"

static const char* CMockString_cancel_timer = "cancel_timer";
static const char* CMockString_duration = "duration";
static const char* CMockString_is_timer_active = "is_timer_active";
static const char* CMockString_is_timer_expired = "is_timer_expired";
static const char* CMockString_start_timer = "start_timer";
static const char* CMockString_timer = "timer";

typedef struct _CMOCK_start_timer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  nertimer_t* Expected_timer;
  uint32_t Expected_duration;
  char IgnoreArg_timer;
  char IgnoreArg_duration;

} CMOCK_start_timer_CALL_INSTANCE;

typedef struct _CMOCK_cancel_timer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  nertimer_t* Expected_timer;
  char IgnoreArg_timer;

} CMOCK_cancel_timer_CALL_INSTANCE;

typedef struct _CMOCK_is_timer_expired_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  nertimer_t* Expected_timer;
  char IgnoreArg_timer;

} CMOCK_is_timer_expired_CALL_INSTANCE;

typedef struct _CMOCK_is_timer_active_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  nertimer_t* Expected_timer;
  char IgnoreArg_timer;

} CMOCK_is_timer_active_CALL_INSTANCE;

static struct mock_timerInstance
{
  char start_timer_IgnoreBool;
  char start_timer_CallbackBool;
  CMOCK_start_timer_CALLBACK start_timer_CallbackFunctionPointer;
  int start_timer_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE start_timer_CallInstance;
  char cancel_timer_IgnoreBool;
  char cancel_timer_CallbackBool;
  CMOCK_cancel_timer_CALLBACK cancel_timer_CallbackFunctionPointer;
  int cancel_timer_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cancel_timer_CallInstance;
  char is_timer_expired_IgnoreBool;
  bool is_timer_expired_FinalReturn;
  char is_timer_expired_CallbackBool;
  CMOCK_is_timer_expired_CALLBACK is_timer_expired_CallbackFunctionPointer;
  int is_timer_expired_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE is_timer_expired_CallInstance;
  char is_timer_active_IgnoreBool;
  bool is_timer_active_FinalReturn;
  char is_timer_active_CallbackBool;
  CMOCK_is_timer_active_CALLBACK is_timer_active_CallbackFunctionPointer;
  int is_timer_active_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE is_timer_active_CallInstance;
} Mock;


void mock_timer_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.start_timer_CallInstance;
  if (Mock.start_timer_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_start_timer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.start_timer_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.cancel_timer_CallInstance;
  if (Mock.cancel_timer_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_cancel_timer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.cancel_timer_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.is_timer_expired_CallInstance;
  if (Mock.is_timer_expired_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_is_timer_expired);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.is_timer_expired_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.is_timer_active_CallInstance;
  if (Mock.is_timer_active_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_is_timer_active);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.is_timer_active_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_timer_Init(void)
{
  mock_timer_Destroy();
}

void mock_timer_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void start_timer(nertimer_t* timer, uint32_t duration)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_start_timer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_start_timer);
  cmock_call_instance = (CMOCK_start_timer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.start_timer_CallInstance);
  Mock.start_timer_CallInstance = CMock_Guts_MemNext(Mock.start_timer_CallInstance);
  if (Mock.start_timer_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.start_timer_CallbackBool &&
      Mock.start_timer_CallbackFunctionPointer != NULL)
  {
    Mock.start_timer_CallbackFunctionPointer(timer, duration, Mock.start_timer_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_timer)
  {
    UNITY_SET_DETAILS(CMockString_start_timer,CMockString_timer);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_timer), (void*)(timer), sizeof(nertimer_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_duration)
  {
    UNITY_SET_DETAILS(CMockString_start_timer,CMockString_duration);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_duration, duration, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.start_timer_CallbackFunctionPointer != NULL)
  {
    Mock.start_timer_CallbackFunctionPointer(timer, duration, Mock.start_timer_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_start_timer(CMOCK_start_timer_CALL_INSTANCE* cmock_call_instance, nertimer_t* timer, uint32_t duration);
void CMockExpectParameters_start_timer(CMOCK_start_timer_CALL_INSTANCE* cmock_call_instance, nertimer_t* timer, uint32_t duration)
{
  cmock_call_instance->Expected_timer = timer;
  cmock_call_instance->IgnoreArg_timer = 0;
  cmock_call_instance->Expected_duration = duration;
  cmock_call_instance->IgnoreArg_duration = 0;
}

void start_timer_CMockIgnore(void)
{
  Mock.start_timer_IgnoreBool = (char)1;
}

void start_timer_CMockStopIgnore(void)
{
  Mock.start_timer_IgnoreBool = (char)0;
}

void start_timer_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_timer_CALL_INSTANCE));
  CMOCK_start_timer_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_timer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_timer_CallInstance = CMock_Guts_MemChain(Mock.start_timer_CallInstance, cmock_guts_index);
  Mock.start_timer_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void start_timer_CMockExpect(UNITY_LINE_TYPE cmock_line, nertimer_t* timer, uint32_t duration)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_timer_CALL_INSTANCE));
  CMOCK_start_timer_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_timer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_timer_CallInstance = CMock_Guts_MemChain(Mock.start_timer_CallInstance, cmock_guts_index);
  Mock.start_timer_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_start_timer(cmock_call_instance, timer, duration);
}

void start_timer_AddCallback(CMOCK_start_timer_CALLBACK Callback)
{
  Mock.start_timer_IgnoreBool = (char)0;
  Mock.start_timer_CallbackBool = (char)1;
  Mock.start_timer_CallbackFunctionPointer = Callback;
}

void start_timer_Stub(CMOCK_start_timer_CALLBACK Callback)
{
  Mock.start_timer_IgnoreBool = (char)0;
  Mock.start_timer_CallbackBool = (char)0;
  Mock.start_timer_CallbackFunctionPointer = Callback;
}

void start_timer_CMockIgnoreArg_timer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_timer_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_timer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_timer_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timer = 1;
}

void start_timer_CMockIgnoreArg_duration(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_timer_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_timer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_timer_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_duration = 1;
}

void cancel_timer(nertimer_t* timer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cancel_timer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_cancel_timer);
  cmock_call_instance = (CMOCK_cancel_timer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cancel_timer_CallInstance);
  Mock.cancel_timer_CallInstance = CMock_Guts_MemNext(Mock.cancel_timer_CallInstance);
  if (Mock.cancel_timer_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.cancel_timer_CallbackBool &&
      Mock.cancel_timer_CallbackFunctionPointer != NULL)
  {
    Mock.cancel_timer_CallbackFunctionPointer(timer, Mock.cancel_timer_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_timer)
  {
    UNITY_SET_DETAILS(CMockString_cancel_timer,CMockString_timer);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_timer), (void*)(timer), sizeof(nertimer_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.cancel_timer_CallbackFunctionPointer != NULL)
  {
    Mock.cancel_timer_CallbackFunctionPointer(timer, Mock.cancel_timer_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_cancel_timer(CMOCK_cancel_timer_CALL_INSTANCE* cmock_call_instance, nertimer_t* timer);
void CMockExpectParameters_cancel_timer(CMOCK_cancel_timer_CALL_INSTANCE* cmock_call_instance, nertimer_t* timer)
{
  cmock_call_instance->Expected_timer = timer;
  cmock_call_instance->IgnoreArg_timer = 0;
}

void cancel_timer_CMockIgnore(void)
{
  Mock.cancel_timer_IgnoreBool = (char)1;
}

void cancel_timer_CMockStopIgnore(void)
{
  Mock.cancel_timer_IgnoreBool = (char)0;
}

void cancel_timer_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cancel_timer_CALL_INSTANCE));
  CMOCK_cancel_timer_CALL_INSTANCE* cmock_call_instance = (CMOCK_cancel_timer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cancel_timer_CallInstance = CMock_Guts_MemChain(Mock.cancel_timer_CallInstance, cmock_guts_index);
  Mock.cancel_timer_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void cancel_timer_CMockExpect(UNITY_LINE_TYPE cmock_line, nertimer_t* timer)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cancel_timer_CALL_INSTANCE));
  CMOCK_cancel_timer_CALL_INSTANCE* cmock_call_instance = (CMOCK_cancel_timer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cancel_timer_CallInstance = CMock_Guts_MemChain(Mock.cancel_timer_CallInstance, cmock_guts_index);
  Mock.cancel_timer_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_cancel_timer(cmock_call_instance, timer);
}

void cancel_timer_AddCallback(CMOCK_cancel_timer_CALLBACK Callback)
{
  Mock.cancel_timer_IgnoreBool = (char)0;
  Mock.cancel_timer_CallbackBool = (char)1;
  Mock.cancel_timer_CallbackFunctionPointer = Callback;
}

void cancel_timer_Stub(CMOCK_cancel_timer_CALLBACK Callback)
{
  Mock.cancel_timer_IgnoreBool = (char)0;
  Mock.cancel_timer_CallbackBool = (char)0;
  Mock.cancel_timer_CallbackFunctionPointer = Callback;
}

void cancel_timer_CMockIgnoreArg_timer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cancel_timer_CALL_INSTANCE* cmock_call_instance = (CMOCK_cancel_timer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cancel_timer_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timer = 1;
}

bool is_timer_expired(nertimer_t* timer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_is_timer_expired_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_is_timer_expired);
  cmock_call_instance = (CMOCK_is_timer_expired_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.is_timer_expired_CallInstance);
  Mock.is_timer_expired_CallInstance = CMock_Guts_MemNext(Mock.is_timer_expired_CallInstance);
  if (Mock.is_timer_expired_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.is_timer_expired_FinalReturn;
    Mock.is_timer_expired_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.is_timer_expired_CallbackBool &&
      Mock.is_timer_expired_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.is_timer_expired_CallbackFunctionPointer(timer, Mock.is_timer_expired_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_timer)
  {
    UNITY_SET_DETAILS(CMockString_is_timer_expired,CMockString_timer);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_timer), (void*)(timer), sizeof(nertimer_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.is_timer_expired_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.is_timer_expired_CallbackFunctionPointer(timer, Mock.is_timer_expired_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_is_timer_expired(CMOCK_is_timer_expired_CALL_INSTANCE* cmock_call_instance, nertimer_t* timer);
void CMockExpectParameters_is_timer_expired(CMOCK_is_timer_expired_CALL_INSTANCE* cmock_call_instance, nertimer_t* timer)
{
  cmock_call_instance->Expected_timer = timer;
  cmock_call_instance->IgnoreArg_timer = 0;
}

void is_timer_expired_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_is_timer_expired_CALL_INSTANCE));
  CMOCK_is_timer_expired_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_timer_expired_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.is_timer_expired_CallInstance = CMock_Guts_MemChain(Mock.is_timer_expired_CallInstance, cmock_guts_index);
  Mock.is_timer_expired_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.is_timer_expired_IgnoreBool = (char)1;
}

void is_timer_expired_CMockStopIgnore(void)
{
  if(Mock.is_timer_expired_IgnoreBool)
    Mock.is_timer_expired_CallInstance = CMock_Guts_MemNext(Mock.is_timer_expired_CallInstance);
  Mock.is_timer_expired_IgnoreBool = (char)0;
}

void is_timer_expired_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_is_timer_expired_CALL_INSTANCE));
  CMOCK_is_timer_expired_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_timer_expired_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.is_timer_expired_CallInstance = CMock_Guts_MemChain(Mock.is_timer_expired_CallInstance, cmock_guts_index);
  Mock.is_timer_expired_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void is_timer_expired_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, nertimer_t* timer, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_is_timer_expired_CALL_INSTANCE));
  CMOCK_is_timer_expired_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_timer_expired_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.is_timer_expired_CallInstance = CMock_Guts_MemChain(Mock.is_timer_expired_CallInstance, cmock_guts_index);
  Mock.is_timer_expired_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_is_timer_expired(cmock_call_instance, timer);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void is_timer_expired_AddCallback(CMOCK_is_timer_expired_CALLBACK Callback)
{
  Mock.is_timer_expired_IgnoreBool = (char)0;
  Mock.is_timer_expired_CallbackBool = (char)1;
  Mock.is_timer_expired_CallbackFunctionPointer = Callback;
}

void is_timer_expired_Stub(CMOCK_is_timer_expired_CALLBACK Callback)
{
  Mock.is_timer_expired_IgnoreBool = (char)0;
  Mock.is_timer_expired_CallbackBool = (char)0;
  Mock.is_timer_expired_CallbackFunctionPointer = Callback;
}

void is_timer_expired_CMockIgnoreArg_timer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_is_timer_expired_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_timer_expired_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.is_timer_expired_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timer = 1;
}

bool is_timer_active(nertimer_t* timer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_is_timer_active_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_is_timer_active);
  cmock_call_instance = (CMOCK_is_timer_active_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.is_timer_active_CallInstance);
  Mock.is_timer_active_CallInstance = CMock_Guts_MemNext(Mock.is_timer_active_CallInstance);
  if (Mock.is_timer_active_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.is_timer_active_FinalReturn;
    Mock.is_timer_active_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.is_timer_active_CallbackBool &&
      Mock.is_timer_active_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.is_timer_active_CallbackFunctionPointer(timer, Mock.is_timer_active_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_timer)
  {
    UNITY_SET_DETAILS(CMockString_is_timer_active,CMockString_timer);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_timer), (void*)(timer), sizeof(nertimer_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.is_timer_active_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.is_timer_active_CallbackFunctionPointer(timer, Mock.is_timer_active_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_is_timer_active(CMOCK_is_timer_active_CALL_INSTANCE* cmock_call_instance, nertimer_t* timer);
void CMockExpectParameters_is_timer_active(CMOCK_is_timer_active_CALL_INSTANCE* cmock_call_instance, nertimer_t* timer)
{
  cmock_call_instance->Expected_timer = timer;
  cmock_call_instance->IgnoreArg_timer = 0;
}

void is_timer_active_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_is_timer_active_CALL_INSTANCE));
  CMOCK_is_timer_active_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_timer_active_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.is_timer_active_CallInstance = CMock_Guts_MemChain(Mock.is_timer_active_CallInstance, cmock_guts_index);
  Mock.is_timer_active_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.is_timer_active_IgnoreBool = (char)1;
}

void is_timer_active_CMockStopIgnore(void)
{
  if(Mock.is_timer_active_IgnoreBool)
    Mock.is_timer_active_CallInstance = CMock_Guts_MemNext(Mock.is_timer_active_CallInstance);
  Mock.is_timer_active_IgnoreBool = (char)0;
}

void is_timer_active_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_is_timer_active_CALL_INSTANCE));
  CMOCK_is_timer_active_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_timer_active_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.is_timer_active_CallInstance = CMock_Guts_MemChain(Mock.is_timer_active_CallInstance, cmock_guts_index);
  Mock.is_timer_active_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void is_timer_active_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, nertimer_t* timer, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_is_timer_active_CALL_INSTANCE));
  CMOCK_is_timer_active_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_timer_active_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.is_timer_active_CallInstance = CMock_Guts_MemChain(Mock.is_timer_active_CallInstance, cmock_guts_index);
  Mock.is_timer_active_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_is_timer_active(cmock_call_instance, timer);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void is_timer_active_AddCallback(CMOCK_is_timer_active_CALLBACK Callback)
{
  Mock.is_timer_active_IgnoreBool = (char)0;
  Mock.is_timer_active_CallbackBool = (char)1;
  Mock.is_timer_active_CallbackFunctionPointer = Callback;
}

void is_timer_active_Stub(CMOCK_is_timer_active_CALLBACK Callback)
{
  Mock.is_timer_active_IgnoreBool = (char)0;
  Mock.is_timer_active_CallbackBool = (char)0;
  Mock.is_timer_active_CallbackFunctionPointer = Callback;
}

void is_timer_active_CMockIgnoreArg_timer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_is_timer_active_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_timer_active_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.is_timer_active_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timer = 1;
}

