/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_can_handler.h"

static const char* CMockString_RxFifo0ITs = "RxFifo0ITs";
static const char* CMockString_can_msg = "can_msg";
static const char* CMockString_can_receive_callback = "can_receive_callback";
static const char* CMockString_hcan = "hcan";
static const char* CMockString_init_can = "init_can";
static const char* CMockString_queue_can_msg = "queue_can_msg";

typedef struct _CMOCK_can_receive_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  FDCAN_HandleTypeDef* Expected_hcan;
  uint32_t Expected_RxFifo0ITs;
  char IgnoreArg_hcan;
  char IgnoreArg_RxFifo0ITs;

} CMOCK_can_receive_callback_CALL_INSTANCE;

typedef struct _CMOCK_queue_can_msg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  can_msg_t Expected_can_msg;
  char IgnoreArg_can_msg;

} CMOCK_queue_can_msg_CALL_INSTANCE;

typedef struct _CMOCK_init_can_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  FDCAN_HandleTypeDef* Expected_hcan;
  char IgnoreArg_hcan;

} CMOCK_init_can_CALL_INSTANCE;

static struct mock_can_handlerInstance
{
  char can_receive_callback_IgnoreBool;
  char can_receive_callback_CallbackBool;
  CMOCK_can_receive_callback_CALLBACK can_receive_callback_CallbackFunctionPointer;
  int can_receive_callback_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE can_receive_callback_CallInstance;
  char queue_can_msg_IgnoreBool;
  uint8_t queue_can_msg_FinalReturn;
  char queue_can_msg_CallbackBool;
  CMOCK_queue_can_msg_CALLBACK queue_can_msg_CallbackFunctionPointer;
  int queue_can_msg_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE queue_can_msg_CallInstance;
  char init_can_IgnoreBool;
  uint8_t init_can_FinalReturn;
  char init_can_CallbackBool;
  CMOCK_init_can_CALLBACK init_can_CallbackFunctionPointer;
  int init_can_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE init_can_CallInstance;
} Mock;


void mock_can_handler_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.can_receive_callback_CallInstance;
  if (Mock.can_receive_callback_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_can_receive_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.can_receive_callback_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.queue_can_msg_CallInstance;
  if (Mock.queue_can_msg_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_queue_can_msg);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.queue_can_msg_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.init_can_CallInstance;
  if (Mock.init_can_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_init_can);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.init_can_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_can_handler_Init(void)
{
  mock_can_handler_Destroy();
}

void mock_can_handler_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void can_receive_callback(FDCAN_HandleTypeDef* hcan, uint32_t RxFifo0ITs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_can_receive_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_can_receive_callback);
  cmock_call_instance = (CMOCK_can_receive_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.can_receive_callback_CallInstance);
  Mock.can_receive_callback_CallInstance = CMock_Guts_MemNext(Mock.can_receive_callback_CallInstance);
  if (Mock.can_receive_callback_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.can_receive_callback_CallbackBool &&
      Mock.can_receive_callback_CallbackFunctionPointer != NULL)
  {
    Mock.can_receive_callback_CallbackFunctionPointer(hcan, RxFifo0ITs, Mock.can_receive_callback_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_hcan)
  {
    UNITY_SET_DETAILS(CMockString_can_receive_callback,CMockString_hcan);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hcan), (void*)(hcan), sizeof(FDCAN_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_RxFifo0ITs)
  {
    UNITY_SET_DETAILS(CMockString_can_receive_callback,CMockString_RxFifo0ITs);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_RxFifo0ITs, RxFifo0ITs, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.can_receive_callback_CallbackFunctionPointer != NULL)
  {
    Mock.can_receive_callback_CallbackFunctionPointer(hcan, RxFifo0ITs, Mock.can_receive_callback_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_can_receive_callback(CMOCK_can_receive_callback_CALL_INSTANCE* cmock_call_instance, FDCAN_HandleTypeDef* hcan, uint32_t RxFifo0ITs);
void CMockExpectParameters_can_receive_callback(CMOCK_can_receive_callback_CALL_INSTANCE* cmock_call_instance, FDCAN_HandleTypeDef* hcan, uint32_t RxFifo0ITs)
{
  cmock_call_instance->Expected_hcan = hcan;
  cmock_call_instance->IgnoreArg_hcan = 0;
  cmock_call_instance->Expected_RxFifo0ITs = RxFifo0ITs;
  cmock_call_instance->IgnoreArg_RxFifo0ITs = 0;
}

void can_receive_callback_CMockIgnore(void)
{
  Mock.can_receive_callback_IgnoreBool = (char)1;
}

void can_receive_callback_CMockStopIgnore(void)
{
  Mock.can_receive_callback_IgnoreBool = (char)0;
}

void can_receive_callback_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_receive_callback_CALL_INSTANCE));
  CMOCK_can_receive_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_receive_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.can_receive_callback_CallInstance = CMock_Guts_MemChain(Mock.can_receive_callback_CallInstance, cmock_guts_index);
  Mock.can_receive_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void can_receive_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, FDCAN_HandleTypeDef* hcan, uint32_t RxFifo0ITs)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_receive_callback_CALL_INSTANCE));
  CMOCK_can_receive_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_receive_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.can_receive_callback_CallInstance = CMock_Guts_MemChain(Mock.can_receive_callback_CallInstance, cmock_guts_index);
  Mock.can_receive_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_can_receive_callback(cmock_call_instance, hcan, RxFifo0ITs);
}

void can_receive_callback_AddCallback(CMOCK_can_receive_callback_CALLBACK Callback)
{
  Mock.can_receive_callback_IgnoreBool = (char)0;
  Mock.can_receive_callback_CallbackBool = (char)1;
  Mock.can_receive_callback_CallbackFunctionPointer = Callback;
}

void can_receive_callback_Stub(CMOCK_can_receive_callback_CALLBACK Callback)
{
  Mock.can_receive_callback_IgnoreBool = (char)0;
  Mock.can_receive_callback_CallbackBool = (char)0;
  Mock.can_receive_callback_CallbackFunctionPointer = Callback;
}

void can_receive_callback_CMockIgnoreArg_hcan(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_can_receive_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_receive_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.can_receive_callback_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_hcan = 1;
}

void can_receive_callback_CMockIgnoreArg_RxFifo0ITs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_can_receive_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_receive_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.can_receive_callback_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_RxFifo0ITs = 1;
}

uint8_t queue_can_msg(can_msg_t can_msg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_queue_can_msg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_queue_can_msg);
  cmock_call_instance = (CMOCK_queue_can_msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.queue_can_msg_CallInstance);
  Mock.queue_can_msg_CallInstance = CMock_Guts_MemNext(Mock.queue_can_msg_CallInstance);
  if (Mock.queue_can_msg_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.queue_can_msg_FinalReturn;
    Mock.queue_can_msg_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.queue_can_msg_CallbackBool &&
      Mock.queue_can_msg_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.queue_can_msg_CallbackFunctionPointer(can_msg, Mock.queue_can_msg_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_can_msg)
  {
    UNITY_SET_DETAILS(CMockString_queue_can_msg,CMockString_can_msg);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_can_msg), (void*)(&can_msg), sizeof(can_msg_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.queue_can_msg_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.queue_can_msg_CallbackFunctionPointer(can_msg, Mock.queue_can_msg_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_queue_can_msg(CMOCK_queue_can_msg_CALL_INSTANCE* cmock_call_instance, can_msg_t can_msg);
void CMockExpectParameters_queue_can_msg(CMOCK_queue_can_msg_CALL_INSTANCE* cmock_call_instance, can_msg_t can_msg)
{
  memcpy((void*)(&cmock_call_instance->Expected_can_msg), (void*)(&can_msg),
         sizeof(can_msg_t[sizeof(can_msg) == sizeof(can_msg_t) ? 1 : -1])); /* add can_msg_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_can_msg = 0;
}

void queue_can_msg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_queue_can_msg_CALL_INSTANCE));
  CMOCK_queue_can_msg_CALL_INSTANCE* cmock_call_instance = (CMOCK_queue_can_msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.queue_can_msg_CallInstance = CMock_Guts_MemChain(Mock.queue_can_msg_CallInstance, cmock_guts_index);
  Mock.queue_can_msg_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.queue_can_msg_IgnoreBool = (char)1;
}

void queue_can_msg_CMockStopIgnore(void)
{
  if(Mock.queue_can_msg_IgnoreBool)
    Mock.queue_can_msg_CallInstance = CMock_Guts_MemNext(Mock.queue_can_msg_CallInstance);
  Mock.queue_can_msg_IgnoreBool = (char)0;
}

void queue_can_msg_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_queue_can_msg_CALL_INSTANCE));
  CMOCK_queue_can_msg_CALL_INSTANCE* cmock_call_instance = (CMOCK_queue_can_msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.queue_can_msg_CallInstance = CMock_Guts_MemChain(Mock.queue_can_msg_CallInstance, cmock_guts_index);
  Mock.queue_can_msg_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void queue_can_msg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, can_msg_t can_msg, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_queue_can_msg_CALL_INSTANCE));
  CMOCK_queue_can_msg_CALL_INSTANCE* cmock_call_instance = (CMOCK_queue_can_msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.queue_can_msg_CallInstance = CMock_Guts_MemChain(Mock.queue_can_msg_CallInstance, cmock_guts_index);
  Mock.queue_can_msg_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_queue_can_msg(cmock_call_instance, can_msg);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void queue_can_msg_AddCallback(CMOCK_queue_can_msg_CALLBACK Callback)
{
  Mock.queue_can_msg_IgnoreBool = (char)0;
  Mock.queue_can_msg_CallbackBool = (char)1;
  Mock.queue_can_msg_CallbackFunctionPointer = Callback;
}

void queue_can_msg_Stub(CMOCK_queue_can_msg_CALLBACK Callback)
{
  Mock.queue_can_msg_IgnoreBool = (char)0;
  Mock.queue_can_msg_CallbackBool = (char)0;
  Mock.queue_can_msg_CallbackFunctionPointer = Callback;
}

void queue_can_msg_CMockIgnoreArg_can_msg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_queue_can_msg_CALL_INSTANCE* cmock_call_instance = (CMOCK_queue_can_msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.queue_can_msg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_can_msg = 1;
}

uint8_t init_can(FDCAN_HandleTypeDef* hcan)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_init_can_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_init_can);
  cmock_call_instance = (CMOCK_init_can_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.init_can_CallInstance);
  Mock.init_can_CallInstance = CMock_Guts_MemNext(Mock.init_can_CallInstance);
  if (Mock.init_can_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.init_can_FinalReturn;
    Mock.init_can_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.init_can_CallbackBool &&
      Mock.init_can_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.init_can_CallbackFunctionPointer(hcan, Mock.init_can_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_hcan)
  {
    UNITY_SET_DETAILS(CMockString_init_can,CMockString_hcan);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hcan), (void*)(hcan), sizeof(FDCAN_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.init_can_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.init_can_CallbackFunctionPointer(hcan, Mock.init_can_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_init_can(CMOCK_init_can_CALL_INSTANCE* cmock_call_instance, FDCAN_HandleTypeDef* hcan);
void CMockExpectParameters_init_can(CMOCK_init_can_CALL_INSTANCE* cmock_call_instance, FDCAN_HandleTypeDef* hcan)
{
  cmock_call_instance->Expected_hcan = hcan;
  cmock_call_instance->IgnoreArg_hcan = 0;
}

void init_can_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_init_can_CALL_INSTANCE));
  CMOCK_init_can_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_can_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.init_can_CallInstance = CMock_Guts_MemChain(Mock.init_can_CallInstance, cmock_guts_index);
  Mock.init_can_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.init_can_IgnoreBool = (char)1;
}

void init_can_CMockStopIgnore(void)
{
  if(Mock.init_can_IgnoreBool)
    Mock.init_can_CallInstance = CMock_Guts_MemNext(Mock.init_can_CallInstance);
  Mock.init_can_IgnoreBool = (char)0;
}

void init_can_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_init_can_CALL_INSTANCE));
  CMOCK_init_can_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_can_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.init_can_CallInstance = CMock_Guts_MemChain(Mock.init_can_CallInstance, cmock_guts_index);
  Mock.init_can_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void init_can_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FDCAN_HandleTypeDef* hcan, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_init_can_CALL_INSTANCE));
  CMOCK_init_can_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_can_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.init_can_CallInstance = CMock_Guts_MemChain(Mock.init_can_CallInstance, cmock_guts_index);
  Mock.init_can_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_init_can(cmock_call_instance, hcan);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void init_can_AddCallback(CMOCK_init_can_CALLBACK Callback)
{
  Mock.init_can_IgnoreBool = (char)0;
  Mock.init_can_CallbackBool = (char)1;
  Mock.init_can_CallbackFunctionPointer = Callback;
}

void init_can_Stub(CMOCK_init_can_CALLBACK Callback)
{
  Mock.init_can_IgnoreBool = (char)0;
  Mock.init_can_CallbackBool = (char)0;
  Mock.init_can_CallbackFunctionPointer = Callback;
}

void init_can_CMockIgnoreArg_hcan(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_init_can_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_can_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.init_can_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_hcan = 1;
}

