/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STUBS_H
#define _MOCK_STUBS_H

#include "unity.h"
#include "stubs.h"
#include "stubs.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_stubs_Init(void);
void mock_stubs_Destroy(void);
void mock_stubs_Verify(void);




#define HAL_GetTick_Ignore() TEST_FAIL_MESSAGE("HAL_GetTick requires _IgnoreAndReturn");
#define HAL_GetTick_IgnoreAndReturn(cmock_retval) HAL_GetTick_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_GetTick_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define HAL_GetTick_StopIgnore() HAL_GetTick_CMockStopIgnore()
void HAL_GetTick_CMockStopIgnore(void);
#define HAL_GetTick_Expect() TEST_FAIL_MESSAGE("HAL_GetTick requires _ExpectAndReturn");
#define HAL_GetTick_ExpectAndReturn(cmock_retval) HAL_GetTick_CMockExpectAndReturn(__LINE__, cmock_retval)
void HAL_GetTick_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_HAL_GetTick_CALLBACK)(int cmock_num_calls);
void HAL_GetTick_AddCallback(CMOCK_HAL_GetTick_CALLBACK Callback);
void HAL_GetTick_Stub(CMOCK_HAL_GetTick_CALLBACK Callback);
#define HAL_GetTick_StubWithCallback HAL_GetTick_Stub
#define osMutexNew_Ignore() TEST_FAIL_MESSAGE("osMutexNew requires _IgnoreAndReturn");
#define osMutexNew_IgnoreAndReturn(cmock_retval) osMutexNew_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osMutexNew_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t cmock_to_return);
#define osMutexNew_StopIgnore() osMutexNew_CMockStopIgnore()
void osMutexNew_CMockStopIgnore(void);
#define osMutexNew_ExpectAnyArgs() TEST_FAIL_MESSAGE("osMutexNew requires _ExpectAnyArgsAndReturn");
#define osMutexNew_ExpectAnyArgsAndReturn(cmock_retval) osMutexNew_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osMutexNew_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t cmock_to_return);
#define osMutexNew_Expect(attr) TEST_FAIL_MESSAGE("osMutexNew requires _ExpectAndReturn");
#define osMutexNew_ExpectAndReturn(attr, cmock_retval) osMutexNew_CMockExpectAndReturn(__LINE__, attr, cmock_retval)
void osMutexNew_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const osMutexAttr_t* attr, osMutexId_t cmock_to_return);
typedef osMutexId_t (* CMOCK_osMutexNew_CALLBACK)(const osMutexAttr_t* attr, int cmock_num_calls);
void osMutexNew_AddCallback(CMOCK_osMutexNew_CALLBACK Callback);
void osMutexNew_Stub(CMOCK_osMutexNew_CALLBACK Callback);
#define osMutexNew_StubWithCallback osMutexNew_Stub
#define osMutexNew_IgnoreArg_attr() osMutexNew_CMockIgnoreArg_attr(__LINE__)
void osMutexNew_CMockIgnoreArg_attr(UNITY_LINE_TYPE cmock_line);
#define osMutexAcquire_Ignore() TEST_FAIL_MESSAGE("osMutexAcquire requires _IgnoreAndReturn");
#define osMutexAcquire_IgnoreAndReturn(cmock_retval) osMutexAcquire_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osMutexAcquire_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osMutexAcquire_StopIgnore() osMutexAcquire_CMockStopIgnore()
void osMutexAcquire_CMockStopIgnore(void);
#define osMutexAcquire_ExpectAnyArgs() TEST_FAIL_MESSAGE("osMutexAcquire requires _ExpectAnyArgsAndReturn");
#define osMutexAcquire_ExpectAnyArgsAndReturn(cmock_retval) osMutexAcquire_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osMutexAcquire_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osMutexAcquire_Expect(mutex, timeout) TEST_FAIL_MESSAGE("osMutexAcquire requires _ExpectAndReturn");
#define osMutexAcquire_ExpectAndReturn(mutex, timeout, cmock_retval) osMutexAcquire_CMockExpectAndReturn(__LINE__, mutex, timeout, cmock_retval)
void osMutexAcquire_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t mutex, uint32_t timeout, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_osMutexAcquire_CALLBACK)(osMutexId_t mutex, uint32_t timeout, int cmock_num_calls);
void osMutexAcquire_AddCallback(CMOCK_osMutexAcquire_CALLBACK Callback);
void osMutexAcquire_Stub(CMOCK_osMutexAcquire_CALLBACK Callback);
#define osMutexAcquire_StubWithCallback osMutexAcquire_Stub
#define osMutexAcquire_IgnoreArg_mutex() osMutexAcquire_CMockIgnoreArg_mutex(__LINE__)
void osMutexAcquire_CMockIgnoreArg_mutex(UNITY_LINE_TYPE cmock_line);
#define osMutexAcquire_IgnoreArg_timeout() osMutexAcquire_CMockIgnoreArg_timeout(__LINE__)
void osMutexAcquire_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define osMutexRelease_Ignore() TEST_FAIL_MESSAGE("osMutexRelease requires _IgnoreAndReturn");
#define osMutexRelease_IgnoreAndReturn(cmock_retval) osMutexRelease_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osMutexRelease_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osMutexRelease_StopIgnore() osMutexRelease_CMockStopIgnore()
void osMutexRelease_CMockStopIgnore(void);
#define osMutexRelease_ExpectAnyArgs() TEST_FAIL_MESSAGE("osMutexRelease requires _ExpectAnyArgsAndReturn");
#define osMutexRelease_ExpectAnyArgsAndReturn(cmock_retval) osMutexRelease_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osMutexRelease_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osMutexRelease_Expect(mutex) TEST_FAIL_MESSAGE("osMutexRelease requires _ExpectAndReturn");
#define osMutexRelease_ExpectAndReturn(mutex, cmock_retval) osMutexRelease_CMockExpectAndReturn(__LINE__, mutex, cmock_retval)
void osMutexRelease_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t mutex, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_osMutexRelease_CALLBACK)(osMutexId_t mutex, int cmock_num_calls);
void osMutexRelease_AddCallback(CMOCK_osMutexRelease_CALLBACK Callback);
void osMutexRelease_Stub(CMOCK_osMutexRelease_CALLBACK Callback);
#define osMutexRelease_StubWithCallback osMutexRelease_Stub
#define osMutexRelease_IgnoreArg_mutex() osMutexRelease_CMockIgnoreArg_mutex(__LINE__)
void osMutexRelease_CMockIgnoreArg_mutex(UNITY_LINE_TYPE cmock_line);
#define osTimerNew_Ignore() TEST_FAIL_MESSAGE("osTimerNew requires _IgnoreAndReturn");
#define osTimerNew_IgnoreAndReturn(cmock_retval) osTimerNew_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osTimerNew_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osTimerId_t cmock_to_return);
#define osTimerNew_StopIgnore() osTimerNew_CMockStopIgnore()
void osTimerNew_CMockStopIgnore(void);
#define osTimerNew_ExpectAnyArgs() TEST_FAIL_MESSAGE("osTimerNew requires _ExpectAnyArgsAndReturn");
#define osTimerNew_ExpectAnyArgsAndReturn(cmock_retval) osTimerNew_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osTimerNew_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osTimerId_t cmock_to_return);
#define osTimerNew_Expect(func, type, arg, attr) TEST_FAIL_MESSAGE("osTimerNew requires _ExpectAndReturn");
#define osTimerNew_ExpectAndReturn(func, type, arg, attr, cmock_retval) osTimerNew_CMockExpectAndReturn(__LINE__, func, type, arg, attr, cmock_retval)
void osTimerNew_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osTimerFunc_t func, uint32_t type, void* arg, void* attr, osTimerId_t cmock_to_return);
typedef osTimerId_t (* CMOCK_osTimerNew_CALLBACK)(osTimerFunc_t func, uint32_t type, void* arg, void* attr, int cmock_num_calls);
void osTimerNew_AddCallback(CMOCK_osTimerNew_CALLBACK Callback);
void osTimerNew_Stub(CMOCK_osTimerNew_CALLBACK Callback);
#define osTimerNew_StubWithCallback osTimerNew_Stub
#define osTimerNew_IgnoreArg_func() osTimerNew_CMockIgnoreArg_func(__LINE__)
void osTimerNew_CMockIgnoreArg_func(UNITY_LINE_TYPE cmock_line);
#define osTimerNew_IgnoreArg_type() osTimerNew_CMockIgnoreArg_type(__LINE__)
void osTimerNew_CMockIgnoreArg_type(UNITY_LINE_TYPE cmock_line);
#define osTimerNew_IgnoreArg_arg() osTimerNew_CMockIgnoreArg_arg(__LINE__)
void osTimerNew_CMockIgnoreArg_arg(UNITY_LINE_TYPE cmock_line);
#define osTimerNew_IgnoreArg_attr() osTimerNew_CMockIgnoreArg_attr(__LINE__)
void osTimerNew_CMockIgnoreArg_attr(UNITY_LINE_TYPE cmock_line);
#define osTimerStart_Ignore() TEST_FAIL_MESSAGE("osTimerStart requires _IgnoreAndReturn");
#define osTimerStart_IgnoreAndReturn(cmock_retval) osTimerStart_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osTimerStart_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osTimerStart_StopIgnore() osTimerStart_CMockStopIgnore()
void osTimerStart_CMockStopIgnore(void);
#define osTimerStart_ExpectAnyArgs() TEST_FAIL_MESSAGE("osTimerStart requires _ExpectAnyArgsAndReturn");
#define osTimerStart_ExpectAnyArgsAndReturn(cmock_retval) osTimerStart_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osTimerStart_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osTimerStart_Expect(timer_id, ticks) TEST_FAIL_MESSAGE("osTimerStart requires _ExpectAndReturn");
#define osTimerStart_ExpectAndReturn(timer_id, ticks, cmock_retval) osTimerStart_CMockExpectAndReturn(__LINE__, timer_id, ticks, cmock_retval)
void osTimerStart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osTimerId_t timer_id, uint32_t ticks, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_osTimerStart_CALLBACK)(osTimerId_t timer_id, uint32_t ticks, int cmock_num_calls);
void osTimerStart_AddCallback(CMOCK_osTimerStart_CALLBACK Callback);
void osTimerStart_Stub(CMOCK_osTimerStart_CALLBACK Callback);
#define osTimerStart_StubWithCallback osTimerStart_Stub
#define osTimerStart_IgnoreArg_timer_id() osTimerStart_CMockIgnoreArg_timer_id(__LINE__)
void osTimerStart_CMockIgnoreArg_timer_id(UNITY_LINE_TYPE cmock_line);
#define osTimerStart_IgnoreArg_ticks() osTimerStart_CMockIgnoreArg_ticks(__LINE__)
void osTimerStart_CMockIgnoreArg_ticks(UNITY_LINE_TYPE cmock_line);
#define osTimerStop_Ignore() TEST_FAIL_MESSAGE("osTimerStop requires _IgnoreAndReturn");
#define osTimerStop_IgnoreAndReturn(cmock_retval) osTimerStop_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osTimerStop_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osTimerStop_StopIgnore() osTimerStop_CMockStopIgnore()
void osTimerStop_CMockStopIgnore(void);
#define osTimerStop_ExpectAnyArgs() TEST_FAIL_MESSAGE("osTimerStop requires _ExpectAnyArgsAndReturn");
#define osTimerStop_ExpectAnyArgsAndReturn(cmock_retval) osTimerStop_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osTimerStop_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osTimerStop_Expect(timer_id) TEST_FAIL_MESSAGE("osTimerStop requires _ExpectAndReturn");
#define osTimerStop_ExpectAndReturn(timer_id, cmock_retval) osTimerStop_CMockExpectAndReturn(__LINE__, timer_id, cmock_retval)
void osTimerStop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osTimerId_t timer_id, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_osTimerStop_CALLBACK)(osTimerId_t timer_id, int cmock_num_calls);
void osTimerStop_AddCallback(CMOCK_osTimerStop_CALLBACK Callback);
void osTimerStop_Stub(CMOCK_osTimerStop_CALLBACK Callback);
#define osTimerStop_StubWithCallback osTimerStop_Stub
#define osTimerStop_IgnoreArg_timer_id() osTimerStop_CMockIgnoreArg_timer_id(__LINE__)
void osTimerStop_CMockIgnoreArg_timer_id(UNITY_LINE_TYPE cmock_line);
#define osDelay_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("osDelay requires _Ignore (not AndReturn)");
#define osDelay_Ignore() osDelay_CMockIgnore()
void osDelay_CMockIgnore(void);
#define osDelay_StopIgnore() osDelay_CMockStopIgnore()
void osDelay_CMockStopIgnore(void);
#define osDelay_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("osDelay requires _ExpectAnyArgs (not AndReturn)");
#define osDelay_ExpectAnyArgs() osDelay_CMockExpectAnyArgs(__LINE__)
void osDelay_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define osDelay_ExpectAndReturn(ms, cmock_retval) TEST_FAIL_MESSAGE("osDelay requires _Expect (not AndReturn)");
#define osDelay_Expect(ms) osDelay_CMockExpect(__LINE__, ms)
void osDelay_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ms);
typedef void (* CMOCK_osDelay_CALLBACK)(uint32_t ms, int cmock_num_calls);
void osDelay_AddCallback(CMOCK_osDelay_CALLBACK Callback);
void osDelay_Stub(CMOCK_osDelay_CALLBACK Callback);
#define osDelay_StubWithCallback osDelay_Stub
#define osDelay_IgnoreArg_ms() osDelay_CMockIgnoreArg_ms(__LINE__)
void osDelay_CMockIgnoreArg_ms(UNITY_LINE_TYPE cmock_line);
#define osMessageQueueNew_Ignore() TEST_FAIL_MESSAGE("osMessageQueueNew requires _IgnoreAndReturn");
#define osMessageQueueNew_IgnoreAndReturn(cmock_retval) osMessageQueueNew_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osMessageQueueNew_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osMessageQueueId_t cmock_to_return);
#define osMessageQueueNew_StopIgnore() osMessageQueueNew_CMockStopIgnore()
void osMessageQueueNew_CMockStopIgnore(void);
#define osMessageQueueNew_ExpectAnyArgs() TEST_FAIL_MESSAGE("osMessageQueueNew requires _ExpectAnyArgsAndReturn");
#define osMessageQueueNew_ExpectAnyArgsAndReturn(cmock_retval) osMessageQueueNew_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osMessageQueueNew_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osMessageQueueId_t cmock_to_return);
#define osMessageQueueNew_Expect(msg_count, msg_size, attr) TEST_FAIL_MESSAGE("osMessageQueueNew requires _ExpectAndReturn");
#define osMessageQueueNew_ExpectAndReturn(msg_count, msg_size, attr, cmock_retval) osMessageQueueNew_CMockExpectAndReturn(__LINE__, msg_count, msg_size, attr, cmock_retval)
void osMessageQueueNew_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t msg_count, uint32_t msg_size, void* attr, osMessageQueueId_t cmock_to_return);
typedef osMessageQueueId_t (* CMOCK_osMessageQueueNew_CALLBACK)(uint32_t msg_count, uint32_t msg_size, void* attr, int cmock_num_calls);
void osMessageQueueNew_AddCallback(CMOCK_osMessageQueueNew_CALLBACK Callback);
void osMessageQueueNew_Stub(CMOCK_osMessageQueueNew_CALLBACK Callback);
#define osMessageQueueNew_StubWithCallback osMessageQueueNew_Stub
#define osMessageQueueNew_IgnoreArg_msg_count() osMessageQueueNew_CMockIgnoreArg_msg_count(__LINE__)
void osMessageQueueNew_CMockIgnoreArg_msg_count(UNITY_LINE_TYPE cmock_line);
#define osMessageQueueNew_IgnoreArg_msg_size() osMessageQueueNew_CMockIgnoreArg_msg_size(__LINE__)
void osMessageQueueNew_CMockIgnoreArg_msg_size(UNITY_LINE_TYPE cmock_line);
#define osMessageQueueNew_IgnoreArg_attr() osMessageQueueNew_CMockIgnoreArg_attr(__LINE__)
void osMessageQueueNew_CMockIgnoreArg_attr(UNITY_LINE_TYPE cmock_line);
#define osMessageQueuePut_Ignore() TEST_FAIL_MESSAGE("osMessageQueuePut requires _IgnoreAndReturn");
#define osMessageQueuePut_IgnoreAndReturn(cmock_retval) osMessageQueuePut_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osMessageQueuePut_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osMessageQueuePut_StopIgnore() osMessageQueuePut_CMockStopIgnore()
void osMessageQueuePut_CMockStopIgnore(void);
#define osMessageQueuePut_ExpectAnyArgs() TEST_FAIL_MESSAGE("osMessageQueuePut requires _ExpectAnyArgsAndReturn");
#define osMessageQueuePut_ExpectAnyArgsAndReturn(cmock_retval) osMessageQueuePut_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osMessageQueuePut_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osMessageQueuePut_Expect(queue_id, msg_ptr, msg_prio, timeout) TEST_FAIL_MESSAGE("osMessageQueuePut requires _ExpectAndReturn");
#define osMessageQueuePut_ExpectAndReturn(queue_id, msg_ptr, msg_prio, timeout, cmock_retval) osMessageQueuePut_CMockExpectAndReturn(__LINE__, queue_id, msg_ptr, msg_prio, timeout, cmock_retval)
void osMessageQueuePut_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osMessageQueueId_t queue_id, const void* msg_ptr, uint8_t msg_prio, uint32_t timeout, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_osMessageQueuePut_CALLBACK)(osMessageQueueId_t queue_id, const void* msg_ptr, uint8_t msg_prio, uint32_t timeout, int cmock_num_calls);
void osMessageQueuePut_AddCallback(CMOCK_osMessageQueuePut_CALLBACK Callback);
void osMessageQueuePut_Stub(CMOCK_osMessageQueuePut_CALLBACK Callback);
#define osMessageQueuePut_StubWithCallback osMessageQueuePut_Stub
#define osMessageQueuePut_IgnoreArg_queue_id() osMessageQueuePut_CMockIgnoreArg_queue_id(__LINE__)
void osMessageQueuePut_CMockIgnoreArg_queue_id(UNITY_LINE_TYPE cmock_line);
#define osMessageQueuePut_IgnoreArg_msg_ptr() osMessageQueuePut_CMockIgnoreArg_msg_ptr(__LINE__)
void osMessageQueuePut_CMockIgnoreArg_msg_ptr(UNITY_LINE_TYPE cmock_line);
#define osMessageQueuePut_IgnoreArg_msg_prio() osMessageQueuePut_CMockIgnoreArg_msg_prio(__LINE__)
void osMessageQueuePut_CMockIgnoreArg_msg_prio(UNITY_LINE_TYPE cmock_line);
#define osMessageQueuePut_IgnoreArg_timeout() osMessageQueuePut_CMockIgnoreArg_timeout(__LINE__)
void osMessageQueuePut_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define osMessageQueueGet_Ignore() TEST_FAIL_MESSAGE("osMessageQueueGet requires _IgnoreAndReturn");
#define osMessageQueueGet_IgnoreAndReturn(cmock_retval) osMessageQueueGet_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osMessageQueueGet_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osMessageQueueGet_StopIgnore() osMessageQueueGet_CMockStopIgnore()
void osMessageQueueGet_CMockStopIgnore(void);
#define osMessageQueueGet_ExpectAnyArgs() TEST_FAIL_MESSAGE("osMessageQueueGet requires _ExpectAnyArgsAndReturn");
#define osMessageQueueGet_ExpectAnyArgsAndReturn(cmock_retval) osMessageQueueGet_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osMessageQueueGet_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osMessageQueueGet_Expect(queue_id, msg_ptr, msg_prio, timeout) TEST_FAIL_MESSAGE("osMessageQueueGet requires _ExpectAndReturn");
#define osMessageQueueGet_ExpectAndReturn(queue_id, msg_ptr, msg_prio, timeout, cmock_retval) osMessageQueueGet_CMockExpectAndReturn(__LINE__, queue_id, msg_ptr, msg_prio, timeout, cmock_retval)
void osMessageQueueGet_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osMessageQueueId_t queue_id, void* msg_ptr, uint8_t* msg_prio, uint32_t timeout, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_osMessageQueueGet_CALLBACK)(osMessageQueueId_t queue_id, void* msg_ptr, uint8_t* msg_prio, uint32_t timeout, int cmock_num_calls);
void osMessageQueueGet_AddCallback(CMOCK_osMessageQueueGet_CALLBACK Callback);
void osMessageQueueGet_Stub(CMOCK_osMessageQueueGet_CALLBACK Callback);
#define osMessageQueueGet_StubWithCallback osMessageQueueGet_Stub
#define osMessageQueueGet_IgnoreArg_queue_id() osMessageQueueGet_CMockIgnoreArg_queue_id(__LINE__)
void osMessageQueueGet_CMockIgnoreArg_queue_id(UNITY_LINE_TYPE cmock_line);
#define osMessageQueueGet_IgnoreArg_msg_ptr() osMessageQueueGet_CMockIgnoreArg_msg_ptr(__LINE__)
void osMessageQueueGet_CMockIgnoreArg_msg_ptr(UNITY_LINE_TYPE cmock_line);
#define osMessageQueueGet_IgnoreArg_msg_prio() osMessageQueueGet_CMockIgnoreArg_msg_prio(__LINE__)
void osMessageQueueGet_CMockIgnoreArg_msg_prio(UNITY_LINE_TYPE cmock_line);
#define osMessageQueueGet_IgnoreArg_timeout() osMessageQueueGet_CMockIgnoreArg_timeout(__LINE__)
void osMessageQueueGet_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define osThreadFlagsWait_Ignore() TEST_FAIL_MESSAGE("osThreadFlagsWait requires _IgnoreAndReturn");
#define osThreadFlagsWait_IgnoreAndReturn(cmock_retval) osThreadFlagsWait_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osThreadFlagsWait_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osThreadFlagsWait_StopIgnore() osThreadFlagsWait_CMockStopIgnore()
void osThreadFlagsWait_CMockStopIgnore(void);
#define osThreadFlagsWait_ExpectAnyArgs() TEST_FAIL_MESSAGE("osThreadFlagsWait requires _ExpectAnyArgsAndReturn");
#define osThreadFlagsWait_ExpectAnyArgsAndReturn(cmock_retval) osThreadFlagsWait_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osThreadFlagsWait_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osThreadFlagsWait_Expect(flags, options, timeout) TEST_FAIL_MESSAGE("osThreadFlagsWait requires _ExpectAndReturn");
#define osThreadFlagsWait_ExpectAndReturn(flags, options, timeout, cmock_retval) osThreadFlagsWait_CMockExpectAndReturn(__LINE__, flags, options, timeout, cmock_retval)
void osThreadFlagsWait_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t flags, uint32_t options, uint32_t timeout, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_osThreadFlagsWait_CALLBACK)(uint32_t flags, uint32_t options, uint32_t timeout, int cmock_num_calls);
void osThreadFlagsWait_AddCallback(CMOCK_osThreadFlagsWait_CALLBACK Callback);
void osThreadFlagsWait_Stub(CMOCK_osThreadFlagsWait_CALLBACK Callback);
#define osThreadFlagsWait_StubWithCallback osThreadFlagsWait_Stub
#define osThreadFlagsWait_IgnoreArg_flags() osThreadFlagsWait_CMockIgnoreArg_flags(__LINE__)
void osThreadFlagsWait_CMockIgnoreArg_flags(UNITY_LINE_TYPE cmock_line);
#define osThreadFlagsWait_IgnoreArg_options() osThreadFlagsWait_CMockIgnoreArg_options(__LINE__)
void osThreadFlagsWait_CMockIgnoreArg_options(UNITY_LINE_TYPE cmock_line);
#define osThreadFlagsWait_IgnoreArg_timeout() osThreadFlagsWait_CMockIgnoreArg_timeout(__LINE__)
void osThreadFlagsWait_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define osThreadFlagsSet_Ignore() TEST_FAIL_MESSAGE("osThreadFlagsSet requires _IgnoreAndReturn");
#define osThreadFlagsSet_IgnoreAndReturn(cmock_retval) osThreadFlagsSet_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osThreadFlagsSet_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osThreadFlagsSet_StopIgnore() osThreadFlagsSet_CMockStopIgnore()
void osThreadFlagsSet_CMockStopIgnore(void);
#define osThreadFlagsSet_ExpectAnyArgs() TEST_FAIL_MESSAGE("osThreadFlagsSet requires _ExpectAnyArgsAndReturn");
#define osThreadFlagsSet_ExpectAnyArgsAndReturn(cmock_retval) osThreadFlagsSet_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osThreadFlagsSet_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osThreadFlagsSet_Expect(thread_id, flags) TEST_FAIL_MESSAGE("osThreadFlagsSet requires _ExpectAndReturn");
#define osThreadFlagsSet_ExpectAndReturn(thread_id, flags, cmock_retval) osThreadFlagsSet_CMockExpectAndReturn(__LINE__, thread_id, flags, cmock_retval)
void osThreadFlagsSet_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t thread_id, uint32_t flags, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_osThreadFlagsSet_CALLBACK)(osThreadId_t thread_id, uint32_t flags, int cmock_num_calls);
void osThreadFlagsSet_AddCallback(CMOCK_osThreadFlagsSet_CALLBACK Callback);
void osThreadFlagsSet_Stub(CMOCK_osThreadFlagsSet_CALLBACK Callback);
#define osThreadFlagsSet_StubWithCallback osThreadFlagsSet_Stub
#define osThreadFlagsSet_IgnoreArg_thread_id() osThreadFlagsSet_CMockIgnoreArg_thread_id(__LINE__)
void osThreadFlagsSet_CMockIgnoreArg_thread_id(UNITY_LINE_TYPE cmock_line);
#define osThreadFlagsSet_IgnoreArg_flags() osThreadFlagsSet_CMockIgnoreArg_flags(__LINE__)
void osThreadFlagsSet_CMockIgnoreArg_flags(UNITY_LINE_TYPE cmock_line);
#define HAL_CAN_GetRxMessage_Ignore() TEST_FAIL_MESSAGE("HAL_CAN_GetRxMessage requires _IgnoreAndReturn");
#define HAL_CAN_GetRxMessage_IgnoreAndReturn(cmock_retval) HAL_CAN_GetRxMessage_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_CAN_GetRxMessage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define HAL_CAN_GetRxMessage_StopIgnore() HAL_CAN_GetRxMessage_CMockStopIgnore()
void HAL_CAN_GetRxMessage_CMockStopIgnore(void);
#define HAL_CAN_GetRxMessage_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_CAN_GetRxMessage requires _ExpectAnyArgsAndReturn");
#define HAL_CAN_GetRxMessage_ExpectAnyArgsAndReturn(cmock_retval) HAL_CAN_GetRxMessage_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_CAN_GetRxMessage_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define HAL_CAN_GetRxMessage_Expect(hcan, fifo, rx_header, rx_data) TEST_FAIL_MESSAGE("HAL_CAN_GetRxMessage requires _ExpectAndReturn");
#define HAL_CAN_GetRxMessage_ExpectAndReturn(hcan, fifo, rx_header, rx_data, cmock_retval) HAL_CAN_GetRxMessage_CMockExpectAndReturn(__LINE__, hcan, fifo, rx_header, rx_data, cmock_retval)
void HAL_CAN_GetRxMessage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CAN_HandleTypeDef* hcan, uint32_t fifo, CAN_RxHeaderTypeDef* rx_header, uint8_t* rx_data, int cmock_to_return);
typedef int (* CMOCK_HAL_CAN_GetRxMessage_CALLBACK)(CAN_HandleTypeDef* hcan, uint32_t fifo, CAN_RxHeaderTypeDef* rx_header, uint8_t* rx_data, int cmock_num_calls);
void HAL_CAN_GetRxMessage_AddCallback(CMOCK_HAL_CAN_GetRxMessage_CALLBACK Callback);
void HAL_CAN_GetRxMessage_Stub(CMOCK_HAL_CAN_GetRxMessage_CALLBACK Callback);
#define HAL_CAN_GetRxMessage_StubWithCallback HAL_CAN_GetRxMessage_Stub
#define HAL_CAN_GetRxMessage_IgnoreArg_hcan() HAL_CAN_GetRxMessage_CMockIgnoreArg_hcan(__LINE__)
void HAL_CAN_GetRxMessage_CMockIgnoreArg_hcan(UNITY_LINE_TYPE cmock_line);
#define HAL_CAN_GetRxMessage_IgnoreArg_fifo() HAL_CAN_GetRxMessage_CMockIgnoreArg_fifo(__LINE__)
void HAL_CAN_GetRxMessage_CMockIgnoreArg_fifo(UNITY_LINE_TYPE cmock_line);
#define HAL_CAN_GetRxMessage_IgnoreArg_rx_header() HAL_CAN_GetRxMessage_CMockIgnoreArg_rx_header(__LINE__)
void HAL_CAN_GetRxMessage_CMockIgnoreArg_rx_header(UNITY_LINE_TYPE cmock_line);
#define HAL_CAN_GetRxMessage_IgnoreArg_rx_data() HAL_CAN_GetRxMessage_CMockIgnoreArg_rx_data(__LINE__)
void HAL_CAN_GetRxMessage_CMockIgnoreArg_rx_data(UNITY_LINE_TYPE cmock_line);
#define pdMS_TO_TICKS_Ignore() TEST_FAIL_MESSAGE("pdMS_TO_TICKS requires _IgnoreAndReturn");
#define pdMS_TO_TICKS_IgnoreAndReturn(cmock_retval) pdMS_TO_TICKS_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void pdMS_TO_TICKS_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define pdMS_TO_TICKS_StopIgnore() pdMS_TO_TICKS_CMockStopIgnore()
void pdMS_TO_TICKS_CMockStopIgnore(void);
#define pdMS_TO_TICKS_ExpectAnyArgs() TEST_FAIL_MESSAGE("pdMS_TO_TICKS requires _ExpectAnyArgsAndReturn");
#define pdMS_TO_TICKS_ExpectAnyArgsAndReturn(cmock_retval) pdMS_TO_TICKS_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void pdMS_TO_TICKS_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define pdMS_TO_TICKS_Expect(ms) TEST_FAIL_MESSAGE("pdMS_TO_TICKS requires _ExpectAndReturn");
#define pdMS_TO_TICKS_ExpectAndReturn(ms, cmock_retval) pdMS_TO_TICKS_CMockExpectAndReturn(__LINE__, ms, cmock_retval)
void pdMS_TO_TICKS_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ms, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_pdMS_TO_TICKS_CALLBACK)(uint32_t ms, int cmock_num_calls);
void pdMS_TO_TICKS_AddCallback(CMOCK_pdMS_TO_TICKS_CALLBACK Callback);
void pdMS_TO_TICKS_Stub(CMOCK_pdMS_TO_TICKS_CALLBACK Callback);
#define pdMS_TO_TICKS_StubWithCallback pdMS_TO_TICKS_Stub
#define pdMS_TO_TICKS_IgnoreArg_ms() pdMS_TO_TICKS_CMockIgnoreArg_ms(__LINE__)
void pdMS_TO_TICKS_CMockIgnoreArg_ms(UNITY_LINE_TYPE cmock_line);
#define HAL_ADC_Start_DMA_Ignore() TEST_FAIL_MESSAGE("HAL_ADC_Start_DMA requires _IgnoreAndReturn");
#define HAL_ADC_Start_DMA_IgnoreAndReturn(cmock_retval) HAL_ADC_Start_DMA_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_ADC_Start_DMA_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_ADC_Start_DMA_StopIgnore() HAL_ADC_Start_DMA_CMockStopIgnore()
void HAL_ADC_Start_DMA_CMockStopIgnore(void);
#define HAL_ADC_Start_DMA_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_ADC_Start_DMA requires _ExpectAnyArgsAndReturn");
#define HAL_ADC_Start_DMA_ExpectAnyArgsAndReturn(cmock_retval) HAL_ADC_Start_DMA_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_ADC_Start_DMA_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_ADC_Start_DMA_Expect(hadc, pData, Length) TEST_FAIL_MESSAGE("HAL_ADC_Start_DMA requires _ExpectAndReturn");
#define HAL_ADC_Start_DMA_ExpectAndReturn(hadc, pData, Length, cmock_retval) HAL_ADC_Start_DMA_CMockExpectAndReturn(__LINE__, hadc, pData, Length, cmock_retval)
void HAL_ADC_Start_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* hadc, uint32_t* pData, uint32_t Length, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_ADC_Start_DMA_CALLBACK)(void* hadc, uint32_t* pData, uint32_t Length, int cmock_num_calls);
void HAL_ADC_Start_DMA_AddCallback(CMOCK_HAL_ADC_Start_DMA_CALLBACK Callback);
void HAL_ADC_Start_DMA_Stub(CMOCK_HAL_ADC_Start_DMA_CALLBACK Callback);
#define HAL_ADC_Start_DMA_StubWithCallback HAL_ADC_Start_DMA_Stub
#define HAL_ADC_Start_DMA_IgnoreArg_hadc() HAL_ADC_Start_DMA_CMockIgnoreArg_hadc(__LINE__)
void HAL_ADC_Start_DMA_CMockIgnoreArg_hadc(UNITY_LINE_TYPE cmock_line);
#define HAL_ADC_Start_DMA_IgnoreArg_pData() HAL_ADC_Start_DMA_CMockIgnoreArg_pData(__LINE__)
void HAL_ADC_Start_DMA_CMockIgnoreArg_pData(UNITY_LINE_TYPE cmock_line);
#define HAL_ADC_Start_DMA_IgnoreArg_Length() HAL_ADC_Start_DMA_CMockIgnoreArg_Length(__LINE__)
void HAL_ADC_Start_DMA_CMockIgnoreArg_Length(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_Ignore() TEST_FAIL_MESSAGE("HAL_I2C_Mem_Write requires _IgnoreAndReturn");
#define HAL_I2C_Mem_Write_IgnoreAndReturn(cmock_retval) HAL_I2C_Mem_Write_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Mem_Write_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Write_StopIgnore() HAL_I2C_Mem_Write_CMockStopIgnore()
void HAL_I2C_Mem_Write_CMockStopIgnore(void);
#define HAL_I2C_Mem_Write_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_I2C_Mem_Write requires _ExpectAnyArgsAndReturn");
#define HAL_I2C_Mem_Write_ExpectAnyArgsAndReturn(cmock_retval) HAL_I2C_Mem_Write_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Mem_Write_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Write_Expect(hi2c, devAddress, memAddress, memAddSize, pData, size, timeout) TEST_FAIL_MESSAGE("HAL_I2C_Mem_Write requires _ExpectAndReturn");
#define HAL_I2C_Mem_Write_ExpectAndReturn(hi2c, devAddress, memAddress, memAddSize, pData, size, timeout, cmock_retval) HAL_I2C_Mem_Write_CMockExpectAndReturn(__LINE__, hi2c, devAddress, memAddress, memAddSize, pData, size, timeout, cmock_retval)
void HAL_I2C_Mem_Write_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* hi2c, uint16_t devAddress, uint16_t memAddress, uint16_t memAddSize, uint8_t* pData, uint16_t size, uint32_t timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_I2C_Mem_Write_CALLBACK)(void* hi2c, uint16_t devAddress, uint16_t memAddress, uint16_t memAddSize, uint8_t* pData, uint16_t size, uint32_t timeout, int cmock_num_calls);
void HAL_I2C_Mem_Write_AddCallback(CMOCK_HAL_I2C_Mem_Write_CALLBACK Callback);
void HAL_I2C_Mem_Write_Stub(CMOCK_HAL_I2C_Mem_Write_CALLBACK Callback);
#define HAL_I2C_Mem_Write_StubWithCallback HAL_I2C_Mem_Write_Stub
#define HAL_I2C_Mem_Write_IgnoreArg_hi2c() HAL_I2C_Mem_Write_CMockIgnoreArg_hi2c(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_hi2c(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_devAddress() HAL_I2C_Mem_Write_CMockIgnoreArg_devAddress(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_devAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_memAddress() HAL_I2C_Mem_Write_CMockIgnoreArg_memAddress(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_memAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_memAddSize() HAL_I2C_Mem_Write_CMockIgnoreArg_memAddSize(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_memAddSize(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_pData() HAL_I2C_Mem_Write_CMockIgnoreArg_pData(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_pData(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_size() HAL_I2C_Mem_Write_CMockIgnoreArg_size(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_timeout() HAL_I2C_Mem_Write_CMockIgnoreArg_timeout(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_Ignore() TEST_FAIL_MESSAGE("HAL_I2C_Mem_Read requires _IgnoreAndReturn");
#define HAL_I2C_Mem_Read_IgnoreAndReturn(cmock_retval) HAL_I2C_Mem_Read_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Mem_Read_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Read_StopIgnore() HAL_I2C_Mem_Read_CMockStopIgnore()
void HAL_I2C_Mem_Read_CMockStopIgnore(void);
#define HAL_I2C_Mem_Read_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_I2C_Mem_Read requires _ExpectAnyArgsAndReturn");
#define HAL_I2C_Mem_Read_ExpectAnyArgsAndReturn(cmock_retval) HAL_I2C_Mem_Read_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Mem_Read_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Read_Expect(hi2c, devAddress, memAddress, memAddSize, pData, size, timeout) TEST_FAIL_MESSAGE("HAL_I2C_Mem_Read requires _ExpectAndReturn");
#define HAL_I2C_Mem_Read_ExpectAndReturn(hi2c, devAddress, memAddress, memAddSize, pData, size, timeout, cmock_retval) HAL_I2C_Mem_Read_CMockExpectAndReturn(__LINE__, hi2c, devAddress, memAddress, memAddSize, pData, size, timeout, cmock_retval)
void HAL_I2C_Mem_Read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* hi2c, uint16_t devAddress, uint16_t memAddress, uint16_t memAddSize, uint8_t* pData, uint16_t size, uint32_t timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_I2C_Mem_Read_CALLBACK)(void* hi2c, uint16_t devAddress, uint16_t memAddress, uint16_t memAddSize, uint8_t* pData, uint16_t size, uint32_t timeout, int cmock_num_calls);
void HAL_I2C_Mem_Read_AddCallback(CMOCK_HAL_I2C_Mem_Read_CALLBACK Callback);
void HAL_I2C_Mem_Read_Stub(CMOCK_HAL_I2C_Mem_Read_CALLBACK Callback);
#define HAL_I2C_Mem_Read_StubWithCallback HAL_I2C_Mem_Read_Stub
#define HAL_I2C_Mem_Read_IgnoreArg_hi2c() HAL_I2C_Mem_Read_CMockIgnoreArg_hi2c(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_hi2c(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_devAddress() HAL_I2C_Mem_Read_CMockIgnoreArg_devAddress(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_devAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_memAddress() HAL_I2C_Mem_Read_CMockIgnoreArg_memAddress(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_memAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_memAddSize() HAL_I2C_Mem_Read_CMockIgnoreArg_memAddSize(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_memAddSize(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_pData() HAL_I2C_Mem_Read_CMockIgnoreArg_pData(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_pData(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_size() HAL_I2C_Mem_Read_CMockIgnoreArg_size(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_timeout() HAL_I2C_Mem_Read_CMockIgnoreArg_timeout(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_WritePin_Ignore() TEST_FAIL_MESSAGE("HAL_GPIO_WritePin requires _IgnoreAndReturn");
#define HAL_GPIO_WritePin_IgnoreAndReturn(cmock_retval) HAL_GPIO_WritePin_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_GPIO_WritePin_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_GPIO_WritePin_StopIgnore() HAL_GPIO_WritePin_CMockStopIgnore()
void HAL_GPIO_WritePin_CMockStopIgnore(void);
#define HAL_GPIO_WritePin_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_GPIO_WritePin requires _ExpectAnyArgsAndReturn");
#define HAL_GPIO_WritePin_ExpectAnyArgsAndReturn(cmock_retval) HAL_GPIO_WritePin_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_GPIO_WritePin_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_GPIO_WritePin_Expect(GPIOx, GPIO_Pin, PinState) TEST_FAIL_MESSAGE("HAL_GPIO_WritePin requires _ExpectAndReturn");
#define HAL_GPIO_WritePin_ExpectAndReturn(GPIOx, GPIO_Pin, PinState, cmock_retval) HAL_GPIO_WritePin_CMockExpectAndReturn(__LINE__, GPIOx, GPIO_Pin, PinState, cmock_retval)
void HAL_GPIO_WritePin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint32_t PinState, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_GPIO_WritePin_CALLBACK)(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint32_t PinState, int cmock_num_calls);
void HAL_GPIO_WritePin_AddCallback(CMOCK_HAL_GPIO_WritePin_CALLBACK Callback);
void HAL_GPIO_WritePin_Stub(CMOCK_HAL_GPIO_WritePin_CALLBACK Callback);
#define HAL_GPIO_WritePin_StubWithCallback HAL_GPIO_WritePin_Stub
#define HAL_GPIO_WritePin_IgnoreArg_GPIOx() HAL_GPIO_WritePin_CMockIgnoreArg_GPIOx(__LINE__)
void HAL_GPIO_WritePin_CMockIgnoreArg_GPIOx(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_WritePin_IgnoreArg_GPIO_Pin() HAL_GPIO_WritePin_CMockIgnoreArg_GPIO_Pin(__LINE__)
void HAL_GPIO_WritePin_CMockIgnoreArg_GPIO_Pin(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_WritePin_IgnoreArg_PinState() HAL_GPIO_WritePin_CMockIgnoreArg_PinState(__LINE__)
void HAL_GPIO_WritePin_CMockIgnoreArg_PinState(UNITY_LINE_TYPE cmock_line);
#define HAL_CAN_GetTxMailboxesFreeLevel_Ignore() TEST_FAIL_MESSAGE("HAL_CAN_GetTxMailboxesFreeLevel requires _IgnoreAndReturn");
#define HAL_CAN_GetTxMailboxesFreeLevel_IgnoreAndReturn(cmock_retval) HAL_CAN_GetTxMailboxesFreeLevel_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_CAN_GetTxMailboxesFreeLevel_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_CAN_GetTxMailboxesFreeLevel_StopIgnore() HAL_CAN_GetTxMailboxesFreeLevel_CMockStopIgnore()
void HAL_CAN_GetTxMailboxesFreeLevel_CMockStopIgnore(void);
#define HAL_CAN_GetTxMailboxesFreeLevel_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_CAN_GetTxMailboxesFreeLevel requires _ExpectAnyArgsAndReturn");
#define HAL_CAN_GetTxMailboxesFreeLevel_ExpectAnyArgsAndReturn(cmock_retval) HAL_CAN_GetTxMailboxesFreeLevel_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_CAN_GetTxMailboxesFreeLevel_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_CAN_GetTxMailboxesFreeLevel_Expect(hcan) TEST_FAIL_MESSAGE("HAL_CAN_GetTxMailboxesFreeLevel requires _ExpectAndReturn");
#define HAL_CAN_GetTxMailboxesFreeLevel_ExpectAndReturn(hcan, cmock_retval) HAL_CAN_GetTxMailboxesFreeLevel_CMockExpectAndReturn(__LINE__, hcan, cmock_retval)
void HAL_CAN_GetTxMailboxesFreeLevel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CAN_HandleTypeDef* hcan, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_CAN_GetTxMailboxesFreeLevel_CALLBACK)(CAN_HandleTypeDef* hcan, int cmock_num_calls);
void HAL_CAN_GetTxMailboxesFreeLevel_AddCallback(CMOCK_HAL_CAN_GetTxMailboxesFreeLevel_CALLBACK Callback);
void HAL_CAN_GetTxMailboxesFreeLevel_Stub(CMOCK_HAL_CAN_GetTxMailboxesFreeLevel_CALLBACK Callback);
#define HAL_CAN_GetTxMailboxesFreeLevel_StubWithCallback HAL_CAN_GetTxMailboxesFreeLevel_Stub
#define HAL_CAN_GetTxMailboxesFreeLevel_IgnoreArg_hcan() HAL_CAN_GetTxMailboxesFreeLevel_CMockIgnoreArg_hcan(__LINE__)
void HAL_CAN_GetTxMailboxesFreeLevel_CMockIgnoreArg_hcan(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_TogglePin_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_TogglePin requires _Ignore (not AndReturn)");
#define HAL_GPIO_TogglePin_Ignore() HAL_GPIO_TogglePin_CMockIgnore()
void HAL_GPIO_TogglePin_CMockIgnore(void);
#define HAL_GPIO_TogglePin_StopIgnore() HAL_GPIO_TogglePin_CMockStopIgnore()
void HAL_GPIO_TogglePin_CMockStopIgnore(void);
#define HAL_GPIO_TogglePin_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_TogglePin requires _ExpectAnyArgs (not AndReturn)");
#define HAL_GPIO_TogglePin_ExpectAnyArgs() HAL_GPIO_TogglePin_CMockExpectAnyArgs(__LINE__)
void HAL_GPIO_TogglePin_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_TogglePin_ExpectAndReturn(GPIOx, GPIO_Pin, cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_TogglePin requires _Expect (not AndReturn)");
#define HAL_GPIO_TogglePin_Expect(GPIOx, GPIO_Pin) HAL_GPIO_TogglePin_CMockExpect(__LINE__, GPIOx, GPIO_Pin)
void HAL_GPIO_TogglePin_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin);
typedef void (* CMOCK_HAL_GPIO_TogglePin_CALLBACK)(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, int cmock_num_calls);
void HAL_GPIO_TogglePin_AddCallback(CMOCK_HAL_GPIO_TogglePin_CALLBACK Callback);
void HAL_GPIO_TogglePin_Stub(CMOCK_HAL_GPIO_TogglePin_CALLBACK Callback);
#define HAL_GPIO_TogglePin_StubWithCallback HAL_GPIO_TogglePin_Stub
#define HAL_GPIO_TogglePin_IgnoreArg_GPIOx() HAL_GPIO_TogglePin_CMockIgnoreArg_GPIOx(__LINE__)
void HAL_GPIO_TogglePin_CMockIgnoreArg_GPIOx(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_TogglePin_IgnoreArg_GPIO_Pin() HAL_GPIO_TogglePin_CMockIgnoreArg_GPIO_Pin(__LINE__)
void HAL_GPIO_TogglePin_CMockIgnoreArg_GPIO_Pin(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Transmit_Ignore() TEST_FAIL_MESSAGE("HAL_I2C_Master_Transmit requires _IgnoreAndReturn");
#define HAL_I2C_Master_Transmit_IgnoreAndReturn(cmock_retval) HAL_I2C_Master_Transmit_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Master_Transmit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Transmit_StopIgnore() HAL_I2C_Master_Transmit_CMockStopIgnore()
void HAL_I2C_Master_Transmit_CMockStopIgnore(void);
#define HAL_I2C_Master_Transmit_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_I2C_Master_Transmit requires _ExpectAnyArgsAndReturn");
#define HAL_I2C_Master_Transmit_ExpectAnyArgsAndReturn(cmock_retval) HAL_I2C_Master_Transmit_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Master_Transmit_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Transmit_Expect(hi2c, DevAddress, pData, Size, Timeout) TEST_FAIL_MESSAGE("HAL_I2C_Master_Transmit requires _ExpectAndReturn");
#define HAL_I2C_Master_Transmit_ExpectAndReturn(hi2c, DevAddress, pData, Size, Timeout, cmock_retval) HAL_I2C_Master_Transmit_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Master_Transmit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_I2C_Master_Transmit_CALLBACK)(I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t Timeout, int cmock_num_calls);
void HAL_I2C_Master_Transmit_AddCallback(CMOCK_HAL_I2C_Master_Transmit_CALLBACK Callback);
void HAL_I2C_Master_Transmit_Stub(CMOCK_HAL_I2C_Master_Transmit_CALLBACK Callback);
#define HAL_I2C_Master_Transmit_StubWithCallback HAL_I2C_Master_Transmit_Stub
#define HAL_I2C_Master_Transmit_IgnoreArg_hi2c() HAL_I2C_Master_Transmit_CMockIgnoreArg_hi2c(__LINE__)
void HAL_I2C_Master_Transmit_CMockIgnoreArg_hi2c(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Transmit_IgnoreArg_DevAddress() HAL_I2C_Master_Transmit_CMockIgnoreArg_DevAddress(__LINE__)
void HAL_I2C_Master_Transmit_CMockIgnoreArg_DevAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Transmit_IgnoreArg_pData() HAL_I2C_Master_Transmit_CMockIgnoreArg_pData(__LINE__)
void HAL_I2C_Master_Transmit_CMockIgnoreArg_pData(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Transmit_IgnoreArg_Size() HAL_I2C_Master_Transmit_CMockIgnoreArg_Size(__LINE__)
void HAL_I2C_Master_Transmit_CMockIgnoreArg_Size(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Transmit_IgnoreArg_Timeout() HAL_I2C_Master_Transmit_CMockIgnoreArg_Timeout(__LINE__)
void HAL_I2C_Master_Transmit_CMockIgnoreArg_Timeout(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Receive_Ignore() TEST_FAIL_MESSAGE("HAL_I2C_Master_Receive requires _IgnoreAndReturn");
#define HAL_I2C_Master_Receive_IgnoreAndReturn(cmock_retval) HAL_I2C_Master_Receive_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Master_Receive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Receive_StopIgnore() HAL_I2C_Master_Receive_CMockStopIgnore()
void HAL_I2C_Master_Receive_CMockStopIgnore(void);
#define HAL_I2C_Master_Receive_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_I2C_Master_Receive requires _ExpectAnyArgsAndReturn");
#define HAL_I2C_Master_Receive_ExpectAnyArgsAndReturn(cmock_retval) HAL_I2C_Master_Receive_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Master_Receive_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Receive_Expect(hi2c, DevAddress, pData, Size, Timeout) TEST_FAIL_MESSAGE("HAL_I2C_Master_Receive requires _ExpectAndReturn");
#define HAL_I2C_Master_Receive_ExpectAndReturn(hi2c, DevAddress, pData, Size, Timeout, cmock_retval) HAL_I2C_Master_Receive_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Master_Receive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_I2C_Master_Receive_CALLBACK)(I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t Timeout, int cmock_num_calls);
void HAL_I2C_Master_Receive_AddCallback(CMOCK_HAL_I2C_Master_Receive_CALLBACK Callback);
void HAL_I2C_Master_Receive_Stub(CMOCK_HAL_I2C_Master_Receive_CALLBACK Callback);
#define HAL_I2C_Master_Receive_StubWithCallback HAL_I2C_Master_Receive_Stub
#define HAL_I2C_Master_Receive_IgnoreArg_hi2c() HAL_I2C_Master_Receive_CMockIgnoreArg_hi2c(__LINE__)
void HAL_I2C_Master_Receive_CMockIgnoreArg_hi2c(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Receive_IgnoreArg_DevAddress() HAL_I2C_Master_Receive_CMockIgnoreArg_DevAddress(__LINE__)
void HAL_I2C_Master_Receive_CMockIgnoreArg_DevAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Receive_IgnoreArg_pData() HAL_I2C_Master_Receive_CMockIgnoreArg_pData(__LINE__)
void HAL_I2C_Master_Receive_CMockIgnoreArg_pData(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Receive_IgnoreArg_Size() HAL_I2C_Master_Receive_CMockIgnoreArg_Size(__LINE__)
void HAL_I2C_Master_Receive_CMockIgnoreArg_Size(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Master_Receive_IgnoreArg_Timeout() HAL_I2C_Master_Receive_CMockIgnoreArg_Timeout(__LINE__)
void HAL_I2C_Master_Receive_CMockIgnoreArg_Timeout(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_ReadPin_Ignore() TEST_FAIL_MESSAGE("HAL_GPIO_ReadPin requires _IgnoreAndReturn");
#define HAL_GPIO_ReadPin_IgnoreAndReturn(cmock_retval) HAL_GPIO_ReadPin_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_GPIO_ReadPin_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define HAL_GPIO_ReadPin_StopIgnore() HAL_GPIO_ReadPin_CMockStopIgnore()
void HAL_GPIO_ReadPin_CMockStopIgnore(void);
#define HAL_GPIO_ReadPin_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_GPIO_ReadPin requires _ExpectAnyArgsAndReturn");
#define HAL_GPIO_ReadPin_ExpectAnyArgsAndReturn(cmock_retval) HAL_GPIO_ReadPin_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_GPIO_ReadPin_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define HAL_GPIO_ReadPin_Expect(GPIOx, GPIO_Pin) TEST_FAIL_MESSAGE("HAL_GPIO_ReadPin requires _ExpectAndReturn");
#define HAL_GPIO_ReadPin_ExpectAndReturn(GPIOx, GPIO_Pin, cmock_retval) HAL_GPIO_ReadPin_CMockExpectAndReturn(__LINE__, GPIOx, GPIO_Pin, cmock_retval)
void HAL_GPIO_ReadPin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, int cmock_to_return);
typedef int (* CMOCK_HAL_GPIO_ReadPin_CALLBACK)(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, int cmock_num_calls);
void HAL_GPIO_ReadPin_AddCallback(CMOCK_HAL_GPIO_ReadPin_CALLBACK Callback);
void HAL_GPIO_ReadPin_Stub(CMOCK_HAL_GPIO_ReadPin_CALLBACK Callback);
#define HAL_GPIO_ReadPin_StubWithCallback HAL_GPIO_ReadPin_Stub
#define HAL_GPIO_ReadPin_IgnoreArg_GPIOx() HAL_GPIO_ReadPin_CMockIgnoreArg_GPIOx(__LINE__)
void HAL_GPIO_ReadPin_CMockIgnoreArg_GPIOx(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_ReadPin_IgnoreArg_GPIO_Pin() HAL_GPIO_ReadPin_CMockIgnoreArg_GPIO_Pin(__LINE__)
void HAL_GPIO_ReadPin_CMockIgnoreArg_GPIO_Pin(UNITY_LINE_TYPE cmock_line);
#define __HAL_TIM_GET_COUNTER_Ignore() TEST_FAIL_MESSAGE("__HAL_TIM_GET_COUNTER requires _IgnoreAndReturn");
#define __HAL_TIM_GET_COUNTER_IgnoreAndReturn(cmock_retval) __HAL_TIM_GET_COUNTER_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void __HAL_TIM_GET_COUNTER_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define __HAL_TIM_GET_COUNTER_StopIgnore() __HAL_TIM_GET_COUNTER_CMockStopIgnore()
void __HAL_TIM_GET_COUNTER_CMockStopIgnore(void);
#define __HAL_TIM_GET_COUNTER_ExpectAnyArgs() TEST_FAIL_MESSAGE("__HAL_TIM_GET_COUNTER requires _ExpectAnyArgsAndReturn");
#define __HAL_TIM_GET_COUNTER_ExpectAnyArgsAndReturn(cmock_retval) __HAL_TIM_GET_COUNTER_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void __HAL_TIM_GET_COUNTER_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define __HAL_TIM_GET_COUNTER_Expect(htim) TEST_FAIL_MESSAGE("__HAL_TIM_GET_COUNTER requires _ExpectAndReturn");
#define __HAL_TIM_GET_COUNTER_ExpectAndReturn(htim, cmock_retval) __HAL_TIM_GET_COUNTER_CMockExpectAndReturn(__LINE__, htim, cmock_retval)
void __HAL_TIM_GET_COUNTER_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TIM_HandleTypeDef* htim, int cmock_to_return);
typedef int (* CMOCK___HAL_TIM_GET_COUNTER_CALLBACK)(TIM_HandleTypeDef* htim, int cmock_num_calls);
void __HAL_TIM_GET_COUNTER_AddCallback(CMOCK___HAL_TIM_GET_COUNTER_CALLBACK Callback);
void __HAL_TIM_GET_COUNTER_Stub(CMOCK___HAL_TIM_GET_COUNTER_CALLBACK Callback);
#define __HAL_TIM_GET_COUNTER_StubWithCallback __HAL_TIM_GET_COUNTER_Stub
#define __HAL_TIM_GET_COUNTER_IgnoreArg_htim() __HAL_TIM_GET_COUNTER_CMockIgnoreArg_htim(__LINE__)
void __HAL_TIM_GET_COUNTER_CMockIgnoreArg_htim(UNITY_LINE_TYPE cmock_line);
#define HAL_Delay_Ignore() TEST_FAIL_MESSAGE("HAL_Delay requires _IgnoreAndReturn");
#define HAL_Delay_IgnoreAndReturn(cmock_retval) HAL_Delay_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_Delay_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define HAL_Delay_StopIgnore() HAL_Delay_CMockStopIgnore()
void HAL_Delay_CMockStopIgnore(void);
#define HAL_Delay_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_Delay requires _ExpectAnyArgsAndReturn");
#define HAL_Delay_ExpectAnyArgsAndReturn(cmock_retval) HAL_Delay_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_Delay_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define HAL_Delay_Expect(delay) TEST_FAIL_MESSAGE("HAL_Delay requires _ExpectAndReturn");
#define HAL_Delay_ExpectAndReturn(delay, cmock_retval) HAL_Delay_CMockExpectAndReturn(__LINE__, delay, cmock_retval)
void HAL_Delay_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int delay, int cmock_to_return);
typedef int (* CMOCK_HAL_Delay_CALLBACK)(int delay, int cmock_num_calls);
void HAL_Delay_AddCallback(CMOCK_HAL_Delay_CALLBACK Callback);
void HAL_Delay_Stub(CMOCK_HAL_Delay_CALLBACK Callback);
#define HAL_Delay_StubWithCallback HAL_Delay_Stub
#define HAL_Delay_IgnoreArg_delay() HAL_Delay_CMockIgnoreArg_delay(__LINE__)
void HAL_Delay_CMockIgnoreArg_delay(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
