/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SHT30_H
#define _MOCK_SHT30_H

#include "unity.h"
#include "stubs.h"
#include "sht30.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_sht30_Init(void);
void mock_sht30_Destroy(void);
void mock_sht30_Verify(void);




#define sht30_init_Ignore() TEST_FAIL_MESSAGE("sht30_init requires _IgnoreAndReturn");
#define sht30_init_IgnoreAndReturn(cmock_retval) sht30_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void sht30_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define sht30_init_StopIgnore() sht30_init_CMockStopIgnore()
void sht30_init_CMockStopIgnore(void);
#define sht30_init_ExpectAnyArgs() TEST_FAIL_MESSAGE("sht30_init requires _ExpectAnyArgsAndReturn");
#define sht30_init_ExpectAnyArgsAndReturn(cmock_retval) sht30_init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void sht30_init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define sht30_init_Expect(sht30, write_reg, read_reg, blocking_read_reg, dev_address) TEST_FAIL_MESSAGE("sht30_init requires _ExpectAndReturn");
#define sht30_init_ExpectAndReturn(sht30, write_reg, read_reg, blocking_read_reg, dev_address, cmock_retval) sht30_init_CMockExpectAndReturn(__LINE__, sht30, write_reg, read_reg, blocking_read_reg, dev_address, cmock_retval)
void sht30_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sht30_t* sht30, Write_ptr write_reg, Read_ptr read_reg, Read_ptr blocking_read_reg, uint8_t dev_address, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_sht30_init_CALLBACK)(sht30_t* sht30, Write_ptr write_reg, Read_ptr read_reg, Read_ptr blocking_read_reg, uint8_t dev_address, int cmock_num_calls);
void sht30_init_AddCallback(CMOCK_sht30_init_CALLBACK Callback);
void sht30_init_Stub(CMOCK_sht30_init_CALLBACK Callback);
#define sht30_init_StubWithCallback sht30_init_Stub
#define sht30_init_IgnoreArg_sht30() sht30_init_CMockIgnoreArg_sht30(__LINE__)
void sht30_init_CMockIgnoreArg_sht30(UNITY_LINE_TYPE cmock_line);
#define sht30_init_IgnoreArg_write_reg() sht30_init_CMockIgnoreArg_write_reg(__LINE__)
void sht30_init_CMockIgnoreArg_write_reg(UNITY_LINE_TYPE cmock_line);
#define sht30_init_IgnoreArg_read_reg() sht30_init_CMockIgnoreArg_read_reg(__LINE__)
void sht30_init_CMockIgnoreArg_read_reg(UNITY_LINE_TYPE cmock_line);
#define sht30_init_IgnoreArg_blocking_read_reg() sht30_init_CMockIgnoreArg_blocking_read_reg(__LINE__)
void sht30_init_CMockIgnoreArg_blocking_read_reg(UNITY_LINE_TYPE cmock_line);
#define sht30_init_IgnoreArg_dev_address() sht30_init_CMockIgnoreArg_dev_address(__LINE__)
void sht30_init_CMockIgnoreArg_dev_address(UNITY_LINE_TYPE cmock_line);
#define sht30_toggle_heater_Ignore() TEST_FAIL_MESSAGE("sht30_toggle_heater requires _IgnoreAndReturn");
#define sht30_toggle_heater_IgnoreAndReturn(cmock_retval) sht30_toggle_heater_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void sht30_toggle_heater_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define sht30_toggle_heater_StopIgnore() sht30_toggle_heater_CMockStopIgnore()
void sht30_toggle_heater_CMockStopIgnore(void);
#define sht30_toggle_heater_ExpectAnyArgs() TEST_FAIL_MESSAGE("sht30_toggle_heater requires _ExpectAnyArgsAndReturn");
#define sht30_toggle_heater_ExpectAnyArgsAndReturn(cmock_retval) sht30_toggle_heater_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void sht30_toggle_heater_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define sht30_toggle_heater_Expect(sht30, enable) TEST_FAIL_MESSAGE("sht30_toggle_heater requires _ExpectAndReturn");
#define sht30_toggle_heater_ExpectAndReturn(sht30, enable, cmock_retval) sht30_toggle_heater_CMockExpectAndReturn(__LINE__, sht30, enable, cmock_retval)
void sht30_toggle_heater_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sht30_t* sht30, bool enable, int cmock_to_return);
typedef int (* CMOCK_sht30_toggle_heater_CALLBACK)(sht30_t* sht30, bool enable, int cmock_num_calls);
void sht30_toggle_heater_AddCallback(CMOCK_sht30_toggle_heater_CALLBACK Callback);
void sht30_toggle_heater_Stub(CMOCK_sht30_toggle_heater_CALLBACK Callback);
#define sht30_toggle_heater_StubWithCallback sht30_toggle_heater_Stub
#define sht30_toggle_heater_IgnoreArg_sht30() sht30_toggle_heater_CMockIgnoreArg_sht30(__LINE__)
void sht30_toggle_heater_CMockIgnoreArg_sht30(UNITY_LINE_TYPE cmock_line);
#define sht30_toggle_heater_IgnoreArg_enable() sht30_toggle_heater_CMockIgnoreArg_enable(__LINE__)
void sht30_toggle_heater_CMockIgnoreArg_enable(UNITY_LINE_TYPE cmock_line);
#define sht30_get_temp_humid_Ignore() TEST_FAIL_MESSAGE("sht30_get_temp_humid requires _IgnoreAndReturn");
#define sht30_get_temp_humid_IgnoreAndReturn(cmock_retval) sht30_get_temp_humid_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void sht30_get_temp_humid_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define sht30_get_temp_humid_StopIgnore() sht30_get_temp_humid_CMockStopIgnore()
void sht30_get_temp_humid_CMockStopIgnore(void);
#define sht30_get_temp_humid_ExpectAnyArgs() TEST_FAIL_MESSAGE("sht30_get_temp_humid requires _ExpectAnyArgsAndReturn");
#define sht30_get_temp_humid_ExpectAnyArgsAndReturn(cmock_retval) sht30_get_temp_humid_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void sht30_get_temp_humid_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define sht30_get_temp_humid_Expect(sht30) TEST_FAIL_MESSAGE("sht30_get_temp_humid requires _ExpectAndReturn");
#define sht30_get_temp_humid_ExpectAndReturn(sht30, cmock_retval) sht30_get_temp_humid_CMockExpectAndReturn(__LINE__, sht30, cmock_retval)
void sht30_get_temp_humid_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sht30_t* sht30, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_sht30_get_temp_humid_CALLBACK)(sht30_t* sht30, int cmock_num_calls);
void sht30_get_temp_humid_AddCallback(CMOCK_sht30_get_temp_humid_CALLBACK Callback);
void sht30_get_temp_humid_Stub(CMOCK_sht30_get_temp_humid_CALLBACK Callback);
#define sht30_get_temp_humid_StubWithCallback sht30_get_temp_humid_Stub
#define sht30_get_temp_humid_IgnoreArg_sht30() sht30_get_temp_humid_CMockIgnoreArg_sht30(__LINE__)
void sht30_get_temp_humid_CMockIgnoreArg_sht30(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
