/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CHARGING_H
#define _MOCK_CHARGING_H

#include "unity.h"
#include "stubs.h"
#include "charging.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_charging_Init(void);
void mock_charging_Destroy(void);
void mock_charging_Verify(void);




#define handle_balance_cells_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("handle_balance_cells requires _Ignore (not AndReturn)");
#define handle_balance_cells_Ignore() handle_balance_cells_CMockIgnore()
void handle_balance_cells_CMockIgnore(void);
#define handle_balance_cells_StopIgnore() handle_balance_cells_CMockStopIgnore()
void handle_balance_cells_CMockStopIgnore(void);
#define handle_balance_cells_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("handle_balance_cells requires _ExpectAnyArgs (not AndReturn)");
#define handle_balance_cells_ExpectAnyArgs() handle_balance_cells_CMockExpectAnyArgs(__LINE__)
void handle_balance_cells_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define handle_balance_cells_ExpectAndReturn(bmsdata, cmock_retval) TEST_FAIL_MESSAGE("handle_balance_cells requires _Expect (not AndReturn)");
#define handle_balance_cells_Expect(bmsdata) handle_balance_cells_CMockExpect(__LINE__, bmsdata)
void handle_balance_cells_CMockExpect(UNITY_LINE_TYPE cmock_line, bms_t* bmsdata);
typedef void (* CMOCK_handle_balance_cells_CALLBACK)(bms_t* bmsdata, int cmock_num_calls);
void handle_balance_cells_AddCallback(CMOCK_handle_balance_cells_CALLBACK Callback);
void handle_balance_cells_Stub(CMOCK_handle_balance_cells_CALLBACK Callback);
#define handle_balance_cells_StubWithCallback handle_balance_cells_Stub
#define handle_balance_cells_IgnoreArg_bmsdata() handle_balance_cells_CMockIgnoreArg_bmsdata(__LINE__)
void handle_balance_cells_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
