/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_sht30.h"

static const char* CMockString_blocking_read_reg = "blocking_read_reg";
static const char* CMockString_dev_address = "dev_address";
static const char* CMockString_enable = "enable";
static const char* CMockString_read_reg = "read_reg";
static const char* CMockString_sht30 = "sht30";
static const char* CMockString_sht30_get_temp_humid = "sht30_get_temp_humid";
static const char* CMockString_sht30_init = "sht30_init";
static const char* CMockString_sht30_toggle_heater = "sht30_toggle_heater";
static const char* CMockString_write_reg = "write_reg";

typedef struct _CMOCK_sht30_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  sht30_t* Expected_sht30;
  Write_ptr Expected_write_reg;
  Read_ptr Expected_read_reg;
  Read_ptr Expected_blocking_read_reg;
  uint8_t Expected_dev_address;
  char IgnoreArg_sht30;
  char IgnoreArg_write_reg;
  char IgnoreArg_read_reg;
  char IgnoreArg_blocking_read_reg;
  char IgnoreArg_dev_address;

} CMOCK_sht30_init_CALL_INSTANCE;

typedef struct _CMOCK_sht30_toggle_heater_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  sht30_t* Expected_sht30;
  bool Expected_enable;
  char IgnoreArg_sht30;
  char IgnoreArg_enable;

} CMOCK_sht30_toggle_heater_CALL_INSTANCE;

typedef struct _CMOCK_sht30_get_temp_humid_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  sht30_t* Expected_sht30;
  char IgnoreArg_sht30;

} CMOCK_sht30_get_temp_humid_CALL_INSTANCE;

static struct mock_sht30Instance
{
  char sht30_init_IgnoreBool;
  uint8_t sht30_init_FinalReturn;
  char sht30_init_CallbackBool;
  CMOCK_sht30_init_CALLBACK sht30_init_CallbackFunctionPointer;
  int sht30_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sht30_init_CallInstance;
  char sht30_toggle_heater_IgnoreBool;
  int sht30_toggle_heater_FinalReturn;
  char sht30_toggle_heater_CallbackBool;
  CMOCK_sht30_toggle_heater_CALLBACK sht30_toggle_heater_CallbackFunctionPointer;
  int sht30_toggle_heater_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sht30_toggle_heater_CallInstance;
  char sht30_get_temp_humid_IgnoreBool;
  uint8_t sht30_get_temp_humid_FinalReturn;
  char sht30_get_temp_humid_CallbackBool;
  CMOCK_sht30_get_temp_humid_CALLBACK sht30_get_temp_humid_CallbackFunctionPointer;
  int sht30_get_temp_humid_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sht30_get_temp_humid_CallInstance;
} Mock;


void mock_sht30_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.sht30_init_CallInstance;
  if (Mock.sht30_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_sht30_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.sht30_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.sht30_toggle_heater_CallInstance;
  if (Mock.sht30_toggle_heater_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_sht30_toggle_heater);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.sht30_toggle_heater_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.sht30_get_temp_humid_CallInstance;
  if (Mock.sht30_get_temp_humid_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_sht30_get_temp_humid);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.sht30_get_temp_humid_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_sht30_Init(void)
{
  mock_sht30_Destroy();
}

void mock_sht30_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint8_t sht30_init(sht30_t* sht30, Write_ptr write_reg, Read_ptr read_reg, Read_ptr blocking_read_reg, uint8_t dev_address)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sht30_init);
  cmock_call_instance = (CMOCK_sht30_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sht30_init_CallInstance);
  Mock.sht30_init_CallInstance = CMock_Guts_MemNext(Mock.sht30_init_CallInstance);
  if (Mock.sht30_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sht30_init_FinalReturn;
    Mock.sht30_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.sht30_init_CallbackBool &&
      Mock.sht30_init_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.sht30_init_CallbackFunctionPointer(sht30, write_reg, read_reg, blocking_read_reg, dev_address, Mock.sht30_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_sht30)
  {
    UNITY_SET_DETAILS(CMockString_sht30_init,CMockString_sht30);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_sht30), (void*)(sht30), sizeof(sht30_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_write_reg)
  {
    UNITY_SET_DETAILS(CMockString_sht30_init,CMockString_write_reg);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_write_reg), (void*)(&write_reg), sizeof(Write_ptr), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_read_reg)
  {
    UNITY_SET_DETAILS(CMockString_sht30_init,CMockString_read_reg);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_read_reg), (void*)(&read_reg), sizeof(Read_ptr), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_blocking_read_reg)
  {
    UNITY_SET_DETAILS(CMockString_sht30_init,CMockString_blocking_read_reg);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_blocking_read_reg), (void*)(&blocking_read_reg), sizeof(Read_ptr), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dev_address)
  {
    UNITY_SET_DETAILS(CMockString_sht30_init,CMockString_dev_address);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_dev_address, dev_address, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.sht30_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.sht30_init_CallbackFunctionPointer(sht30, write_reg, read_reg, blocking_read_reg, dev_address, Mock.sht30_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sht30_init(CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance, sht30_t* sht30, Write_ptr write_reg, Read_ptr read_reg, Read_ptr blocking_read_reg, uint8_t dev_address);
void CMockExpectParameters_sht30_init(CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance, sht30_t* sht30, Write_ptr write_reg, Read_ptr read_reg, Read_ptr blocking_read_reg, uint8_t dev_address)
{
  cmock_call_instance->Expected_sht30 = sht30;
  cmock_call_instance->IgnoreArg_sht30 = 0;
  memcpy((void*)(&cmock_call_instance->Expected_write_reg), (void*)(&write_reg),
         sizeof(Write_ptr[sizeof(write_reg) == sizeof(Write_ptr) ? 1 : -1])); /* add Write_ptr to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_write_reg = 0;
  memcpy((void*)(&cmock_call_instance->Expected_read_reg), (void*)(&read_reg),
         sizeof(Read_ptr[sizeof(read_reg) == sizeof(Read_ptr) ? 1 : -1])); /* add Read_ptr to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_read_reg = 0;
  memcpy((void*)(&cmock_call_instance->Expected_blocking_read_reg), (void*)(&blocking_read_reg),
         sizeof(Read_ptr[sizeof(blocking_read_reg) == sizeof(Read_ptr) ? 1 : -1])); /* add Read_ptr to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_blocking_read_reg = 0;
  cmock_call_instance->Expected_dev_address = dev_address;
  cmock_call_instance->IgnoreArg_dev_address = 0;
}

void sht30_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sht30_init_CALL_INSTANCE));
  CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sht30_init_CallInstance = CMock_Guts_MemChain(Mock.sht30_init_CallInstance, cmock_guts_index);
  Mock.sht30_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sht30_init_IgnoreBool = (char)1;
}

void sht30_init_CMockStopIgnore(void)
{
  if(Mock.sht30_init_IgnoreBool)
    Mock.sht30_init_CallInstance = CMock_Guts_MemNext(Mock.sht30_init_CallInstance);
  Mock.sht30_init_IgnoreBool = (char)0;
}

void sht30_init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sht30_init_CALL_INSTANCE));
  CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sht30_init_CallInstance = CMock_Guts_MemChain(Mock.sht30_init_CallInstance, cmock_guts_index);
  Mock.sht30_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void sht30_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sht30_t* sht30, Write_ptr write_reg, Read_ptr read_reg, Read_ptr blocking_read_reg, uint8_t dev_address, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sht30_init_CALL_INSTANCE));
  CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sht30_init_CallInstance = CMock_Guts_MemChain(Mock.sht30_init_CallInstance, cmock_guts_index);
  Mock.sht30_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_sht30_init(cmock_call_instance, sht30, write_reg, read_reg, blocking_read_reg, dev_address);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void sht30_init_AddCallback(CMOCK_sht30_init_CALLBACK Callback)
{
  Mock.sht30_init_IgnoreBool = (char)0;
  Mock.sht30_init_CallbackBool = (char)1;
  Mock.sht30_init_CallbackFunctionPointer = Callback;
}

void sht30_init_Stub(CMOCK_sht30_init_CALLBACK Callback)
{
  Mock.sht30_init_IgnoreBool = (char)0;
  Mock.sht30_init_CallbackBool = (char)0;
  Mock.sht30_init_CallbackFunctionPointer = Callback;
}

void sht30_init_CMockIgnoreArg_sht30(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sht30_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sht30 = 1;
}

void sht30_init_CMockIgnoreArg_write_reg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sht30_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_write_reg = 1;
}

void sht30_init_CMockIgnoreArg_read_reg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sht30_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_read_reg = 1;
}

void sht30_init_CMockIgnoreArg_blocking_read_reg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sht30_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_blocking_read_reg = 1;
}

void sht30_init_CMockIgnoreArg_dev_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sht30_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sht30_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev_address = 1;
}

int sht30_toggle_heater(sht30_t* sht30, bool enable)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sht30_toggle_heater_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sht30_toggle_heater);
  cmock_call_instance = (CMOCK_sht30_toggle_heater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sht30_toggle_heater_CallInstance);
  Mock.sht30_toggle_heater_CallInstance = CMock_Guts_MemNext(Mock.sht30_toggle_heater_CallInstance);
  if (Mock.sht30_toggle_heater_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sht30_toggle_heater_FinalReturn;
    Mock.sht30_toggle_heater_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.sht30_toggle_heater_CallbackBool &&
      Mock.sht30_toggle_heater_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.sht30_toggle_heater_CallbackFunctionPointer(sht30, enable, Mock.sht30_toggle_heater_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_sht30)
  {
    UNITY_SET_DETAILS(CMockString_sht30_toggle_heater,CMockString_sht30);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_sht30), (void*)(sht30), sizeof(sht30_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_enable)
  {
    UNITY_SET_DETAILS(CMockString_sht30_toggle_heater,CMockString_enable);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_enable, enable, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.sht30_toggle_heater_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.sht30_toggle_heater_CallbackFunctionPointer(sht30, enable, Mock.sht30_toggle_heater_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sht30_toggle_heater(CMOCK_sht30_toggle_heater_CALL_INSTANCE* cmock_call_instance, sht30_t* sht30, bool enable);
void CMockExpectParameters_sht30_toggle_heater(CMOCK_sht30_toggle_heater_CALL_INSTANCE* cmock_call_instance, sht30_t* sht30, bool enable)
{
  cmock_call_instance->Expected_sht30 = sht30;
  cmock_call_instance->IgnoreArg_sht30 = 0;
  cmock_call_instance->Expected_enable = enable;
  cmock_call_instance->IgnoreArg_enable = 0;
}

void sht30_toggle_heater_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sht30_toggle_heater_CALL_INSTANCE));
  CMOCK_sht30_toggle_heater_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_toggle_heater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sht30_toggle_heater_CallInstance = CMock_Guts_MemChain(Mock.sht30_toggle_heater_CallInstance, cmock_guts_index);
  Mock.sht30_toggle_heater_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sht30_toggle_heater_IgnoreBool = (char)1;
}

void sht30_toggle_heater_CMockStopIgnore(void)
{
  if(Mock.sht30_toggle_heater_IgnoreBool)
    Mock.sht30_toggle_heater_CallInstance = CMock_Guts_MemNext(Mock.sht30_toggle_heater_CallInstance);
  Mock.sht30_toggle_heater_IgnoreBool = (char)0;
}

void sht30_toggle_heater_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sht30_toggle_heater_CALL_INSTANCE));
  CMOCK_sht30_toggle_heater_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_toggle_heater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sht30_toggle_heater_CallInstance = CMock_Guts_MemChain(Mock.sht30_toggle_heater_CallInstance, cmock_guts_index);
  Mock.sht30_toggle_heater_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void sht30_toggle_heater_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sht30_t* sht30, bool enable, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sht30_toggle_heater_CALL_INSTANCE));
  CMOCK_sht30_toggle_heater_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_toggle_heater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sht30_toggle_heater_CallInstance = CMock_Guts_MemChain(Mock.sht30_toggle_heater_CallInstance, cmock_guts_index);
  Mock.sht30_toggle_heater_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_sht30_toggle_heater(cmock_call_instance, sht30, enable);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void sht30_toggle_heater_AddCallback(CMOCK_sht30_toggle_heater_CALLBACK Callback)
{
  Mock.sht30_toggle_heater_IgnoreBool = (char)0;
  Mock.sht30_toggle_heater_CallbackBool = (char)1;
  Mock.sht30_toggle_heater_CallbackFunctionPointer = Callback;
}

void sht30_toggle_heater_Stub(CMOCK_sht30_toggle_heater_CALLBACK Callback)
{
  Mock.sht30_toggle_heater_IgnoreBool = (char)0;
  Mock.sht30_toggle_heater_CallbackBool = (char)0;
  Mock.sht30_toggle_heater_CallbackFunctionPointer = Callback;
}

void sht30_toggle_heater_CMockIgnoreArg_sht30(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sht30_toggle_heater_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_toggle_heater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sht30_toggle_heater_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sht30 = 1;
}

void sht30_toggle_heater_CMockIgnoreArg_enable(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sht30_toggle_heater_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_toggle_heater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sht30_toggle_heater_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_enable = 1;
}

uint8_t sht30_get_temp_humid(sht30_t* sht30)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sht30_get_temp_humid_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sht30_get_temp_humid);
  cmock_call_instance = (CMOCK_sht30_get_temp_humid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sht30_get_temp_humid_CallInstance);
  Mock.sht30_get_temp_humid_CallInstance = CMock_Guts_MemNext(Mock.sht30_get_temp_humid_CallInstance);
  if (Mock.sht30_get_temp_humid_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sht30_get_temp_humid_FinalReturn;
    Mock.sht30_get_temp_humid_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.sht30_get_temp_humid_CallbackBool &&
      Mock.sht30_get_temp_humid_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.sht30_get_temp_humid_CallbackFunctionPointer(sht30, Mock.sht30_get_temp_humid_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_sht30)
  {
    UNITY_SET_DETAILS(CMockString_sht30_get_temp_humid,CMockString_sht30);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_sht30), (void*)(sht30), sizeof(sht30_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.sht30_get_temp_humid_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.sht30_get_temp_humid_CallbackFunctionPointer(sht30, Mock.sht30_get_temp_humid_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sht30_get_temp_humid(CMOCK_sht30_get_temp_humid_CALL_INSTANCE* cmock_call_instance, sht30_t* sht30);
void CMockExpectParameters_sht30_get_temp_humid(CMOCK_sht30_get_temp_humid_CALL_INSTANCE* cmock_call_instance, sht30_t* sht30)
{
  cmock_call_instance->Expected_sht30 = sht30;
  cmock_call_instance->IgnoreArg_sht30 = 0;
}

void sht30_get_temp_humid_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sht30_get_temp_humid_CALL_INSTANCE));
  CMOCK_sht30_get_temp_humid_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_get_temp_humid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sht30_get_temp_humid_CallInstance = CMock_Guts_MemChain(Mock.sht30_get_temp_humid_CallInstance, cmock_guts_index);
  Mock.sht30_get_temp_humid_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sht30_get_temp_humid_IgnoreBool = (char)1;
}

void sht30_get_temp_humid_CMockStopIgnore(void)
{
  if(Mock.sht30_get_temp_humid_IgnoreBool)
    Mock.sht30_get_temp_humid_CallInstance = CMock_Guts_MemNext(Mock.sht30_get_temp_humid_CallInstance);
  Mock.sht30_get_temp_humid_IgnoreBool = (char)0;
}

void sht30_get_temp_humid_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sht30_get_temp_humid_CALL_INSTANCE));
  CMOCK_sht30_get_temp_humid_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_get_temp_humid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sht30_get_temp_humid_CallInstance = CMock_Guts_MemChain(Mock.sht30_get_temp_humid_CallInstance, cmock_guts_index);
  Mock.sht30_get_temp_humid_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void sht30_get_temp_humid_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sht30_t* sht30, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sht30_get_temp_humid_CALL_INSTANCE));
  CMOCK_sht30_get_temp_humid_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_get_temp_humid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sht30_get_temp_humid_CallInstance = CMock_Guts_MemChain(Mock.sht30_get_temp_humid_CallInstance, cmock_guts_index);
  Mock.sht30_get_temp_humid_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_sht30_get_temp_humid(cmock_call_instance, sht30);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void sht30_get_temp_humid_AddCallback(CMOCK_sht30_get_temp_humid_CALLBACK Callback)
{
  Mock.sht30_get_temp_humid_IgnoreBool = (char)0;
  Mock.sht30_get_temp_humid_CallbackBool = (char)1;
  Mock.sht30_get_temp_humid_CallbackFunctionPointer = Callback;
}

void sht30_get_temp_humid_Stub(CMOCK_sht30_get_temp_humid_CALLBACK Callback)
{
  Mock.sht30_get_temp_humid_IgnoreBool = (char)0;
  Mock.sht30_get_temp_humid_CallbackBool = (char)0;
  Mock.sht30_get_temp_humid_CallbackFunctionPointer = Callback;
}

void sht30_get_temp_humid_CMockIgnoreArg_sht30(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sht30_get_temp_humid_CALL_INSTANCE* cmock_call_instance = (CMOCK_sht30_get_temp_humid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sht30_get_temp_humid_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sht30 = 1;
}

