/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_TIMER_H
#define _MOCK_TIMER_H

#include "unity.h"
#include "stubs.h"
#include "timer.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_timer_Init(void);
void mock_timer_Destroy(void);
void mock_timer_Verify(void);




#define start_timer_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("start_timer requires _Ignore (not AndReturn)");
#define start_timer_Ignore() start_timer_CMockIgnore()
void start_timer_CMockIgnore(void);
#define start_timer_StopIgnore() start_timer_CMockStopIgnore()
void start_timer_CMockStopIgnore(void);
#define start_timer_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("start_timer requires _ExpectAnyArgs (not AndReturn)");
#define start_timer_ExpectAnyArgs() start_timer_CMockExpectAnyArgs(__LINE__)
void start_timer_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define start_timer_ExpectAndReturn(timer, duration, cmock_retval) TEST_FAIL_MESSAGE("start_timer requires _Expect (not AndReturn)");
#define start_timer_Expect(timer, duration) start_timer_CMockExpect(__LINE__, timer, duration)
void start_timer_CMockExpect(UNITY_LINE_TYPE cmock_line, nertimer_t* timer, uint32_t duration);
typedef void (* CMOCK_start_timer_CALLBACK)(nertimer_t* timer, uint32_t duration, int cmock_num_calls);
void start_timer_AddCallback(CMOCK_start_timer_CALLBACK Callback);
void start_timer_Stub(CMOCK_start_timer_CALLBACK Callback);
#define start_timer_StubWithCallback start_timer_Stub
#define start_timer_IgnoreArg_timer() start_timer_CMockIgnoreArg_timer(__LINE__)
void start_timer_CMockIgnoreArg_timer(UNITY_LINE_TYPE cmock_line);
#define start_timer_IgnoreArg_duration() start_timer_CMockIgnoreArg_duration(__LINE__)
void start_timer_CMockIgnoreArg_duration(UNITY_LINE_TYPE cmock_line);
#define cancel_timer_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("cancel_timer requires _Ignore (not AndReturn)");
#define cancel_timer_Ignore() cancel_timer_CMockIgnore()
void cancel_timer_CMockIgnore(void);
#define cancel_timer_StopIgnore() cancel_timer_CMockStopIgnore()
void cancel_timer_CMockStopIgnore(void);
#define cancel_timer_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("cancel_timer requires _ExpectAnyArgs (not AndReturn)");
#define cancel_timer_ExpectAnyArgs() cancel_timer_CMockExpectAnyArgs(__LINE__)
void cancel_timer_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define cancel_timer_ExpectAndReturn(timer, cmock_retval) TEST_FAIL_MESSAGE("cancel_timer requires _Expect (not AndReturn)");
#define cancel_timer_Expect(timer) cancel_timer_CMockExpect(__LINE__, timer)
void cancel_timer_CMockExpect(UNITY_LINE_TYPE cmock_line, nertimer_t* timer);
typedef void (* CMOCK_cancel_timer_CALLBACK)(nertimer_t* timer, int cmock_num_calls);
void cancel_timer_AddCallback(CMOCK_cancel_timer_CALLBACK Callback);
void cancel_timer_Stub(CMOCK_cancel_timer_CALLBACK Callback);
#define cancel_timer_StubWithCallback cancel_timer_Stub
#define cancel_timer_IgnoreArg_timer() cancel_timer_CMockIgnoreArg_timer(__LINE__)
void cancel_timer_CMockIgnoreArg_timer(UNITY_LINE_TYPE cmock_line);
#define is_timer_expired_Ignore() TEST_FAIL_MESSAGE("is_timer_expired requires _IgnoreAndReturn");
#define is_timer_expired_IgnoreAndReturn(cmock_retval) is_timer_expired_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void is_timer_expired_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define is_timer_expired_StopIgnore() is_timer_expired_CMockStopIgnore()
void is_timer_expired_CMockStopIgnore(void);
#define is_timer_expired_ExpectAnyArgs() TEST_FAIL_MESSAGE("is_timer_expired requires _ExpectAnyArgsAndReturn");
#define is_timer_expired_ExpectAnyArgsAndReturn(cmock_retval) is_timer_expired_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void is_timer_expired_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define is_timer_expired_Expect(timer) TEST_FAIL_MESSAGE("is_timer_expired requires _ExpectAndReturn");
#define is_timer_expired_ExpectAndReturn(timer, cmock_retval) is_timer_expired_CMockExpectAndReturn(__LINE__, timer, cmock_retval)
void is_timer_expired_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, nertimer_t* timer, bool cmock_to_return);
typedef bool (* CMOCK_is_timer_expired_CALLBACK)(nertimer_t* timer, int cmock_num_calls);
void is_timer_expired_AddCallback(CMOCK_is_timer_expired_CALLBACK Callback);
void is_timer_expired_Stub(CMOCK_is_timer_expired_CALLBACK Callback);
#define is_timer_expired_StubWithCallback is_timer_expired_Stub
#define is_timer_expired_IgnoreArg_timer() is_timer_expired_CMockIgnoreArg_timer(__LINE__)
void is_timer_expired_CMockIgnoreArg_timer(UNITY_LINE_TYPE cmock_line);
#define is_timer_active_Ignore() TEST_FAIL_MESSAGE("is_timer_active requires _IgnoreAndReturn");
#define is_timer_active_IgnoreAndReturn(cmock_retval) is_timer_active_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void is_timer_active_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define is_timer_active_StopIgnore() is_timer_active_CMockStopIgnore()
void is_timer_active_CMockStopIgnore(void);
#define is_timer_active_ExpectAnyArgs() TEST_FAIL_MESSAGE("is_timer_active requires _ExpectAnyArgsAndReturn");
#define is_timer_active_ExpectAnyArgsAndReturn(cmock_retval) is_timer_active_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void is_timer_active_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define is_timer_active_Expect(timer) TEST_FAIL_MESSAGE("is_timer_active requires _ExpectAndReturn");
#define is_timer_active_ExpectAndReturn(timer, cmock_retval) is_timer_active_CMockExpectAndReturn(__LINE__, timer, cmock_retval)
void is_timer_active_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, nertimer_t* timer, bool cmock_to_return);
typedef bool (* CMOCK_is_timer_active_CALLBACK)(nertimer_t* timer, int cmock_num_calls);
void is_timer_active_AddCallback(CMOCK_is_timer_active_CALLBACK Callback);
void is_timer_active_Stub(CMOCK_is_timer_active_CALLBACK Callback);
#define is_timer_active_StubWithCallback is_timer_active_Stub
#define is_timer_active_IgnoreArg_timer() is_timer_active_CMockIgnoreArg_timer(__LINE__)
void is_timer_active_CMockIgnoreArg_timer(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
