/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_charging.h"

static const char* CMockString_bmsdata = "bmsdata";
static const char* CMockString_handle_balance_cells = "handle_balance_cells";

typedef struct _CMOCK_handle_balance_cells_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bms_t* Expected_bmsdata;
  char IgnoreArg_bmsdata;

} CMOCK_handle_balance_cells_CALL_INSTANCE;

static struct mock_chargingInstance
{
  char handle_balance_cells_IgnoreBool;
  char handle_balance_cells_CallbackBool;
  CMOCK_handle_balance_cells_CALLBACK handle_balance_cells_CallbackFunctionPointer;
  int handle_balance_cells_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE handle_balance_cells_CallInstance;
} Mock;


void mock_charging_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.handle_balance_cells_CallInstance;
  if (Mock.handle_balance_cells_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_handle_balance_cells);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.handle_balance_cells_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_charging_Init(void)
{
  mock_charging_Destroy();
}

void mock_charging_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void handle_balance_cells(bms_t* bmsdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_handle_balance_cells_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_handle_balance_cells);
  cmock_call_instance = (CMOCK_handle_balance_cells_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.handle_balance_cells_CallInstance);
  Mock.handle_balance_cells_CallInstance = CMock_Guts_MemNext(Mock.handle_balance_cells_CallInstance);
  if (Mock.handle_balance_cells_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.handle_balance_cells_CallbackBool &&
      Mock.handle_balance_cells_CallbackFunctionPointer != NULL)
  {
    Mock.handle_balance_cells_CallbackFunctionPointer(bmsdata, Mock.handle_balance_cells_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_bmsdata)
  {
    UNITY_SET_DETAILS(CMockString_handle_balance_cells,CMockString_bmsdata);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bmsdata), (void*)(bmsdata), sizeof(bms_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.handle_balance_cells_CallbackFunctionPointer != NULL)
  {
    Mock.handle_balance_cells_CallbackFunctionPointer(bmsdata, Mock.handle_balance_cells_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_handle_balance_cells(CMOCK_handle_balance_cells_CALL_INSTANCE* cmock_call_instance, bms_t* bmsdata);
void CMockExpectParameters_handle_balance_cells(CMOCK_handle_balance_cells_CALL_INSTANCE* cmock_call_instance, bms_t* bmsdata)
{
  cmock_call_instance->Expected_bmsdata = bmsdata;
  cmock_call_instance->IgnoreArg_bmsdata = 0;
}

void handle_balance_cells_CMockIgnore(void)
{
  Mock.handle_balance_cells_IgnoreBool = (char)1;
}

void handle_balance_cells_CMockStopIgnore(void)
{
  Mock.handle_balance_cells_IgnoreBool = (char)0;
}

void handle_balance_cells_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_handle_balance_cells_CALL_INSTANCE));
  CMOCK_handle_balance_cells_CALL_INSTANCE* cmock_call_instance = (CMOCK_handle_balance_cells_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.handle_balance_cells_CallInstance = CMock_Guts_MemChain(Mock.handle_balance_cells_CallInstance, cmock_guts_index);
  Mock.handle_balance_cells_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void handle_balance_cells_CMockExpect(UNITY_LINE_TYPE cmock_line, bms_t* bmsdata)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_handle_balance_cells_CALL_INSTANCE));
  CMOCK_handle_balance_cells_CALL_INSTANCE* cmock_call_instance = (CMOCK_handle_balance_cells_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.handle_balance_cells_CallInstance = CMock_Guts_MemChain(Mock.handle_balance_cells_CallInstance, cmock_guts_index);
  Mock.handle_balance_cells_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_handle_balance_cells(cmock_call_instance, bmsdata);
}

void handle_balance_cells_AddCallback(CMOCK_handle_balance_cells_CALLBACK Callback)
{
  Mock.handle_balance_cells_IgnoreBool = (char)0;
  Mock.handle_balance_cells_CallbackBool = (char)1;
  Mock.handle_balance_cells_CallbackFunctionPointer = Callback;
}

void handle_balance_cells_Stub(CMOCK_handle_balance_cells_CALLBACK Callback)
{
  Mock.handle_balance_cells_IgnoreBool = (char)0;
  Mock.handle_balance_cells_CallbackBool = (char)0;
  Mock.handle_balance_cells_CallbackFunctionPointer = Callback;
}

void handle_balance_cells_CMockIgnoreArg_bmsdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_handle_balance_cells_CALL_INSTANCE* cmock_call_instance = (CMOCK_handle_balance_cells_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.handle_balance_cells_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bmsdata = 1;
}

